### ISSUE TITLE
[ungoogled-chromium] issue with glslang

### ISSUE THREAD

**Issue by frstrikerman** [PF4Public/gentoo-overlay#1]
While configuring ungoogled-chromium I got this error
https://bpaste.net/show/0nnY
http://dpaste.com/3AQ22ZP

**Comment by frstrikerman** [comment]
0.1616
-------- Original Message --------

**Comment by frstrikerman** [comment]
It does work after downgrading

**Comment by PF4Public** [comment]
I assume, that this bug could be closed then.
