### ISSUE TITLE
www-client/ungoogled-chromium-93.0.4577.63-r1: USE=cfi, clang<13 fails to compile

### ISSUE THREAD

**Issue by 0xC0ncord** [PF4Public/gentoo-overlay#100]
It seems that as of Chromium 93, building with CFI now requires clang>=13, as clang 13 has changed the argument `fsanitize-blacklist=` to `-fsanitize-ignorelist=`. Trying to build Chromium 93 with an older version of clang results in the following build error:
```
clang++: error: unknown argument: '-fsanitize-ignorelist=../../tools/cfi/ignores.txt'
```

This looks easy enough to fix with a patch for older versions of clang until clang 13 gets keyworded in Gentoo. Ideally such a patch should probably be applied during the patching phase if the version of clang being used is not 13 or higher.

**Comment by PF4Public** [comment]
Right! I noticed this in one of the failing tests, but didn't have the time to investigate further as I don't usually build with `cfi`.

I would gladly accept a PR with the patch if someone manages to fix this.

**Comment by 0xC0ncord** [comment]
I will look into this tonight and test. Should hopefully have a working patch afterwards.

**Comment by 0xC0ncord** [comment]
The linked pull request fixed the issue for me. I was able to build ungoogled-chromium 93 with USE=cfi and using clang 12.
