### ISSUE TITLE
www-client/ungoogled-chromium-94.0.4606.81-r1: /usr/bin/../include/c++/v1/stddef.h:17:15: fatal error: 'stddef.h' file not found

### ISSUE THREAD

**Issue by perfect7gentleman** [PF4Public/gentoo-overlay#103]
build.log - http://dpaste.com//7LTRDU5GJ

**Comment by PF4Public** [comment]
That's weird. For me it got past `convert_dict` and `mksnapshot` without failures.
![image](https://user-images.githubusercontent.com/10319700/136590984-cf549dc0-f495-479b-be3f-5312444a5aa6.png)
