### ISSUE TITLE
www-client/ungoogled-chromium: new variables

### ISSUE THREAD

**Issue by PF4Public** [PF4Public/gentoo-overlay#104]
I've just added some variables into ungoogled-chromium ebuild in db57783283c1127562a4988b9919be2f327cb036.

It would be awesome if someone could test whether they work as intended. 
cc @0xC0ncord

**Comment by 0xC0ncord** [comment]
Just to test, I have this in ungoogled-chromium's env:
```
UGC_SKIP_PATCHES="disable-gaia.patch disable-gcm.patch"
```
and I see this output:
```
...
 * Removing disable-gaia.patch disable-gcm.patch
...
```

Is that right? Looking at the code I expected to see each omitted patch on a separate line from `einfo`, so I'm not sure if it's working as intended or if I am not using that variable correctly.

**Comment by PF4Public** [comment]
> Is that right? Looking at the code I expected to see each omitted patch on a separate line from `einfo`, so I'm not sure if it's working as intended or if I am not using that variable correctly.

Weird. Should be separate lines. I'll look at it later.

**Comment by PF4Public** [comment]
Looks like I wrongly enclosed variables in quotes. Should be good now. I see that `disable-gaia.patch` was removed from `series` and wasn't applied.

Please test again when you have the chance.

**Comment by 0xC0ncord** [comment]
Sorry for the delay. I just tested it and it seems to be working!

**Comment by PF4Public** [comment]
Thanks!
