### ISSUE TITLE
www-client/ungoogled-chromium-95: vaapi on X11 is broken

### ISSUE THREAD

**Issue by dagraver** [PF4Public/gentoo-overlay#108]
With v95, vaapi on X11 is broken and won't be fixed until v96. Until then, the attached patch (taken from Arch Linux) will restore this functionality.

Please remember to set 'use_vaapi_x11=true' -- This seems to be an addition to the normal use_vaapi!

I have tested this by putting the patch in my local patches and setting the aforementioned use_vaapi_x11=true and confirm vaapi again works on X11

From the patch:

> 
> This patch fixes VA-API usage with Ozone/X11 backend (which
> is our default backend now as X11 has been deprecated -
> crrev.com/c/3114071)).
> 
> non-Ozone X11 is disabled now and Ozone is always used
> on Linux. However, VA-API implementation is not Ozone friendly
> yet and requires major refactoring. But given that VA-API
> implementation on Linux worked only with X11, it's fine for
> now to change USE_X11 and !IsUsingOzonePlatform to
> BUILDFLAG(OZONE_PLATFORM_X11) and fail VA-API initialization
> in VADisplayState::Initialize for Ozone/Linux other than
> non-X11 backends.
> 
> Bug: 1121948

[ozone-x11-fix-VA-API.patch.txt](https://github.com/PF4Public/gentoo-overlay/files/7444681/ozone-x11-fix-VA-API.patch.txt)

**Comment by gringus** [comment]
Patch seems to conflict with vdpau patch (vdpau has to be disabled).

**Comment by gringus** [comment]
I can confirm that after disabling `vdpau` and following above instructions I get hardware acceleration back.

**Comment by PF4Public** [comment]
Thanks for testing!

**Comment by PF4Public** [comment]
I've pushed 96 and removed this vaapi patch. Please test if `vaapi` still works, when you have the chance.

**Comment by gringus** [comment]
Looks like `vdpau-support-r3.patch` needs to be adjusted for 96. It fails to apply.

**Comment by PF4Public** [comment]
Yep, 2bf07fcf4b1bb32d03bf5f92fb95ad1b456f5247

**Comment by gringus** [comment]
I ran into https://bugs.gentoo.org/823857 while building. Bug is reported by somebody else.

**Comment by gringus** [comment]
More info at https://forums.gentoo.org/viewtopic-p-8644495.html?sid=fe1f3342f2f1163902b0f11cd3f3f1b5
Seems to be glibc 2.34 related

**Comment by PF4Public** [comment]
I use stable glibc and it is still building for me, no errors so far.

**Comment by gringus** [comment]
It's affecting `glibc-2.34+` only. Gentoo bug has already a working patch (I tried very similar one with the same success).
BTW: I can confirm ungoogled-chromium-96 has hardware video acceleration working.
