### ISSUE TITLE
www-client/ungoogled-chromium-95.0.4638.69-r1: Preparations fail if Clang is not already installed

### ISSUE THREAD

**Issue by arbitrary-dev** [PF4Public/gentoo-overlay#111]
https://github.com/PF4Public/gentoo-overlay/blob/master/www-client/ungoogled-chromium/ungoogled-chromium-95.0.4638.69-r1.ebuild#L223

...though I see Clang in the list of packages to be emerged.

**Comment by PF4Public** [comment]
So what is the issue you are facing?

**Comment by PF4Public** [comment]
See the issues #86 and #84

**Comment by arbitrary-dev** [comment]
Still confusing. Preparations step requires Clang of the correct version to be ALREADY installed. Though Clang is added to the emerge list.

**Comment by PF4Public** [comment]
I can understand that, but this confusion vanishes just after you have installed clang at least once.
