### ISSUE TITLE
Does ungoogled-chromium-bin is compiled with pgo and thinlto USE flags?

### ISSUE THREAD

**Issue by mortezadadgar** [PF4Public/gentoo-overlay#112]
well I can't find any information about this anywhere either in chromium itself or ebuild

**Comment by PF4Public** [comment]
Yes, they are.

**Comment by mortezadadgar** [comment]
Thanks!

**Comment by PF4Public** [comment]
> Yes, they are.

Except i686. I remember I had to disable thinlto there for some reason. `pgo` is still enabled there.

**Comment by mortezadadgar** [comment]
> Yes, they are.

Also CFI? is there anyway I can check it except asking you

**Comment by PF4Public** [comment]
> Also CFI

No. Neither is built with `cfi`

**Comment by mortezadadgar** [comment]
> > Also CFI
> 
> No. Neither is built with `cfi`

Any reason for not doing it?

**Comment by PF4Public** [comment]
> Any reason for not doing it?

https://github.com/PF4Public/gentoo-overlay/blob/93c78039ee4c686e021a39f2dd50ea951526d356/www-client/ungoogled-chromium/ungoogled-chromium-96.0.4664.45-r1.ebuild#L247-L252
