### ISSUE TITLE
dev-util/electron-13.6.1 is not compatible with dev-util/gn-0.1943

### ISSUE THREAD

**Issue by aleclearmind** [PF4Public/gentoo-overlay#114]
As per title, recent versions of `gn` (Gentoo currently provides 0.1943) seem to have changed the way in which visibility of items can be specified.
For instance, `//third_party/googletest:gtest_config` specifies `:*` no longer matches `//testing/gmock:gmock`.

Relevant error:
```
$ USE="-system-harfbuzz -system-ffmpeg -system-icu -system-jsoncpp -system-libevent -system-openh264 -system-re2" emerge -v electron
...
gn gen --args= is_clang=true clang_use_chrome_plugins=false custom_toolchain="//build/toolchain/linux/unbundle:default" host_toolchain="//build/toolchain/linux/unbundle:default" is_debug=false use_allocator="partition" enable_nacl=false use_system_harfbuzz=true use_gnome_keyring=false enable_js_type_check=false enable_hangout_services_extension=false use_cups=true use_kerberos=
false use_pulseaudio=true use_vaapi=false link_pulseaudio=true chrome_pgo_phase=0 use_thin_lto=false thin_lto_enable_optimizations=false optimize_webui=false use_system_freetype=false use_sy
stem_libopenjpeg2=false enable_pdf=true use_system_lcms2=true enable_print_preview=true enable_mdns=false enable_mse_mpeg2ts_stream_parser=true enable_nacl_nonsfi=false enable_one_click_sign
in=false enable_reading_list=false enable_remoting=false enable_service_discovery=false exclude_unwind_tables=true use_official_google_api_keys=false google_api_key="" google_default_client_
id="" google_default_client_secret="" safe_browsing_mode=0 use_unofficial_version_number=false blink_symbol_level=0 symbol_level=0 enable_iterator_debugging=false enable_swiftshader=false bu
ild_with_tflite_lib=false use_system_libjpeg=true use_system_zlib=true rtc_build_examples=false fieldtrial_testing_like_official_build=true use_gold=false use_sysroot=false use_custom_libcxx
=false use_lld=true enable_pseudolocales=false proprietary_codecs=true ffmpeg_branding="Chrome" target_cpu="x64" treat_warnings_as_errors=false fatal_linker_warnings=false use_ozone=true ozo
ne_auto_platforms=false ozone_platform_headless=true is_official_build=true import("//electron/build/args/release.gn")  out/Release
ERROR at //testing/gmock/BUILD.gn:9:1: Dependency not allowed.
source_set("gmock") {
^--------------------
The item //testing/gmock:gmock
can not depend on //third_party/googletest:gtest_config
because it is not in //third_party/googletest:gtest_config's visibility list: [
  //third_party/googletest:*
]
```                                                                                                                                                                                       

Adding `//testing/gmock:gmock` to `visibility` in `config("gtest_config")` in `third_party/googletest/BUILD.gn` overcomes the issue, but a similar one arises.

`dev-util/gn-0.1807` works fine.

**Comment by PF4Public** [comment]
I may put `<dev-util/gn-0.1943` in DEPS if it helps…

**Comment by aleclearmind** [comment]
Yes, I think that's the right fix.
I'm not sure how this works, but isn't there a reliable place where the `gn` version that is supported is reported?

**Comment by PF4Public** [comment]
> a reliable place where the `gn` version that is supported is reported

DEPS :)

**Comment by aleclearmind** [comment]
Ah, `gn` is bundled. Maybe we need a `system-gn` USE flag.

**Comment by PF4Public** [comment]
> Maybe we need a `system-gn` USE flag.

Probbaly. I'm still hoping that `vscode` and `element` switch to a higher version, so this won't be needed.

**Comment by PF4Public** [comment]
@aleclearmind In case you're insterested, I've added `electron-16` USE flag to vscode and element-desktop. For now it is only available at live versions, but it will sneak into ordinary ebuilds with version bumps.

PS: seems to be functional:
![image](https://user-images.githubusercontent.com/10319700/147156111-86fa5d2b-9e2c-49c5-ae24-9e6d95c8a22a.png)

**Comment by PF4Public** [comment]
> can you advise

Use the older one obviously.

**Comment by liliangnike** [comment]
Yes. Understood. The key point is I don't know how to revert gn version back in WebRTC. Let me do more investigation on this. Thanks!
