### ISSUE TITLE
www-client/ungoogled-chromium: Drop dep on sys-apps/hwids

### ISSUE THREAD

**Issue by gringus** [PF4Public/gentoo-overlay#117]
Currently it's not possible to build `ungoogled-chromium` as `hwids` dependency conflicts with `systemd-249.6-r1`. Gentoo folks already dropped it for `chromium` in https://github.com/gentoo/gentoo/commit/40be71636602aab31d898255e00bfe2f462322e2#diff-6cca3c2b1171956a14d3519d78033b8c7801914e3e7760fb9c76613df641cfec

**Comment by PF4Public** [comment]
Sure! Thanks!
