### ISSUE TITLE
www-client/ungoogled-chromium-96.0.4664.45-r1 does not regard font scaling settings

### ISSUE THREAD

**Issue by logrusx** [PF4Public/gentoo-overlay#118]
I'm using something like 2k screen and up until now I did pretty fine with setting font scale factor to 1.5 in Gnome Tweaks. Today I updated to 96.0.4664.45-r1 and I noticed a few sites looked strange. For example, Facebook had somehow normal size fonts, but it had been centered and with wide empty areas on both sides. Then I noticed the text in the tabs was tiny. I tried to change minimum font sizes, but this didn't change much until I figured I had updated to 96. I reverted back to 95.0.4638.69-r1 and everything is as it was before.

I hope this is not a change from the upstream.

Portage 3.0.28 (python 3.9.8-final-0, default/linux/amd64/17.1/desktop/gnome/systemd, gcc-11.2.0, glibc-2.33-r7, 5.15.1-def x86_64)

=================================================================

System uname: Linux-5.15.1-def-x86_64-AMD_Ryzen_7_5800H_with_Radeon_Graphics-with-glibc2.33
KiB Mem:    28668344 total,  26519476 free
KiB Swap:   67108860 total,  67108860 free
Timestamp of repository gentoo: Mon, 29 Nov 2021 13:36:42 +0000
Head commit of repository gentoo: 9375c3bd35f684feed288f71a1c4e96003c3e9d8

Timestamp of repository pentoo: Mon, 29 Nov 2021 01:49:38 +0000
Head commit of repository pentoo: 7f16e8b835d05b1c0e04c510ffdb3814c1e73e68

Timestamp of repository pf4public: Mon, 29 Nov 2021 11:36:22 +0000
Head commit of repository pf4public: af5d5455f7457fbf659e49e4a42945fcbf52baf2

Head commit of repository supertux88: 5bc8538bdb96f577c42eac0c21310671d73dea54

sh bash 5.1_p8
ld GNU ld (Gentoo 2.37_p1 p0) 2.37
ccache version 4.4.2 [disabled]
app-shells/bash:          5.1_p8::gentoo
dev-java/java-config:     2.3.1::gentoo
dev-lang/perl:            5.34.0-r3::gentoo
dev-lang/python:          2.7.18_p13::gentoo, 3.9.8::gentoo
dev-lang/rust:            1.56.1::gentoo
dev-util/ccache:          4.4.2::gentoo
dev-util/cmake:           3.20.5::gentoo
sys-apps/baselayout:      2.7-r3::gentoo
sys-apps/sandbox:         2.25::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.71-r1::gentoo
sys-devel/automake:       1.16.4::gentoo
sys-devel/binutils:       2.37_p1::gentoo
sys-devel/gcc:            11.2.0::gentoo
sys-devel/gcc-config:     2.4::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.15::gentoo (virtual/os-headers)
sys-libs/glibc:           2.33-r7::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: git
    sync-uri: https://git.gentoo.org/repo/sync/gentoo.git/
    priority: -1000

devrepo
    location: /var/db/repos/devrepo
    masters: gentoo
    priority: 0

pentoo
    location: /var/db/repos/pentoo
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/pentoo.git
    masters: gentoo

pf4public
    location: /var/db/repos/pf4public
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/pf4public.git
    masters: gentoo

supertux88
    location: /var/db/repos/supertux88
    sync-type: git
    sync-uri: https://github.com/SuperTux88/gentoo-overlay.git
    masters: gentoo

localrepo
    location: /var/db/repos/localrepo
    masters: gentoo
    priority: 1

Installed sets: @desktop, @programming, @utils
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/gnupg/qualified.txt /usr/share/maven-bin-3.8/conf"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=native -O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=native -O2 -pipe"
GENTOO_MIRRORS="http://mirrors.xservers.ro/gentoo/"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 bluetooth branding bzip2 cairo cli colord crypt cups dbus dri dts dvd eds emboss encode evo exif flac fortran gdbm gif gnome gnome-keyring gpm gstreamer gtk gui iconv icu introspection ipv6 jpeg lcms libglvnd libnotify libsecret libtirpc mad mng mp3 mp4 mpeg multilib nautilus ncurses networkmanager nls nptl ogg opengl openmp pam pango pcre pdf png policykit ppds pulseaudio qt5 readline sdl seccomp spell split-usr ssl startup-notification svg sysprof systemd tiff tracker truetype udev udisks unicode upower usb vorbis wayland wxwidgets x264 xattr xcb xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2020" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev libinput synaptics" KERNEL="linux" L10N="bg bg-BG en en-US" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-3 php7-4" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_9" PYTHON_TARGETS="python3_9" RUBY_TARGETS="ruby26 ruby27" USERLAND="GNU" VIDEO_CARDS="nvidia amdgpu" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, MAKEOPTS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RUSTFLAGS

**Comment by PF4Public** [comment]
> I hope this is not a change from the upstream.

I'm afraid It is. Either that, or something with your system settings. I didn't notice anything like that on both 123 dpi and 142 dpi screens after updating to 96. On both screens setting the corresponding dpi does the scaling properly.

**Comment by logrusx** [comment]
Thank you for your response!

> I'm afraid It is. Either that, or something with your system settings.
Well it shouldn't be the settings, as:
1) I didn't change anything, except adding harfbuzz flag to freetype (as portage warned me some things might look bad), but
2) 95 version works as before, despite that change and the other updated packages.
> I didn't notice anything like that on both 123 dpi and 142 dpi screens after updating to 96.
I don't think much can be noticed for that small change. My screen is 2560x1600@16'' which is marked as 189 PPI. Any ideas of what I can try locally to test?

Regards

**Comment by PF4Public** [comment]
> Any ideas of what I can try locally to test?

I'd suggest setting proper dpi and a scaling of 1 in your DE.

>I don't think much can be noticed for that small change.

You are taking this out of context. The context was: "Then I noticed the text in the tabs was tiny." → and the reply was "I didn't notice anything like that on _both_ […] screens"

**Comment by logrusx** [comment]
Just emerged original chromium and it works as expected. I tried to emerge ungoogle-chromium with the system-* use flags not present in original chromium disabled and I hit #115. I'll comment there too.

**Comment by logrusx** [comment]
It turns out after disabling ozone platform (although I'm using the integrated GPU and not the NVIDIA one), things look fine, which suggests a change from the upstream after all.
I'm closing this issue as there's a solution.
p.s. the bin version is not affected by this issue, possibly because it's built without Wayland support. Could you please confirm if the latter is so?
Thanks!

**Comment by PF4Public** [comment]
> it's built without Wayland support

Correct.
