### ISSUE TITLE
www-client/ungoogled-chromium-96.0.4664.110-r1 - ld.lld: error: undefined symbol: snappy::Compress'

### ISSUE THREAD

**Issue by Bogdan107** [PF4Public/gentoo-overlay#119]
`www-client/ungoogled-chromim` compilation fails with **clang** use flag, if _app-arch/snappy_ compiled with **gcc**.
Rebuilding `app-arch/snappy` package with **clang** compiler resolve this error.

### [build.log.txt](https://github.com/PF4Public/gentoo-overlay/files/7739973/build.log.txt)
File truncated to reduce file size.
```
$ cat ungoogled-chromium-96.0.4664.110-r1:20211218-140043.log | head -n2 > build.log.txt
$ echo " " >> build.log.txt
$ cat ungoogled-chromium-96.0.4664.110-r1:20211218-140043.log | tail -n100 >> build.log.txt
```
### [emerge.info](https://github.com/PF4Public/gentoo-overlay/files/7739963/emerge.info.txt)
```
$ emerge --info ungoogled-chromium > emerge.info
```
### Compiler configuration for successful build:
```
$ grep -r app-arch/snappy /etc/portage/package*
/etc/portage/package.accept_keywords/custom:app-arch/snappy
/etc/portage/package.env:app-arch/snappy compiler-clang

$ cat /etc/portage/env/compiler-clang | grep -v -e "^#" -e "^[[:space:]]*$"  
    CXXFLAGS="${CFLAGS} -stdlib=libc++"
    LDFLAGS="${LDFLAGS} -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind"
    LDFLAGS="${LDFLAGS} -lc++abi"
    LDFLAGS="${LDFLAGS} -fuse-ld=lld -flto=thin"
    CC="clang"
    CXX="clang++"
    LD="ld.lld"
    AR="llvm-ar"
    NM="llvm-nm"
    RANLIB="llvm-ranlib"
    COMMON_FLAGS_ADD="${COMMON_FLAGS} -mllvm -align-all-functions=5 -flto=thin"
    CFLAGS="${CFLAGS} ${COMMON_FLAGS_ADD}"
    CXXFLAGS="${CXXFLAGS} ${COMMON_FLAGS_ADD}"
```

**Comment by PF4Public** [comment]
You re building with libc++, you should've received the following warning:

https://github.com/PF4Public/gentoo-overlay/blob/572ba3a9de64d20d3fbaf8c325d9a0c0294ef252/www-client/ungoogled-chromium/ungoogled-chromium-96.0.4664.110-r1.ebuild#L236-L243
