### ISSUE TITLE
dev-util/electron-16.0.5: doesn't compile with python 3.10

### ISSUE THREAD

**Issue by t0b3** [PF4Public/gentoo-overlay#121]
ebuild ./electron-16.0.5.ebuild failed with errormsg:
```
 * Configuring bundled nodejs...
Node.js configure: Found Python 3.10.1...
Please use python3.9 or python3.8 or python3.7 or python3.6.
```
the attached patch helps to compile as expected :-)
[conf_py310.patch](https://github.com/PF4Public/gentoo-overlay/files/7773681/conf_py310.patch.txt)

**Comment by PF4Public** [comment]
That's probably the patch I forgot to copy from 96 chromium :)
