### ISSUE TITLE
www-client/ungoogled-chromium: crash on >=wlroots-0.15.0

### ISSUE THREAD

**Issue by 0xC0ncord** [PF4Public/gentoo-overlay#129]
This is an upstream Chromium bug that causes Chromium to crash on the newer version of the wayland protocol that was introduced recently when used with wlroots. I managed to backport the patch and compile ungoogled-chromium successfully with it and I can run it under ozone with sway 1.7. I have no issue continuing to apply the patch locally, but maybe we should apply it in the ebuild for other users as well if `USE=wayland`.

I had to make a slight modification to the patch in order for it to apply cleanly though:
```
--- Downloads/dd4c3dd.diff	2022-01-27 11:37:34.865530422 -0500
+++ /etc/portage/patches/www-client/ungoogled-chromium/chromium-wayland-fixed-terminate-caused-by-binding-to-wrong-version.patch	2022-01-26 15:15:47.138624683 -0500
@@ -211,7 +211,7 @@
  namespace ui {
  
  namespace {
--constexpr uint32_t kMaxSurfaceAugmenterVersion = 2;
+-constexpr uint32_t kMaxSurfaceAugmenterVersion = 1;
 +constexpr uint32_t kMinVersion = 1;
 +constexpr uint32_t kMaxVersion = 2;
  }
```

Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1279574
Upstream patch: https://chromium-review.googlesource.com/c/chromium/src/+/3337037

**Comment by PF4Public** [comment]
> for other users as well if `USE=wayland`

Is it needed to also check for >=wlroots-0.15.0 before applying this patch?

**Comment by 0xC0ncord** [comment]
> > for other users as well if `USE=wayland`
> 
> Is it needed to also check for >=wlroots-0.15.0 before applying this patch?

I think this patch is safe to apply even if using an older wlroots, but I haven't tested it.

**Comment by 0xC0ncord** [comment]
I reinstalled an older version of sway and can confirm that ungoogled-chromium seems to continue to be working fine. Specifically, these are the package versions I have:
```
=gui-libs/wlroots-0.14.1-r1::gentoo
=gui-wm/sway-1.6.1-r1::gentoo
```
So it seems that we can apply this patch for older wlroots as well, at least based on my testing (which includes posting this comment in this environment!).

**Comment by PF4Public** [comment]
Thank you very much for testing! It would be great if you could do the PR.
