### ISSUE TITLE
www-client/ungoogled-chromium-78.0.3904.97_p2: version bump

### ISSUE THREAD

**Issue by perfect7gentleman** [PF4Public/gentoo-overlay#13]
https://github.com/Eloston/ungoogled-chromium/releases/tag/78.0.3904.97-2

**Comment by PF4Public** [comment]
It is mere a revision bump, not even a version :)
Apart from that it has only one change. Namely, Eloston excluded perfetto patch: Eloston/ungoogled-chromium@569f7b3.

I don't see any reason for bumping this revision and making everyone rebuild chromium once again for no apparent gain at all.
