### ISSUE TITLE
www-client:ungoogled-chromium-98.0.4758.80-r1: chromium-wayland.... patch fails to apply 

### ISSUE THREAD

**Issue by crabbedhaloablution** [PF4Public/gentoo-overlay#131]
See log for details: [www-client:ungoogled-chromium-98.0.4758.80-r1:20220201-234844.log](https://github.com/PF4Public/gentoo-overlay/files/7982660/www-client.ungoogled-chromium-98.0.4758.80-r1.20220201-234844.log)

**Comment by PF4Public** [comment]
It is already known: https://github.com/PF4Public/gentoo-overlay/pull/130#issuecomment-1026090259
You may try fixing the patch yourself if you wish
