### ISSUE TITLE
www-client/ungoogled-chromium-98 needs additional settings for vaapi-decoding

### ISSUE THREAD

**Issue by dagraver** [PF4Public/gentoo-overlay#133]
As of version 98, vaapi is broken, it needs '--disable-features=UseChromeOSDirectVideoDecoder' in addition to '--enable-features=VaapiVideoDecoder', as found on https://bbs.archlinux.org/viewtopic.php?pid=2021090#p2021090

This fixes the the problem of non-accelerated video decoding for me. I'm not sure this will be required for future versions, though.

**Comment by PF4Public** [comment]
I can add this to the already present notice.

**Comment by PF4Public** [comment]
Thanks for letting me know

**Comment by dagraver** [comment]
That would be the best thing to do at the moment. Thanks!

**Comment by rzalamena** [comment]
I can confirm adding the flags works. Thanks @PF4Public for providing the ungoogled-chromium ebuild and in such good quality (I had very few compilation failures in a long time).

I'd like to contribute with some information regarding my use case: ungoogled-chromium 98 with nvidia decoding in Xorg.

1. First check: see if your card supports decoding (and what kind: h264, vp9 etc...):
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

> Some laptop eGPUs don't have it (in my case MX150), in that case use `libva-intel-driver` (for older iGPUs) or `libva-intel-media-driver` (for newer iGPUs).
> My desktop video card has it.

2. Next you need to compile ungoogled-chromium with VAAPI and VDPAU use flags.
3. Now you need nVidia specific va-api driver: `libva-vdpau-driver`. As of writing the Gentoo main repository `libva-vdpau-driver-0.7.4-r5` ebuild is not working with recent (ungoogled-)chromium version, so I wrote an ebuild and published here:

   https://github.com/rzalamena/gentoo-overlay/commits/master/x11-libs/libva-vdpau-driver

   (read commit messages for more information: it fixes h264 decoding, adds experimental VP9 if supported and fixes other code issues)

   It contains a bunch of patches I found in archlinux AUR and other places.

4. Check that `libva` is using your VDPAU (e.g. compat driver for using VDPAU through libva):

```sh
# Install libva utilities
emerge -1 libva-utils
# Now run vainfo
vainfo 
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib64/va/drivers/nvidia_drv_video.so # <--
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4 # <--
```

5. Double check your `/etc/chromium/default`. It must have the following items:

   ```
   # Unlock video decoding
   CHROMIUM_FLAGS="--enable-features=VaapiVideoDecoder" 
   # Unlock VAAPI decode chooser
   CHROMIUM_FLAGS="${CHROMIUM_FLAGS} --disable-features=UseChromeOSDirectVideoDecoder" 
   # Fixes a blank screen during video playback problem for me (nvidia only, my intel iGPU doesn't need it)
   CHROMIUM_FLAGS="${CHROMIUM_FLAGS} --use-gl=desktop"
   ```

6. Start chromium from command line to make sure it doesn't log any related warning
7. Check that everything is set as expected in `about:gpu` (e.g. video decoding is OK and no critical issues reported at the bottom of the page)
8. Go to youtube and look for a 4K video
9. In a different tab open `about:media-intervals`
    Click on the video player instance you are running and you should see in the logs:
    `00:00:00.876 | kVideoDecoderName | "VDAVideoDecoder"`

   > If the VDAVideoDecoder failed you'd see the following message:
   > `00:00:00.494 | info | "Failed to initialize VDAVideoDecoder"`
   > Something useful might be available at the terminal you launched (ungoogled)-chromium.
   >
   > It is also possible to see this information with the developer tools in the youtube page:
   > `CTRL + Shift + i` -> Open the three dots menu on the top right corner -> `More Tools` -> `Media` -> Select the video instance.
   > It should show: `Hardware decoder: true`.
