### ISSUE TITLE
dev-util/electron: how to run on Wayland?

### ISSUE THREAD

**Issue by darkbasic** [PF4Public/gentoo-overlay#135]
On Arch Linux you set `--enable-features=UseOzonePlatform --ozone-platform=wayland` in  `~/.config/electron-flags.conf` (https://wiki.archlinux.org/title/wayland#Electron) to run Electron on Wayland. How can I accomplish the same?

**Comment by PF4Public** [comment]
`electron-16` lacks Wayland support as I didn't bother copying it from chromium ebuild. Compare:
https://github.com/PF4Public/gentoo-overlay/blob/3442a4b146b067ee0ea09d7fab458ae10eb6eb11/dev-util/electron/electron-16.0.9.ebuild#L2118-L2122
https://github.com/PF4Public/gentoo-overlay/blob/3442a4b146b067ee0ea09d7fab458ae10eb6eb11/dev-util/electron/electron-17.0.1-r1.ebuild#L2073-L2086

It could be restored. Alternatively it may work in electron-17.

**Comment by joecool1029** [comment]
This can be closed, Wayland works in 17 and 18. 16 is no longer in this tree.

**Comment by darkbasic** [comment]
I'll close this. By the way `~/.config/electron-flags.conf` is Arch Linux specific, I wonder if it might be worth implementing in in Gentoo as well.

**Comment by PF4Public** [comment]
> By the way `~/.config/electron-flags.conf` is Arch Linux specific, I wonder if it might be worth implementing in in Gentoo as well.

Have you tried `/etc/chromium/default` to that effect?



> This can be closed, Wayland works in 17 and 18. 16 is no longer in this tree.

Good to know.

**Comment by darkbasic** [comment]
> Have you tried /etc/chromium/default to that effect? Hmm, will electron consult that file though…

It works for Chromium but not Electron if I recall correctly.
