### ISSUE TITLE
www-client/ungoogled-chromium: failing to build with pgo USE flag

### ISSUE THREAD

**Issue by kostadin04** [PF4Public/gentoo-overlay#145]
Hi, when I try to compile ungoogled-chromium with the PGO use flag, there are some errors such as Could not read profile and the build fails. I am using bootstrapped clang 14.0.1 compiled with thinlto

`emerge -pqv '=www-client/ungoogled-chromium-101.0.4951.41_p1::pf4public'`

www-client/ungoogled-chromium-101.0.4951.41_p1  USE="clang official optimize-thinlto pgo proprietary-codecs pulseaudio screencast system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libusb system-openh264 system-png system-re2 system-snappy thinlto vaapi wayland -cfi -convert-dict -cups -custom-cflags -debug -enable-driver -gtk4 -hangouts -headless -js-type-check -kerberos -optimize-webui -pic (-selinux) -suid -system-libvpx -system-openjpeg -vdpau -widevine" L10N="af am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW"
[build.log](https://github.com/PF4Public/gentoo-overlay/files/8561047/build.log)

[emerge --info.txt](https://github.com/PF4Public/gentoo-overlay/files/8561058/emerge.--info.txt)

**Comment by PF4Public** [comment]
You need clang-15

**Comment by Interpause** [comment]
The check for clang-15 seems to be missing in the latest ebuilds

**Comment by PF4Public** [comment]
Unfortunately I had to remove it in c9ccb0de4fd6db0fd89dfc5662cd8f39e2001949 because it was giving me annoying false-failures on repoman check since then:
https://github.com/PF4Public/gentoo-overlay/runs/6271497721?check_suite_focus=true

> RepoMan scours the neighborhood...
> Unable to unshare: EPERM (for FEATURES="network-sandbox")
> Unable to unshare: EPERM (for FEATURES="network-sandbox")
>   dependency.bad [fatal]        [14](https://github.com/PF4Public/gentoo-overlay/runs/6271497721?check_suite_focus=true#step:5:15)
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1)
> ['>=sys-devel/clang-[15](https://github.com/PF4Public/gentoo-overlay/runs/6271497721?check_suite_focus=true#step:5:16)', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/desktop)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/[17](https://github.com/PF4Public/gentoo-overlay/runs/6271497721?check_suite_focus=true#step:5:18).1/desktop/gnome)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/desktop/gnome/systemd)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/desktop/plasma)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/desktop/plasma/systemd)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/desktop/systemd)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/hardened)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/hardened/selinux)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/no-multilib)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/no-multilib/hardened)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/no-multilib/hardened/selinux)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/selinux)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>    www-client/ungoogled-chromium/ungoogled-chromium-101.0.4951.41_p1.ebuild: BDEPEND: amd64(default/linux/amd64/17.1/systemd)
> ['>=sys-devel/clang-15', '>=sys-devel/lld-15']
>   dependency.badindev           2

If anyone knows how to write the dependence on clang-15 in a way that does not disturb repoman check — I'm <s>all ears</s> waiting for a PR :)
