### ISSUE TITLE
media-libs/zint-2.11.0: FATAL: Unable to find CMakeLists.txt

### ISSUE THREAD

**Issue by jjakob** [PF4Public/gentoo-overlay#160]
I think the source directory has moved:

```
 * Unable to locate CMakeLists.txt under:
 * "/var/tmp/portage/media-libs/zint-2.11.0/work/CMakeLists.txt"
 * Consider not inheriting the cmake eclass.
 * ERROR: media-libs/zint-2.11.0::pf4public failed (prepare phase):
 *   FATAL: Unable to find CMakeLists.txt
```

It moved to `/var/tmp/portage/media-libs/zint-2.11.0/work/zint-2.11.0-src/CMakeLists.txt` so I think S needs to be set to that dir or it needs to be unpacked into workdir.

**Comment by PF4Public** [comment]
I see now, why they reuploaded it :)

**Comment by jjakob** [comment]
Thanks, it works now.
