### ISSUE TITLE
dev-util/electron:18: Hard depends on removed package media-libs/openjpeg version 2.4.* with USE="system-openjpeg"

### ISSUE THREAD

**Issue by Imred-Gemu** [PF4Public/gentoo-overlay#165]
Building dev-util/electron 18.* is no longer possible with USE="system-openjpeg" as the Gentoo repository has removed all ebuilds for media-libs/openjpeg below version 2.5.0-r2, while electron hard depends on versions within 2.4.* by using `openjpeg-2.4/openjpeg.h` in include statement(s). I've attached a build log with details and the error message. The error occurs quite far into the build process, as a result I had to truncate a significant portion of the otherwise uneventful compiler commands for the file to be small enough to upload. This ebuild is in a local repository as I have modified it to apply a patch which fixes USE="-proprietary-codecs", but is otherwise identical to the ebuild from this repository.
[build.log](https://github.com/PF4Public/gentoo-overlay/files/9388386/build.log)

**Comment by PF4Public** [comment]
This one is actually easy to fix :)
