### ISSUE TITLE
dev-util/electron:18: Flags set in build/args/all.gn conflict with flags set when using USE="-proprietary-codecs", causing the build to fail

### ISSUE THREAD

**Issue by Imred-Gemu** [PF4Public/gentoo-overlay#166]
While building electron 18.* with `USE="-proprietary-codecs"`, the `proprietary_codecs` and `ffmpeg_branding` flags are altered by the ebuild in `src_configure`. This conflicts with flags set in `${WORKDIR}/${P}/build/args/all.gn`, causing the build to almost immediately fail. Here are the build logs:
[build.log](https://github.com/PF4Public/gentoo-overlay/files/9388475/build.log)
I can get it working by applying the following patch if the `proprietary-codecs` use flag is not set:
[electron-18-proprietary-codecs-fix.patch](https://github.com/PF4Public/gentoo-overlay/files/9388485/electron-18-proprietary-codecs-fix.patch.txt)
I don't know if this is the best solution, and I haven't tested it or even if it's needed with electron 19 or 20.

**Comment by PF4Public** [comment]
Does it build with your patch applied? Does it run thereafter? Have you tested any electron application with it? Most interesting for me would've been `vscode` and `element-desktop` of-course.

**Comment by Imred-Gemu** [comment]
> Does it build with your patch applied? Does it run thereafter? Have you tested any electron application with it? Most interesting for me would've been `vscode` and `element-desktop` of-course.

Yes it builds with my patch conditionally applied based on the `proprietary-codecs` use flag. This patch must not be applied when this flag is on or it will break for the same reason. I use this condition in `src_prepare`:
```bash
if ! use proprietary-codecs; then
	pushd "${WORKDIR}/${P}" || die
	eapply "${FILESDIR}/electron-18-proprietary-codecs-fix.patch" || die
	popd > /dev/null || die
fi
```
I don't know if that's the proper way to control the root of the patch in ebuilds. After applying this patch, I have used the resulting build to build `vscode`. I haven't noticed any unusual behavior in `vscode` in the last few months, other than #155. I have not tested `element-desktop`, would you like me to? I currently have a build with this patch completed.

**Comment by PF4Public** [comment]
> I have not tested `element-desktop`, would you like me to?

Not really. Since you already have a functioning vscode, which is more complex by far.

I think removing those lines by sed in `build/args/all.gn` should allow us to control them and be more reliable in the long run. I'll take care of this a bit later.

**Comment by PF4Public** [comment]
@Imred-Gemu It would be great if you could attempt rebuilding electron again and confirm that #165 and #166 are fixed.

**Comment by Imred-Gemu** [comment]
@PF4Public Thank you for the fix, I built it last night from this repo (with none of my own patches) and built vscode with it this morning. Everything seems to be working fine.
