### ISSUE TITLE
net-im/element-desktop: Fails to compile on ppc64

### ISSUE THREAD

**Issue by TheCodex6824** [PF4Public/gentoo-overlay#170]
Trying to emerge element-desktop on ppc64 currently fails due to the builder-util component of electron-builder erroring out if the architecture is not in their hardcoded list (which currently seems to have only x86 and arm). This is probably because they seem to use app-builder-bin, which provides precompiled binaries.

USE flags: electron-20 build-online native-modules
<details><summary>Relevant error output:</summary>
<p>

```
  ⨯ Unsupported arch ppc64  failedTask=build stackTrace=Error: Unsupported arch ppc64
    at Object.archFromString (/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/electron-builder/node_modules/builder-util/src/arch.ts:48:13)
    at commonArch (/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/electron-builder/src/builder.ts:52:62)
    at processTargets (/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/electron-builder/src/builder.ts:63:26)
    at normalizeOptions (/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/electron-builder/src/builder.ts:94:5)
    at build (/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/electron-builder/src/builder.ts:211:24)
    at /var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/electron-builder/src/cli/cli.ts:52:19
```
</p>
</details>

I tried patching things for a few hours to get it to not depend on precompiled binaries, but I never used node/yarn before and it seems to really not like me trying to edit things in node_modules, because it keeps overwriting my changes.

**Comment by PF4Public** [comment]
Well, that's unfortunate. I was hoping that it would "just work" after ppc64 arch was added. Turns out, it doesn't.

You should not be removing `electron-builder` as it is used during the build: https://github.com/PF4Public/gentoo-overlay/blob/c65ec5160be0640656a0b619df4a738db0343a88/net-im/element-desktop/element-desktop-9999.ebuild#L127

Theoretically it would be possible to get rid of `electron-builder` altogether, but that means that one should implement what it does. I doubt I have enough time and motivation to do so, sorry.

There is another possibility: another codepath specifically for `ppc64` platform. Everything needed to run element-desktop should be prepared before the `electron-builder` invocation. Thus it could suffice to just use the whole results folder instead of calling `electron-builder`. This could potentially produce heavier package with lots of junk, but still should be a working solution. I don't have any `ppc64` hardware at my disposal, so I can only direct you in this if you are willing to investigate yourself.

**Comment by TheCodex6824** [comment]
> You should not be removing electron-builder as it is used during the build: 

I wasn't trying to remove it, I was trying to mess with it's dependencies to use app-builder instead of app-builder-bin (probably should have been more clear about that). I think I made a big mistake though: apparently, app-builder has nothing to do with app-builder-bin, despite the naming.

Given that, I think it would probably be best to go with one of your suggestions. If the files really are already there and just need to be packed up, I might try to see what electron-builder does and try to minimally replicate that.

One other thing I didn't mention: I had to change the version of the Raptor ppc64 patches used when emerging electron because the chromium 104 based patches seem to be gone. It compiled fine with the 105 patches, but I have no idea if the built electron actually works, so I can't say if that is a real fix yet.

**Comment by PF4Public** [comment]
Why didn't you build electron-20 to begin with? Unlike `vscode`, `electron-desktop` works fine with electron-20.

It is trivial to test whether electron works or not. Just call it: `electron -v` should print its version in terminal and `electron` should show an electron default application with some information in it.

Let me know if you need any help. I would've started with cloning element-desktop repository locally and trying building it locally and then trying to run it as an electron application to see if a viable solution could be built without electron-builder.

**Comment by TheCodex6824** [comment]
> Why didn't you build electron-20 to begin with?

I did use electron 20 (should have put use flags in the initial report, sorry about that) but that version of electron still only wants chromium 104. The Raptor patches are absolutely required for ppc64 since upstream refuses to merge them for some reason, and [the only somewhat modern versions of chromium they have patches for are 98 and 105](https://ppa.quickbuild.io/raptor-engineering-public/chromium/ubuntu/pool/main/c/chromium/). The 105 patches seem to work on 104, though. 

I tested the electron build and it works fine, so I can PR the patch version change if you're ok with the version mismatch.

I'm currently re-emerging electron with `dev-dependencies` while also working on a local copy of element-desktop.

**Comment by PF4Public** [comment]
> I did use electron 20 (should have put use flags in the initial report, sorry about that) but that version of electron still only wants chromium 104. The Raptor patches are absolutely required for ppc64 since upstream refuses to merge them for some reason, and [the only somewhat modern versions of chromium they have patches for are 98 and 105](https://ppa.quickbuild.io/raptor-engineering-public/chromium/ubuntu/pool/main/c/chromium/). The 105 patches seem to work on 104, though.
> 
> I tested the electron build and it works fine, so I can PR the patch version change if you're ok with the version mismatch.

I'd like to hear from @darkbasic about that first.

**Comment by darkbasic** [comment]
It looks like Timothy deletes the older patchsets, probably because it makes no sense to use old version of Chromium. Yet it makes a lot of sense to keep them around because of electron.
105 and 104 patchsets are very similar and they both should apply (but this is an exception, usually they don't), in fact I've tried 104 patches on top of 105 (but not the other way round).
I don't suggest to use the 105 patchset on electron 20 because I didn't test it (I didn't test electron 20 a lot to be honest because  vscode didn't work with it yet).
The best course of action would be to ask Timothy to keep packages around for a little longer because of electron, but worse case scenario I can simply ship the tarballs along with the other files.

In the meantime, here it is: 
[chromium_104.0.5112.101-1raptor0_deb11u1.debian.tar.xz.zip](https://github.com/PF4Public/gentoo-overlay/files/9574232/chromium_104.0.5112.101-1raptor0_deb11u1.debian.tar.xz.zip)

(drop the .zip extension because it's not a zip file, I had to rename it because of github)

**Comment by darkbasic** [comment]
102 patchset for electron 19:

[chromium_102.0.5005.61-1raptor0~deb11u1.debian.tar.xz.zip](https://github.com/PF4Public/gentoo-overlay/files/9574280/chromium_102.0.5005.61-1raptor0.deb11u1.debian.tar.xz.zip)

(drop .zip)

**Comment by TheCodex6824** [comment]
I managed to get Element working - you were right, it was just mostly moving files around and making `app.asar`. Changes are [here](https://github.com/TheCodex6824/PF4Public-gentoo-overlay/blob/fix/element-desktop-ppc64/net-im/element-desktop/element-desktop-1.11.5.ebuild#L1154), but I still need to test all the USE configurations to make sure nothing breaks (and the change is the same for all versions). I did keep all of the changes to just ppc64 though, so even if this stops working someday every other arch should still be fine.

> The best course of action would be to ask Timothy to keep packages around for a little longer because of electron

If you'd like, I can ask about that (and maybe ask about the state of electron in general) on the RCS forums. If you have a more direct line of contact, that might get faster results, though.

**Comment by TheCodex6824** [comment]
> Why are you repeating yarn install?

That seemed to be the most straightforward way to get only production dependencies (`--production`) into the `node_modules` folder for the final archive. The normal install for building includes dev dependencies, which in total is over 600 MB of stuff. I originally just tried parsing the dependency list and copying over the production dependencies, but not all modules needed are hoisted to the top level `node_modules` by yarn, so that would at least require recursively searching every dependency for nested modules (and even then, I'm not sure if there would be symlinks or such that would get broken by copying things).

> Also I've had a suspicion that the first yarn install could fail. Does it not?

The install doesn't fail, as the original error only appears when a script in `build-util` gets ran as part of `electron-builder`. That's a good point though - it isn't a dependency on ppc64 anymore, although it might require patching `package.json` so yarn doesn't complain about a missing dependency. It doesn't get installed in the final package so I just kept it in for now.

**Comment by PF4Public** [comment]
> That seemed to be the most straightforward way to get only production dependencies (`--production`) into the `node_modules` folder for the final archive.

You may replicate the logic behind `${ONLINE_OFFLINE}` and apply it to `--production` flag.

**Comment by TheCodex6824** [comment]
> You may replicate the logic behind ${ONLINE_OFFLINE} and apply it to --production flag.

I think it needs all the dependencies at build time though, as typescript (`tsc`) needs them to compile everything. I tried it to see what happens, and typescript fails to find electron (which is only a dev dependency). To even get to that point, I also had to add `dev-lang/typescript` as a dependency and patch the `tsconfig.json` file to stop trying to load test files (it was requiring `jest`).

I feel like there has to be a better way than running the install command again just to get the production dependencies, but I don't know what it is (if it exists).

**Comment by PF4Public** [comment]
@TheCodex6824 I can feel that pain.

If you cannot find any better way, but your testing shows that it still builds a working Element, feel free to open a PR.

**Comment by darkbasic** [comment]
> If you'd like, I can ask about that (and maybe ask about the state of electron in general) on the RCS forums. If you have a more direct line of contact, that might get faster results, though.

I've already asked and we managed to find a solution: https://github.com/PF4Public/gentoo-overlay/pull/172
