### ISSUE TITLE
www-client/ungoogled-chromium-bin:  Missing dependency on libaom.so.3?

### ISSUE THREAD

**Issue by dcrook** [PF4Public/gentoo-overlay#183]
Hi, thanks for maintaining this package.    I ran an emerge on ungoogled-chromium-bin and there was a QA message in the installation section:

 * QA Notice: Unresolved soname dependencies:
 * 
 * 	/opt/chromium-browser/chrome: libaom.so.3

When I try to run chromium in the command line I see a similar error.  

dcrook@godzilla ~ $ chromium
chromium-browser: error while loading shared libraries: libaom.so.3: cannot open shared object file: No such file or directory

If I install media-libs/libaom then chromium starts up normally.  I did a oneshot emerge on media-libs/libaom and libaom-3.4.0 was installed.

**Comment by Siinamon** [comment]
I can confirm that this happened on my machine as well.

**Comment by PF4Public** [comment]
Riiiight… I was trying to remember to add these newly introduced dependencies into -bin. I remembered… remembered…remembered… and completely forgot about it :) At least something is stable in this universe: me breaking things.
