### ISSUE TITLE
www-client/ungoogled-chromium-108.0.5359.48_p1: posix_spawn: No such file or directory (2)

### ISSUE THREAD

**Issue by imrebuild** [PF4Public/gentoo-overlay#186]
From https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1993581, the issue seems to be that chrome_crashpad_handler is not included in the final result.

It's fixed by https://git.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source/commit/?h=beta&id=7df4229e93981f5fa475c8fd98b68b74721a8588.

### Solution
Uncomment this
https://github.com/PF4Public/gentoo-overlay/blob/708ea01e2651ce3efe9cbeca3e3b25f788e480e2/www-client/ungoogled-chromium/ungoogled-chromium-108.0.5359.48_p1.ebuild#L1280

**Comment by PF4Public** [comment]
See the discussion upstream: https://github.com/ungoogled-software/ungoogled-chromium/pull/2148#issuecomment-1326492305
