### ISSUE TITLE
www-client/ungoogled-chromium: libva moved from x11-libs to media-libs

### ISSUE THREAD

**Issue by SpaceBudokan** [PF4Public/gentoo-overlay#187]
Ungoogled Chromium is still looking for libva in x11-libs, but it has been moved to media-libs.

**Comment by PF4Public** [comment]
Please provide some more information. I fail to see where the issue could be.

**Comment by SpaceBudokan** [comment]
It seems I have an update issue, not an actual issue with the ebuild. Sorry for the inconvenience.
