### ISSUE TITLE
app-misc/font-manager-0.8.8: won't build; complains about libnautilus-extension

### ISSUE THREAD

**Issue by jayofdoom** [PF4Public/gentoo-overlay#188]
After the gnome43 unmasking, I can't build font-manager with my existing use flags. All the info is in https://bugs.gentoo.org/883597, which I filed before I realized this was an overlay package.

Setting `-nautilus` permits it to build successfully.

**Comment by PF4Public** [comment]
Could you please file this issue to font-manager itself? I think, it might have something to do with https://github.com/FontManager/font-manager/issues/286

**Comment by JerryCasiano** [comment]
I actually just pushed a commit which allows the extension to build against both 3 & 4.

If you need me to tag a new release to resolve this issue just let me know. ;-)

**Comment by PF4Public** [comment]
@jayofdoom Please try building 9999 version and let us know if it's OK.

**Comment by jayofdoom** [comment]
I just reinstalled the 0.8.8 version; it's working now. I also tested -9999 for good measure; it works as well.
