### ISSUE TITLE
www-client/ungoogled-chromium-bin: icu versions conflicts

### ISSUE THREAD

**Issue by Katarn** [PF4Public/gentoo-overlay#189]
Icu 72.1 was stabilized: https://packages.gentoo.org/packages/dev-libs/icu.

I updated the system and all applications dependent on this library, but ungoogled-chromium-bin requires an earlier version and there is a conflict.

**Comment by PF4Public** [comment]
Soooo, what is the issue exactly?

**Comment by Katarn** [comment]
In the ungoogled-chromium-bin build container, update icu to version 72.1 to keep it in sync with the latest version in Gentoo Portage.

**Comment by PF4Public** [comment]
> In the ungoogled-chromium-bin build container, update icu to version 72.1 to keep it in sync with the latest version in Gentoo Portage.

It won't magically make existing binaries work with 72 icu, will it?

**Comment by Katarn** [comment]
> It won't magically make existing binaries work with 72 icu, will it?

Of course, therefore, they will need to be rebuild. At least starting with today's Chromium 108. Because 72.1 was already stabilized a week ago.

**Comment by PF4Public** [comment]
So to clear this, you _do_ realize I have no obligations to do anything and I'm doing it out of my own good will, right? You had the opportunity to build yourself, which you choose not to employ.

> UPD: I see that 108 is not yet in the overlay - apparently, nothing will have to be rebuild.

What is [this](https://github.com/PF4Public/gentoo-overlay/tree/master/www-client/ungoogled-chromium) then?

**Comment by Katarn** [comment]
> So to clear this, you do _realize_ I have no obligations to do anything and I'm doing it out of my own good will, right?

Yes, I have no questions for you. I also volunteer to report a bug that you may not know exists.

> What is [this](https://github.com/PF4Public/gentoo-overlay/tree/master/www-client/ungoogled-chromium) then?

This is not the "-bin" version.

**Comment by PF4Public** [comment]
> I also volunteer to report a bug that you may not know exists.

Unfortunately I just didn't have time to tackle it. This has to wait a couple of days more.

**Comment by PF4Public** [comment]
Just a heads up. [First is ready to go](https://github.com/PF4Public/ungoogled-chromium-bin/releases/tag/108.0.5359.94), others are coming … veeeery soon. There are lots of cache misses while building.

**Comment by PF4Public** [comment]
I'm reopening this since the hardware I used for building ungoogled-chromium-bin failed today horribly. No idea when it'll be up and running again. I'll keep everyone posted here.

**Comment by PF4Public** [comment]
Problem solved, new binaries have been published.

**Comment by zz64** [comment]
Not solved for me.
when i try installing libreoffice binary from gentoo repository, i get conflict:

![alt conflict](http://152.228.173.205/files/20221209_19-52-56.jpg)

**Comment by zz64** [comment]
sorry, i think to be fixed with latest: www-client/ungoogled-chromium-bin-108.0.5359.98::pf4public
using dev-libs/icu-72.1:0/72.1::gentoo
Thanks for good work :)
