### ISSUE TITLE
category/package: something is broken net-im/electron-desktop MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by FellFromTheSky** [PF4Public/gentoo-overlay#191]
I was trying to install the latest version of net-im/electron-desktop and this happened :
https://gist.github.com/FellFromTheSky/3982ade8642917c43f8def7f95b63401

It seems to me the package doesn't install all required dependencies.
Are you able to fix it or should I report this to upstream?

**Comment by PF4Public** [comment]
Have you tried building non-live version?

**Comment by FellFromTheSky** [comment]
No, since I'm also using the live element-web.
I'm currently kinda busy with school so I'll do the test later.
Then I didn't have an issue with the live Element Desktop package during the last few months, unlike for other live packages like Yuzu  (guru overlay) and CodeBlocks (gentoo overlay).

**Comment by PF4Public** [comment]
Live ebuilds are inherently unstable no matter what. You should've tested non-live one to begin with. Let me know, if non-live also does not function.
