### ISSUE TITLE
www-client/ungoogled-chromium-bin: missing widevine support

### ISSUE THREAD

**Issue by gringus** [PF4Public/gentoo-overlay#193]
On self built `www-client/ungoogled-chromium` package to be able to play some web videos (eg. [Workplace](https://www.workplace.com/)) I need to enable `widevine` USE flag and get `www-plugins/chrome-binary-plugins` installed. This does not seem to be the case for `www-client/ungoogled-chromium-bin` as installing `www-plugins/chrome-binary-plugins` is not sufficient. I suspect `widevine` USE flag is not enabled in the build process. If this is the the case I would like to ask to enable it, so pre-build ungoogled chromium binaries would cover more use cases and make more users happy.

**Comment by PF4Public** [comment]
That is correct, `www-client/ungoogled-chromium-bin` is built without widevine. 

🤷Theoretically I could build `amd64` and `x86` variants with widevine support, but not `core2` and `haswell` because those are the binaries I use myself.

**Comment by gringus** [comment]
I think building in `widevine` support by default should not have any negative impact(?) if you don't use it as it still requires `chrome-binary-plugins` to work properly.

**Comment by PF4Public** [comment]
I have enabled widevine on my build system and added the corresponding code into ebuild. It is a dummy USE flag actually :)

widevine should be available starting with the next release. Let me know if it does not function.

**Comment by gringus** [comment]
Thank. Will report back.

**Comment by gringus** [comment]
It looks like we are still missing a symlink in the build (finally I found some time to figure out why this still did not work). Please see https://github.com/gentoo/gentoo/blob/master/www-client/chromium-bin/chromium-bin-110.0.5481.30.ebuild#L196 for an example. In my mind it also makes sense to pull `chrome-binary-plugins` automatically when `widevine` `USE` flag is set (unless we have a reason not to do so).

**Comment by PF4Public** [comment]
Funny how I forgot to include a link in -bin, but have it in non-bin :D
See here: https://github.com/PF4Public/gentoo-overlay/blob/394fadba6960c58ed41e54ed9874bd408f095f8e/www-client/ungoogled-chromium/ungoogled-chromium-114.0.5735.106_p1.ebuild#L1454

If you know the correct path, feel free to submit a PR for both: -bin and non-bin

**Comment by gringus** [comment]
Created #236 for bin only (tested). Interestingly `chromium` ebuild does not create any symlinks, but currently I have no resources to test if dropping creation of them in `ungoogled-chromium` would still work fine.
