### ISSUE TITLE
Install electron on Gentoo ppc64le category/package: something is broken

### ISSUE THREAD

**Issue by sumitd2** [PF4Public/gentoo-overlay#196]
Hi team, 

We are trying to install electron in a gentoo/stage3 ppc64le docker container (`layman -a pf4public && emerge electron`). The installation doesn't go through and reports errors one after the other, similar to the following:

```
!!! All ebuilds that could satisfy "electron" have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-util/electron-22.0.0::pf4public (masked by: ~ppc64 keyword)
- dev-util/electron-21.3.3::pf4public (masked by: ~ppc64 keyword)
- dev-util/electron-21.3.1::pf4public (masked by: ~ppc64 keyword)
- dev-util/electron-20.3.8::pf4public (masked by: ~ppc64 keyword)
- dev-util/electron-20.3.7::pf4public (masked by: ~ppc64 keyword)
- dev-util/electron-19.1.9::pf4public (masked by: ~ppc64 keyword)
- dev-util/electron-19.1.8::pf4public (masked by: ~ppc64 keyword)
-----------------
!!! All ebuilds that could satisfy "sys-apps/yarn" have been masked.
!!! One of the following masked packages is required to complete your request:
- sys-apps/yarn-1.22.19::gentoo (masked by: missing keyword)
- sys-apps/yarn-1.22.17::gentoo (masked by: missing keyword)

```

Are we missing a step or something else?

P.S.: I am very new to Gentoo.

**Comment by PF4Public** [comment]
Please make sure to study [Gentoo Handbook's portage section](https://wiki.gentoo.org/wiki/Handbook:PPC64/Working/Portage).  

Also useful might be [Knowledge Base:Accepting a keyword for a single package](https://wiki.gentoo.org/wiki/Knowledge_Base:Accepting_a_keyword_for_a_single_package).
