### ISSUE TITLE
app-editors/vscode-1.75.1:The terminal process failed to launch: A native exception occurred during launch (posix_spawn failed: Permission denied).

### ISSUE THREAD

**Issue by darkbasic** [PF4Public/gentoo-overlay#205]
See https://bugs.gentoo.org/893208

`chmod +x /usr/lib64/vscode/node_modules.asar.unpacked/node-pty/build/Release/spawn-helper` did the trick for me

**Comment by PF4Public** [comment]
I suppose https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4da5959f47930c3ba2ec9e89972ca046cc6aaa38 should fix it also for us?

**Comment by darkbasic** [comment]
Yes I think so.

**Comment by PF4Public** [comment]
OK, I'll add the fix after your PR is merged to avoid merge-conflicts.
