### ISSUE TITLE
dev-util/electron-23.1.1-r1: /usr/bin/bash not found

### ISSUE THREAD

**Issue by SpookySkeletons** [PF4Public/gentoo-overlay#206]
The fully built chromium engine is attempting to run /usr/bin/bash which does not exist.

Mega weird. If this is just my system close the issue and I'll investigate the disk/ filesystem health and reemerge bash.

**Comment by PF4Public** [comment]
@darkbasic Could recent changes do this?

**Comment by darkbasic** [comment]
Oh definitely, I've used bash to run the script but I didn't think that not everybody might have it: https://github.com/PF4Public/gentoo-overlay/blob/master/dev-util/electron/files/electron-launcher.sh#L1

Changing `bash` to `sh` would do the trick.
@SpookySkeletons you can do the same in `/usr/bin/electron-23` if you don't want to recompile it.

**Comment by PF4Public** [comment]
`sh` might not support `[[ ]]`. This is the true issue and should be solved somehow. 

- Could the launcher be written so, that it would be executable by `sh`?
- Maybe adding `#!/bin/bash` and requiring bash in deps could solve this issue?

**Comment by PF4Public** [comment]
@SpookySkeletons Have you tried changing interpreter path in the script?

**Comment by SpookySkeletons** [comment]
I made a simple symlink from where it's looking to bash instead and it works fine. Does your system come with /usr/bin/bash?

**Comment by PF4Public** [comment]
@SpookySkeletons Do you have `/bin/bash`?

**Comment by SpookySkeletons** [comment]
Yep just nothing in `/usr/bin/bash` by default.

I think patching the launch script to `/bin/bash` should be harmless.

**Comment by darkbasic** [comment]
I'm sorry, but I don't understand what you are talking about: as you can [see](https://github.com/PF4Public/gentoo-overlay/blob/master/dev-util/electron/files/electron-launcher.sh#L1) the script already uses bash.
Can you please post the output of the following:
```
ls -al /usr/bin/bash
```

**Comment by PF4Public** [comment]
Actually, I don't have it either:
```
# equery f bash
 * Searching for bash ...
 * Contents of app-shells/bash-5.1_p16-r2:
/bin
/bin/bash
/bin/rbash -> bash
/etc
/etc/bash
/etc/bash/bash_logout
/etc/bash/bashrc
/etc/bash/bashrc.d
/etc/bash/bashrc.d/.keep_app-shells_bash-0
/etc/skel
/etc/skel/.bash_logout
/etc/skel/.bash_profile
/etc/skel/.bashrc
/usr
/usr/bin
/usr/bin/bashbug

```

**Comment by darkbasic** [comment]
Oh sorry, now I understand: you do have `/bin/bash` but not `/usr/bin/bash`.
Which is super weird because I have both but equery only lists the first:
```
niko@talos2 ~ $ equery f bash
 * Searching for bash ...
 * Contents of app-shells/bash-5.1_p16-r2:
/bin
/bin/bash

niko@talos2 ~ $ equery f bash | grep "usr/bin/bash"
/usr/bin/bashbug

niko@talos2 ~ $ ls -al /usr/bin/bash
-rwxr-xr-x 1 root root 1195896 Nov 12 02:02 /usr/bin/bash

niko@talos2 ~ $ ls -al /bin/bash
-rwxr-xr-x 1 root root 1195896 Nov 12 02:02 /bin/bash

niko@talos2 ~ $ md5sum /usr/bin/bash
0724b15a07e2bd927c8f4dbc1c6da714  /usr/bin/bash

niko@talos2 ~ $ md5sum /bin/bash
0724b15a07e2bd927c8f4dbc1c6da714  /bin/bash
```

**Comment by PF4Public** [comment]
```sh
# ls -al /usr/bin/bash
ls: Zugriff auf '/usr/bin/bash' nicht möglich: Datei oder Verzeichnis nicht gefunden
```

So I guess, `#!/bin/bash` should be good enough?

**Comment by darkbasic** [comment]
Oh I think I know why I have it and you don't: https://www.gentoo.org/support/news-items/2022-12-01-systemd-usrmerge.html
I think merged-usr should be the default with the upcoming profile 23.

I was thinking about using `#!/usr/bin/env sh` instead. We don't enforce a dependency on bash so `#!/bin/bash` would fail anyway on the systems without it, but `#!/usr/bin/env sh` would allow more shells to work without having to rely on bash.
`#!/usr/bin/env sh` is already being used by code-oss so it should be available on every system, but please double check on your system before I send a PR.

**Comment by PF4Public** [comment]
> `#!/usr/bin/env sh` is already being used by code-oss so it should be available on every system, but please double check on your system before I send a PR.

```sh
# ls -al /usr/bin/env
lrwxrwxrwx 1 root root 13 22. Jan 05:18 /usr/bin/env -> ../../bin/env


```

Or do you mean to check if `sh` is capable of executing that script?

**Comment by darkbasic** [comment]
> Or do you mean to check if sh is capable of executing that script?

That would depend on which system shell you have installed. 99% of the times people chose something as capable of bash, so I wouldn't be too worried about that. I'll open a PR to use `#!/usr/bin/env sh` then.

> on't use systemd btw. It was the cornerstone for me to migrate to Gentoo to begin with ;)

That's the beauty of Gentoo: you can choose to use whatever you want :)
