### ISSUE TITLE
x11-misc/caffeine-ng: dev-python/setuptools_scm moved to dev-python/setuptools-scm in 1Q-2023 portage

### ISSUE THREAD

**Issue by gdegough** [PF4Public/gentoo-overlay#207]
1Q-2023 gentoo repository dev-python/setuptools_scm was renamed to dev-python/setuptools-scm, breaking x11-misc/caffeine-ng builds

all ebuilds for x11-misc/caffeine-ng need DEPEND modified to use  dev-python/setuptools-scm as a dependency

**Comment by PF4Public** [comment]
What a coincidence! It was just yesterday that I was wondering if I should remove caffeine-ng from my machines and also from overlay as its usage brings me more trouble than it solves. I also had no idea whether anyone uses it :)

I can keep it in overlay if someone finds it useful :)

**Comment by gdegough** [comment]
I find it very useful. It works for my use cases, but I'm only one user. 
I created a localrepo and made the change to the ebuild and it builds without error and works great, but thought you might want to know.

**Comment by PF4Public** [comment]
> thought you might want to know.

Of course! I'll deal with it a bit later.

> your work was valuable to me. :)

Great to hear.

**Comment by gdegough** [comment]
Thanks for the quick fix!
