### ISSUE TITLE
www-client/ungoogled-chromium-111.0.5563.64_p1 breaks with unresolved dependency

### ISSUE THREAD

**Issue by logrusx** [PF4Public/gentoo-overlay#211]
`[ebuild     U  ] www-client/ungoogled-chromium-111.0.5563.64_p1::pf4public [110.0.5481.177_p1::pf4public] USE="X clang convert-dict cups gtk4 hangouts js-type-check official optimize-webui proprietary-codecs pulseaudio screencast system-av1 system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libusb system-openh264 system-png system-re2 system-snappy vaapi wayland -cfi -custom-cflags -debug -enable-driver -headless -hevc -kerberos -optimize-thinlto -pgo -pic -qt5 (-selinux) -suid -system-libvpx -system-openjpeg -thinlto -widevine" L10N="bg -af -am -ar -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -ur -vi -zh-CN -zh-TW" `

`* Configuring Chromium...
gn gen --args= is_clang=true clang_use_chrome_plugins=false use_lld=false custom_toolchain="//build/toolchain/linux/unbundle:default" host_toolchain="//build/toolchain/linux/unbundle:default" is_debug=false dcheck_always_on=false dcheck_is_configurable=false enable_nacl=false use_system_libpng=true use_system_harfbuzz=true use_gnome_keyring=false enable_js_type_check=true enable_hangout_services_extension=true enable_widevine=false use_cups=true use_kerberos=false use_pulseaudio=true use_vaapi=true rtc_use_pipewire=true gtk_version=4 disable_fieldtrial_testing_config=true is_cfi=false chrome_pgo_phase=0 optimize_webui=true use_system_freetype=true use_system_libopenjpeg2=false enable_pdf=true use_system_lcms2=true enable_print_preview=true enable_platform_hevc=false enable_hevc_parser_and_hw_decoder=false enable_mdns=false enable_mse_mpeg2ts_stream_parser=true enable_reading_list=false enable_remoting=false enable_reporting=false enable_service_discovery=false exclude_unwind_tables=true use_official_google_api_keys=false google_api_key="" google_default_client_id="" google_default_client_secret="" safe_browsing_mode=0 use_unofficial_version_number=false blink_symbol_level=0 symbol_level=0 enable_iterator_debugging=false enable_swiftshader=false build_with_tflite_lib=false perfetto_use_system_zlib=true use_system_zlib=true use_system_libjpeg=true rtc_build_examples=false use_gold=false use_sysroot=false use_custom_libcxx=false enable_pseudolocales=false blink_enable_generated_code_formatting=false proprietary_codecs=true ffmpeg_branding="Chrome" target_cpu="x64" treat_warnings_as_errors=false fatal_linker_warnings=false v8_use_libm_trig_functions=true icu_use_data_file=false use_ozone=true ozone_auto_platforms=false ozone_platform_headless=true use_system_libdrm=true use_system_minigbm=true use_xkbcommon=true use_qt=false ozone_platform_x11=true ozone_platform_wayland=true ozone_platform="wayland" use_system_libffi=true is_official_build=true use_thin_lto=false thin_lto_enable_optimizations=false symbol_level=0  out/Release
ERROR Unresolved dependencies.
//mojo/public/js/test:compile_test(//build/toolchain/linux/unbundle:default)
  needs //mojo/public/js/test:test_mojom_js_library_for_compile(//build/toolchain/linux/unbundle:default)
`

**Comment by PF4Public** [comment]
You need to disable `js-type-check`. Apparently they broke something there. I'm not inclined in fixing this, but if someone makes it work, PR is welcome.

**Comment by fordfrog** [comment]
i can see that on gentoo `js-type-check` has been dropped from `www-client/chromium-111.0.5563.64`. the commit log does not mention the reason though.

**Comment by fordfrog** [comment]
i just asked sultan at gentoo chromium irc channel and it was dropped for good so you can drop it too: https://bugs.chromium.org/p/chromium/issues/detail?id=1410874
