### ISSUE TITLE
<www-client/chromium-79.0.3945.117: multiple vulnerabilities

### ISSUE THREAD

**Issue by crabbedhaloablution** [PF4Public/gentoo-overlay#22]
https://bugs.gentoo.org/704960
Time to bump :-)

**Comment by crabbedhaloablution** [comment]
Ps. my overnight compile of 79.0.3945.117_p1, which was a simply cp a to b, compiled without problems.

**Comment by PF4Public** [comment]
>Time to bump :-)

Yep
