### ISSUE TITLE
www-client/ungoogled-chromium: on gentoo chromium is now built in one run

### ISSUE THREAD

**Issue by fordfrog** [PF4Public/gentoo-overlay#221]
it's not really a feature request but rather a note as i have no idea whether it is important or not.

on gentoo, chromium is built already for several major versions just in one run (so there are around 50k files compiled instead of twice around 20k files - the numbers are very rough). i don't know the reasons behind this, whether there are some benefits or not. so i just wanted to point this out so that we could get the benefits too, if there are any.

**Comment by PF4Public** [comment]
That is needed for hardened kernel and it is an easy fix.
