### ISSUE TITLE
dev-util/electron-23.3.1: abseil-cpp breakage (llvm/clang-16 issue?)

### ISSUE THREAD

**Issue by joecool1029** [PF4Public/gentoo-overlay#224]
Haven't been able to use electron for months, but I could build it before. Past few weeks that stopped being the case, build failure below, there's some more to it but it's all the same type failure error: 

dev-util/electron-23.3.1:23/3.1::pf4public  USE="X clang cups proprietary-codecs screencast system-av1 system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libusb system-openh264 system-png system-re2 system-snappy vaapi wayland -custom-cflags -debug -dev-dependencies -gtk4 -hangouts -hevc -js-type-check -kerberos -optimize-thinlto -optimize-webui -pgo -pic -pulseaudio (-selinux) -suid -system-libvpx -system-openjpeg -thinlto -ungoogled -vdpau" L10N="-af -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -ur -vi -zh-CN -zh-TW" 0 KiB

`FAILED: obj/third_party/abseil-cpp/absl/strings/strings/damerau_levenshtein_distance.o
x86_64-pc-linux-gnu-clang++ -MMD -MF obj/third_party/abseil-cpp/absl/strings/strings/damerau_lev
enshtein_distance.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D_FIL
E_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DND
EBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DABSL_ALLOCATOR_NOTHROW=1 -I../.. -Igen -I../.
./third_party/abseil-cpp -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param
=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -p
thread -fcolor-diagnostics -fmerge-all-constants -no-canonical-prefixes -ftrivial-auto-var-init=
pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointe
r -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -W
all -Wno-unused-variable -Wno-c++11-narrowing -Wno-unused-but-set-variable -Wno-misleading-inden
tation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unn
eeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecat
ed-builtins -Wno-bitfield-constant-conversion -Wshorten-64-to-32 -Wimplicit-int-conversion -Wsig
n-compare -Wsign-conversion -Wtautological-unsigned-zero-compare -std=c++20 -Wno-trigraphs -gsim
ple-template-names -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wbool-conversion -Wcon
stant-conversion -Wenum-conversion -Wint-conversion -Wliteral-conversion -Wnon-literal-null-conv
ersion -Wnull-conversion -Wobjc-literal-conversion -Wstring-conversion -Wbitfield-enum-conversio
n  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -pipe -march=native -Wno-unknown-warning-option -Wno
-builtin-macro-redefined -c ../../third_party/abseil-cpp/absl/strings/internal/damerau_levenshte
in_distance.cc -o obj/third_party/abseil-cpp/absl/strings/strings/damerau_levenshtein_distance.o
In file included from ../../third_party/abseil-cpp/absl/strings/internal/damerau_levenshtein_dis
tance.cc:15: 
../../third_party/abseil-cpp/absl/strings/internal/damerau_levenshtein_distance.h:28:1: error: u
nknown type name 'uint8_t'
uint8_t CappedDamerauLevenshteinDistance(absl::string_view s1,
^
../../third_party/abseil-cpp/absl/strings/internal/damerau_levenshtein_distance.h:29:64: error: 
unknown type name 'uint8_t'
                                         absl::string_view s2, uint8_t cutoff);
                                                               ^
../../third_party/abseil-cpp/absl/strings/internal/damerau_levenshtein_distance.cc:34:1: error: 
unknown type name 'uint8_t'
uint8_t CappedDamerauLevenshteinDistance(absl::string_view s1,
^
../../third_party/abseil-cpp/absl/strings/internal/damerau_levenshtein_distance.cc:35:64: error:
 unknown type name 'uint8_t'
                                         absl::string_view s2, uint8_t cutoff) {
                                                               ^
../../third_party/abseil-cpp/absl/strings/internal/damerau_levenshtein_distance.cc:36:9: error: 
unknown type name 'uint8_t'
  const uint8_t MAX_SIZE = 100;
`

**Comment by joecool1029** [comment]
clang-16.0.3 currently, also failed with 16.0.2.
gcc-13.1.0-r1

**Comment by PF4Public** [comment]
> gcc-13.1.0-r1

This is your issue.

**Comment by PF4Public** [comment]
> but didn't think it would happen with clang

It is still using libstdc++ from gcc though, unless you build with libcxx.

**Comment by joecool1029** [comment]
Understood. Just didn't consider it previously. Thanks for pointing it out.

**Comment by joecool1029** [comment]
Electron-24 bails too, it's probably going to have to be patched to work on gcc-13 systems, very likely just #include <cstdint> in a bunch of places.

**Comment by PF4Public** [comment]
> Actually, probably anything >gcc-12 I think that's when they broke out that library?

Very much so. I have no issues with gcc-12 and clang-6, but latest Chromiums needed to be patched.


By the way, I may have omitted [these patches for chromium-112](https://dev.gentoo.org/~sam/distfiles/www-client/chromium/chromium-112-gcc-13-patches.tar.xz) in electron as they had appeared later than that. You may give it a shot and if it is good enough, I'll pull them into electron ebuild.

**Comment by gringus** [comment]
I should have MR for 22 with gcc-13 support sometime soon.

**Comment by gringus** [comment]
It's in #225 Feel free to try it. I suspect other electron versions might require no or small tweaks here and there.

**Comment by joecool1029** [comment]
> It's in #225 Feel free to try it. I suspect other electron versions might require no or small tweaks here and there.

Builds yeah, it could probably be trivially updated to latest minor 22. I still hit https://github.com/PF4Public/gentoo-overlay/issues/197 with element-desktop and it though, but nothing new there....

**Comment by PF4Public** [comment]
@joecool1029 Does electron itself work for you? If you're willing to investigate this further you'll need to build electron with debug info and provide a backtrace of a crash.

**Comment by joecool1029** [comment]
I'll do that, it will take me around a day to provide it.

**Comment by PF4Public** [comment]
Additionally maybe it is worth trying electron-25, maybe it'll behave better.

**Comment by PF4Public** [comment]
I'll close this issue for inactivity. Feel free to reopen when you have new information.

**Comment by joecool1029** [comment]
New abseil-cpp in gentoo seems to have solved this issue in past week or so. It builds now.  (sorry this took forever to test again)
