### ISSUE TITLE
=www-client/ungoogled-chromium-113.0.5672.92_p1 breaks when nvidia use flag enabled

### ISSUE THREAD

**Issue by logrusx** [PF4Public/gentoo-overlay#226]
```
[17541/49377] python3.11 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="x86_64-pc-linux-gnu-nm"  --sofile="./libGLESv2.so" --tocfile="./libGLESv2.so.TOC" --output="./libGLESv2.so" -- x86_64-pc-linux-gnu-clang++ -shared -Wl,-soname="libGLESv2.so" -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -no-canonical-prefixes -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--as-needed -o "./libGLESv2.so" @"./libGLESv2.so.rsp"  
FAILED: libGLESv2.so libGLESv2.so.TOC 
python3.11 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="x86_64-pc-linux-gnu-nm"  --sofile="./libGLESv2.so" --tocfile="./libGLESv2.so.TOC" --output="./libGLESv2.so" -- x86_64-pc-linux-gnu-clang++ -shared -Wl,-soname="libGLESv2.so" -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -no-canonical-prefixes -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--as-needed -o "./libGLESv2.so" @"./libGLESv2.so.rsp"  
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/libXNVCtrl.a(NVCtrl.o): in function `find_display':
(.text+0x2f): undefined reference to `XextFindDisplay'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: (.text+0x41): undefined reference to `XextCreateExtension'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: (.text+0x58): undefined reference to `XextFindDisplay'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/libXNVCtrl.a(NVCtrl.o): in function `wire_to_event':
(.text+0x16b): undefined reference to `XMissingExtension'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/libXNVCtrl.a(NVCtrl.o): in function `XNVCTRLSetTargetAttributeAndGetStatus':
(.text+0xabb): undefined reference to `XMissingExtension'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/libXNVCtrl.a(NVCtrl.o): in function `XNVCTRLStringOperation':
(.text+0x1e6b): undefined reference to `XMissingExtension'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/libXNVCtrl.a(NVCtrl.o): in function `close_display':
(.text+0xb): undefined reference to `XextRemoveDisplay'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/libXNVCtrl.a(NVCtrl.o): in function `find_display':
(.text+0x8c): undefined reference to `XextAddDisplay'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/libXNVCtrl.a(NVCtrl.o): in function `XNVCTRLSetTargetAttribute':
(.text+0x919): undefined reference to `XMissingExtension'
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/libXNVCtrl.a(NVCtrl.o): in function `XNVCTRLSetGvoColorConversion':
(.text+0x1719): undefined reference to `XMissingExtension'
x86_64-pc-linux-gnu-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
Gnome 44.1/Wayland
x11-drivers/nvidia-drivers-525.116.03

**Comment by PF4Public** [comment]
Hmm, weird. It didn't fail for me on nvidia. Please provide information on USE flags you use to build.

Also try building with `EXTRA_GN=\"use_lld=true\"`, or something like that.

**Comment by logrusx** [comment]
Hello,
I'm currently experiencing other problems and cannot investigate further. The use flags should be like that, ignore the asterisk of -system-av1, it's because I downgraded to 112, but when I built 113 it should have been exactly as portage wants to do it now:
`[ebuild     U  ] www-client/ungoogled-chromium-113.0.5672.92_p1::pf4public [112.0.5615.121_p1::pf4public] USE="X clang convert-dict cups gtk4 hangouts official optimize-webui proprietary-codecs pulseaudio screencast system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libusb system-openh264 system-png system-re2 system-snappy vaapi wayland -cfi -custom-cflags -debug -enable-driver -headless -hevc -kerberos -nvidia% -optimize-thinlto -pax-kernel% -pgo -pic -qt5 (-selinux) -suid -system-abseil-cpp% -system-av1* -system-brotli% -system-crc32c% -system-double-conversion% -system-libvpx -system-openjpeg -system-woff2% -thinlto -widevine"`

I'll try your suggestion as soon as I can.

Best Regards,
Georgi

**Comment by PF4Public** [comment]
You both don't use any USE flag, which would enable lld, thus I suspect that `use_lld=true` should solve it. If anyone of you could quickly verify it via `EXTRA_GN`, I'd update ebuild accordingly.

**Comment by logrusx** [comment]
It looks like it didn't break, it still hasn't finished, but it's beyond that point. I think the relevant line is this:

`[17152/49377] python3.11 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="x86_64-pc-linux-gnu-nm"  --sofile="./libGLESv2.so" --tocfile="./libGLESv2.so.TOC" --output="./libGLESv2.so" -- x86_64-pc-linux-gnu-clang++ -shared -Wl,-soname="libGLESv2.so" -fuse-ld=lld -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,--undefined-version -Wl,--no-call-graph-profile-sort -no-canonical-prefixes -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--as-needed -o "./libGLESv2.so" @"./libGLESv2.so.rsp"`

and it's nearing 25000 already, so I don't think it'll break, at least not at the same file.

I'll post an update when it's finished.

Best Regards,
Georgi

**Comment by logrusx** [comment]
Compiled.

**Comment by logrusx** [comment]
I can confirm the ebuild for 114 builds as is, without the need to supply use_lld=true.

Best Regards,
Georgi
