### ISSUE TITLE
www-client/ungoogled-chromium-113: broken

### ISSUE THREAD

**Issue by mirek967** [PF4Public/gentoo-overlay#227]
I tried several times to compile ungoogled-chromium-113.* with various use flags, but until now result is always the same.
All extensions get crashed at start, and browser is not able to connect to network. In this state it is rather unusefull. 
I compile it with gcc-12, and my system is free of clang.

When started from command line, there will be displayed a following log:

[516825:516825:0520/223410.460877:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
[516825:516825:0520/223410.817681:ERROR:service_worker_task_queue.cc(234)] DidStartWorkerFail fjkmabmdepjfammlpliljpnbhleegehm: 3
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
[516825:516825:0520/223410.827163:ERROR:service_worker_task_queue.cc(234)] DidStartWorkerFail ocaahdebbfolfmndjeplogmgcagdmblk: 3
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
[516825:516836:0520/223415.661532:ERROR:ev_root_ca_metadata.cc(285)] Failed to register OID: 0
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid

**Comment by PF4Public** [comment]
Does upstream chromium from Gentoo work for you? There is not much I can do about it unfortunately. Unless you're willing to fix this yourself.

**Comment by mirek967** [comment]
I will try to compile upstream. Then let's see.

**Comment by mirek967** [comment]
Compiled chromium over the night. Now I tested it. It have the same issues as ungoogled chromium. 
So it is an upstream problem.

**Comment by PF4Public** [comment]
And is is not even Gentoo. Google does no effort in making Chromium gcc-compatible. Sorry.

**Comment by PF4Public** [comment]
@mirek967 Please try 114. Maybe it'll behave better…

**Comment by mirek967** [comment]
I will try, I seen yesterday that there is new version. 
3 days ago I reported in chromium bugzilla as error. Right now there is no any answer on it.
https://bugs.chromium.org/p/chromium/issues/detail?id=1453205

**Comment by PF4Public** [comment]
BTW, maybe this is your issue: https://bugs.gentoo.org/906008?

**Comment by mirek967** [comment]
I successfully compiled latest version of chromium 114. And...... it works. 
I am surprised.
