### ISSUE TITLE
dev-util/electron-20.3.12-r1: Not possible to build with python 3.11.x

### ISSUE THREAD

**Issue by Imred-Gemu** [PF4Public/gentoo-overlay#238]
I need to build Electron 19 or 20 due to the [tree sitter issue](https://github.com/tree-sitter/tree-sitter-typescript/issues/244) in VSCode. As far as I understand, the only workaround for this currently is to use a version of Electron <21, however it is possible to build neither version with the current default version of Python from the main Gentoo repository. Both fail with the same error as shown in the attached logs: `ValueError: invalid mode: 'rU'`.
[build.log](https://github.com/PF4Public/gentoo-overlay/files/11844237/build.log)

**Comment by PF4Public** [comment]
Please try patching it like this:
```diff
--- a/tools/grit/grit/util.py
+++ b/tools/grit/grit/util.py
@@ -209,7 +209,7 @@
     mode = 'rb'
     encoding = None
   else:
-    mode = 'rU'
+    mode = 'r'
 
   with io.open(filename, mode, encoding=encoding) as f:
     return f.read()
```

**Comment by PF4Public** [comment]
BTW, what issue are you referring to exactly? There is an issue on ppc64 platform, that makes electron-19 and electron-20 the only options for now (and it is the reason I keep them in overlay). 

If you're on amd64 platform, you could try building vscode with electron-25. You need to build manually with the help of `ebuild` utility and revert e80a226cd25e3e4865575443f6ceccdf7a86e59f in `environment` before `src_configure` step.

At least it worked for me:
![image](https://github.com/PF4Public/gentoo-overlay/assets/10319700/db97c581-c8ad-408b-9c90-94a94a5713b2)

**Comment by Imred-Gemu** [comment]
> BTW, what issue are you referring to exactly? There is an issue on ppc64 platform, that makes electron-19 and electron-20 the only options for now (and it is the reason I keep them in overlay).
> 
> If you're on amd64 platform, you could try building vscode with electron-25. You need to build manually with the help of `ebuild` utility and revert [e80a226](https://github.com/PF4Public/gentoo-overlay/commit/e80a226cd25e3e4865575443f6ceccdf7a86e59f) in `environment` before `src_configure` step.
> 
> At least it worked for me: ![image](https://user-images.githubusercontent.com/10319700/248480431-db97c581-c8ad-408b-9c90-94a94a5713b2.png)

I did see that you had mentioned you were able to build VSCode with Electron 25 in another issue, however when I tried it with `app-editors/vscode-1.79.2`, I received the same error: `Error: bad export type for tree_sitter_typescript_external_scanner_create: undefined`. The commit you mentioned looks like it only changed the live ebuild, is that the only version you had working with Electron 25?

**Comment by PF4Public** [comment]
>You need to build manually with the help of ebuild utility and revert [e80a226](https://github.com/PF4Public/gentoo-overlay/commit/e80a226cd25e3e4865575443f6ceccdf7a86e59f) in environment before src_configure step.

As I've written above you need to replace  `/usr/bin/node` with `node` in order to attempt building via electron's built-in node instead of the system node. This would be only possible if you build with `ebuild` instead of `emerge`.

**Comment by Imred-Gemu** [comment]
> As I've written above you need to replace `/usr/bin/node` with `node` in order to attempt building via electron's built-in node instead of the system node. This would be only possible if you build with `ebuild` instead of `emerge`.

Sorry, I hadn't looked in the ebuild for `app-editors/vscode-1.79.2`, I see now it has the same changes. After switching it back to using Electron as Node, I was able to build using Electron 25, thank you very much for your help. I am building Electron 20 with the patch you suggested for the original issue, I will post if it succeeds or not.

**Comment by Imred-Gemu** [comment]
`dev-util/electron-20.3.12-r1` built successfully with the above patch and the dependency on the `xml` use flag from the Python package removed, as this use flag was dropped in the 3.11.x Python ebuilds.

**Comment by NriotHrreion** [comment]
> BTW, what issue are you referring to exactly? There is an issue on ppc64 platform, that makes electron-19 and electron-20 the only options for now (and it is the reason I keep them in overlay).
> 
> If you're on amd64 platform, you could try building vscode with electron-25. You need to build manually with the help of `ebuild` utility and revert [e80a226](https://github.com/PF4Public/gentoo-overlay/commit/e80a226cd25e3e4865575443f6ceccdf7a86e59f) in `environment` before `src_configure` step.
> 
> At least it worked for me: ![image](https://private-user-images.githubusercontent.com/10319700/248480431-db97c581-c8ad-408b-9c90-94a94a5713b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMzMzMDksIm5iZiI6MTcwODEzMzAwOSwicGF0aCI6Ii8xMDMxOTcwMC8yNDg0ODA0MzEtZGI5N2M1ODEtYzhhZC00MDhiLTljOTAtOTRhOTRhNTcxM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDAxMjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiY2ZmZWMzN2QzMjk3NGZkNTMwNWMyODUwNjVkOTZkZTFhN2Y5ZTYxM2RjM2ZmMDY1ZTQzZjdhNDFiMDgxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8nUprQQm5KIC6VRhIgRtdxDvN3hsnalA4TPV_ILm2SE)

@PF4Public I've read through the issues you created about the `tree_sitter_tsx_external_scanner_create`. And I got here and tried to change my electron version from `27.3.2` to `25.1.1`.

But when I re-ran `yarn` to re-install the dependencies, it stuck at
```bash
[4/4] Building fresh packages...
[20/20] ⠈ windows-foreground-love
[8/20] ⠈ @vscode/windows-process-tree
[18/20] ⠈ electron
[14/20] ⠈ node-pty
[5/20] ⠈ @vscode/spdlog
```
for a while and then reported
```bash
error D:\vscode\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: D:\vscode\node_modules\electron
Output:
ReadError: The server aborted pending request
    at IncomingMessage.<anonymous> (D:\vscode\node_modules\got\dist\source\core\index.js:809:31)
    at Object.onceWrapper (node:events:632:28)
    at IncomingMessage.emit (node:events:530:35)
    at origin.emit (D:\vscode\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
```

Btw, I've been struggling for some time and I couldn't solve it. So I made this comment under this issue page to find some help.

**Comment by NriotHrreion** [comment]
I tried some other versions (`19` `20` etc.) of electron just now and got `RequestError: read ECONNRESET` and `RequestError: socket hang up` error.

**Comment by NriotHrreion** [comment]
I solved this by switching my node version from `20.11.1` to `18.16.0`.

**Comment by PF4Public** [comment]
@NriotHrreion You seem to be on Windows. On Linux I solve this issue by running electron as node: `ELECTRON_RUN_AS_NODE=1 electron`. This works since electron has node 18 inside. The other solution (as you've already discovered) is to downgrade the real node and use it.
