### ISSUE TITLE
>=www-client/ungoogled-chromium-79 crashes on startup when built with widevine use flag

### ISSUE THREAD

**Issue by thubble** [PF4Public/gentoo-overlay#24]
NOTE - This issue happens with 79.0.3945.117 and 79.0.3945.130. I copied the 79.0.3945.117_p1 ebuild into my local repo in order to update to the .130 version before the ebuild was released. There were no other changes, except I did also comment out `chromium-compiler-r10.patch` in order to let Chromium do its own optimizations (basically just adding -O3 for v8, and -O2 everywhere else).
```
www-client/ungoogled-chromium-79.0.3945.130_p1::localrepo
USE="clang cups optimize-thinlto pdf proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-openh264 system-openjpeg tcmalloc thinlto vaapi widevine -cfi -closure-compile -convert-dict -custom-cflags -enable-driver -gnome -gnome-keyring -hangouts -jumbo-build -kerberos -optimize-webui (-selinux) -suid -system-libvpx" ABI_X86="(64)" L10N="am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk vi zh-CN zh-TW" PYTHON_TARGETS="python2_7 python3_6 python3_7 python3_8"
CFLAGS="-march=native -pipe -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
CXXFLAGS="-march=native -pipe -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
```

Crashes immediately after launch with the command line error:
`Trace/breakpoint trap`
And the following error in dmesg:
`traps: chrome[16264] trap int3 ip:55555a01a6e0 sp:7fffffffcc10 error:0 in chrome[555556c4d000+8839000]`

This is due to the following patch (included in ungoogled, but apparently from Debian) : https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/debian_buster/fixes/widevine-enable-version-string.patch

Starting in version 79, Chromium now allows Widevine to be either bundled (this is only enabled for Google's offical Chrome builds) or component-updated. What this patch does is always do the check for the "bundled" version even if only the component-updated version is enabled. However, Chromium wraps this "bundled widevine" code in their `CHECK()` macro, to make sure it was loaded successfully. For debug/non-official Chromium builds, this macro simply prints a warning to the command line and continues; however, if the gn flag `is_official_build=true` is used (as in this ebuild), it hard-crashes the app by inserting an illegal instruction. (Note this flag is NOT the same as the "offical Chrome build" I mentioned above, that's a separate flag only enabled by Google builds).

**Solution**
Delete `widevine-enable-version-string.patch` and remove it from the `series` file before applying the ungoogled-chromium patches (I'm not sure if both steps are necessary). I did this manually between the ebuild unpack/prepare commands, and this one step fixed the crash. Widevine is showing in `chrome://components/`.

I can report this to ungoogled-chromium upstream if you think it's more appropriate, but I suspect this patch may be necessary for certain builds/distros. On Gentoo, using the new "component-updated" Widevine code in chromium-79 works with the `www-plugins/chrome-binary-plugins` package which is exactly what it's intended for.

**Comment by PF4Public** [comment]
Thanks for reporting. There's nothing better than a bugreport that provides a solution :)

>comment out chromium-compiler-r10.patch in order to let Chromium do its own optimizations (basically just adding -O3 for v8, and -O2 everywhere else).

Would you suggest removing this patch from ebuild? Given your explanation, there is a valid reason to omit it.

With respect to `widevine-enable-version-string.patch` it is in fact trivial to exclude it and I will do so, if it really solves the issue. It would be useful however to (softly ;) ) report the same bug to ungoogled-chromium upstream, cross-linking the issues. Their input might be useful anyway. If they find nothing to fix on their end, I'll keep this exclusion in my ebuild.

**Comment by thubble** [comment]
I created an issue upstream: https://github.com/Eloston/ungoogled-chromium/issues/913

As for `chromium-compiler-r10.patch`, without it, the build makes the following changes to the compiler flags:
- Passes the clang version in a define.
- Adds the C[XX]FLAGS `-fno-ident -fdata-sections -ffunction-sections`
- Adds the LDFLAGS `-Wl,-O2 -Wl,--gc-sections`
- Adds `-O3` when building the V8 Javascript engine, and `-O2` everywhere else.
- Adds `march=` with whatever the gn flag `x64_arch` is set to. (`x86-64` if not defined).

So it doesn't do anything too crazy, but it will override certain flags like `-march=` so at the very least the patch should be applied if `custom-cflags` is set.

I have a `/etc/portage/env/` file to set `EXTRA_GN="x64_arch=\"native\""` and remove my usual `-O2` from the flags. This allows the default level of optimization recommended by Chromium.

Unfortunately, there's no easy way to build it the "Gentoo" way with the highest safe level of optimization, because it appears (at least according to the Chromium developers) that different parts of the code need different optimization levels. If the user specifies `-O2` then the Javascript engine will be built with lower optimization, but if they specify `-O3` then the rest of Chromium may use unsafe optimization. Combine that with things like LTO, and I have no idea what the right answer is here. :(

**Comment by PF4Public** [comment]
@thubble What do you think about `widevine-locations.patch`, that Eloston uses for Debian? Do we need it here in Gentoo or we just wait till `widevine-enable-version-string.patch` is removed from upstream repo?

I've also separated the second issue

**Comment by thubble** [comment]
It looks like the patch has already been removed upstream, in the .130-2 release: https://github.com/Eloston/ungoogled-chromium/commit/9f7c10722c37feef3124d957f5ef2dfd2a285e33

**Comment by PF4Public** [comment]
> It looks like the patch has already been removed upstream, in the .130-2 release: [Eloston/ungoogled-chromium@9f7c107](https://github.com/Eloston/ungoogled-chromium/commit/9f7c10722c37feef3124d957f5ef2dfd2a285e33)

Yep, just checked the repo. Wasn't aware of this, while writing.

What about `widevine-locations.patch`?

**Comment by thubble** [comment]
`widevine-locations.patch` is only for snap builds, it shouldn't be necessary for Gentoo. The build seems to find the `chrome-binary-plugins` installation just fine.

**Comment by PF4Public** [comment]
I bump revision and close this then
