### ISSUE TITLE
ungoogled-chromium-114.0.5735.198_p1: "chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch VERIFY FAILED!"

### ISSUE THREAD

**Issue by GeorgiaM-honestly** [PF4Public/gentoo-overlay#240]
Attempting to emerge ungoogled-chromium-114.0.5735.198_p1. During the various fetches, chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch is downloaded however it fails verification:

Is there something I can do to help or more information to provide?

--2023-06-28 18:36:27--  http://distfiles.gentoo.org/distfiles/b5/chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch
Resolving distfiles.gentoo.org... 89.187.167.2, 195.181.164.17
Connecting to distfiles.gentoo.org|89.187.167.2|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-28 18:36:28 ERROR 404: Not Found.

--2023-06-28 18:36:28--  https://github.com/chromium/chromium/commit/2914039316d4ed3f53c3393dc2ba48f637807689.patch
Resolving github.com... 140.82.121.4
Connecting to github.com|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2334 (2.3K) [text/plain]
Saving to: ‘/var/cache/distfiles/chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch.__download__’

     0K ..                                                    100% 17.0M=0s

2023-06-28 18:36:29 (17.0 MB/s) - ‘/var/cache/distfiles/chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch.__download__’ saved [2334/2334]

!!! Fetched file: chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      2334
!!! Expected: 2330
Refetching... File renamed to '/var/cache/distfiles/chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch._checksum_failure_.tl0azhha'

!!! Couldn't download 'chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch'. Aborting.
 * Fetch failed for 'www-client/ungoogled-chromium-114.0.5735.198_p1', Log file:
[build.log.gz](https://github.com/PF4Public/gentoo-overlay/files/11900478/build.log.gz)

**Comment by PF4Public** [comment]
Interesting :) They've added 4 more bytes :)
```diff
--- chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch
+++ chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch
@@ -18,7 +18,7 @@
  2 files changed, 2 insertions(+), 2 deletions(-)
 
 diff --git a/chrome/browser/printing/print_backend_service_manager.cc b/chrome/browser/printing/print_backend_service_manager.cc
-index b5a4b525a2d68..224369cd58cfa 100644
+index b5a4b525a2d689..224369cd58cfa6 100644
 --- a/chrome/browser/printing/print_backend_service_manager.cc
 +++ b/chrome/browser/printing/print_backend_service_manager.cc
 @@ -1477,7 +1477,7 @@ template <class... T>
@@ -31,7 +31,7 @@
    if (found_callbacks_map == saved_callbacks.end())
      return;  // No callbacks to run.
 diff --git a/chrome/browser/printing/print_backend_service_manager.h b/chrome/browser/printing/print_backend_service_manager.h
-index 41788f42a9593..6aa7479c1fdc8 100644
+index 41788f42a95933..6aa7479c1fdc83 100644
 --- a/chrome/browser/printing/print_backend_service_manager.h
 +++ b/chrome/browser/printing/print_backend_service_manager.h
 @@ -588,7 +588,7 @@ class PrintBackendServiceManager {
```
