### ISSUE TITLE
www-client/ungoogled-chromium-114.0.5735.198_p1: "chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch VERIFY FAILED!"

### ISSUE THREAD

**Issue by GeorgiaM-honestly** [PF4Public/gentoo-overlay#242]
OMG I'm baaack!

Thanks for all your work on this, seems like a pain in the backside.

>>> Failed to emerge www-client/ungoogled-chromium-114.0.5735.198_p1, Log file:
>>>  '/var/tmp/portage/www-client/ungoogled-chromium-114.0.5735.198_p1/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.86, 0.56, 0.40
--2023-06-29 10:27:10--  http://distfiles.gentoo.org/distfiles/cb/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch
Resolving distfiles.gentoo.org... 89.187.167.6, 195.181.164.21
Connecting to distfiles.gentoo.org|89.187.167.6|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-29 10:27:11 ERROR 404: Not Found.

--2023-06-29 10:27:11--  https://github.com/chromium/chromium/commit/54969766fd2029c506befc46e9ce14d67c7ed02a.patch
Resolving github.com... 140.82.121.3
Connecting to github.com|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2127 (2.1K) [text/plain]
Saving to: ‘/var/cache/distfiles/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch.__download__’

     0K ..                                                    100% 35.6M=0s

2023-06-29 10:27:12 (35.6 MB/s) - ‘/var/cache/distfiles/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch.__download__’ saved [2127/2127]

!!! Fetched file: chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      2127
!!! Expected: 2125
Refetching... File renamed to '/var/cache/distfiles/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch._checksum_failure_.xphzxoid'

!!! Couldn't download 'chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch'. Aborting.
 * Fetch failed for 'www-client/ungoogled-chromium-114.0.5735.198_p1', Log file:
 *  '/var/tmp/portage/www-client/ungoogled-chromium-114.0.5735.198_p1/temp/build.log'

 * Messages for package www-client/ungoogled-chromium-114.0.5735.198_p1:

 * Fetch failed for 'www-client/ungoogled-chromium-114.0.5735.198_p1', Log file:
 *  '/var/tmp/portage/www-client/ungoogled-chromium-114.0.5735.198_p1/temp/build.log'
[build.log.gz](https://github.com/PF4Public/gentoo-overlay/files/11907341/build.log.gz)

**Comment by PF4Public** [comment]
There was no need in opening another issue.
