### ISSUE TITLE
dev-util/electron-25.8.0: Error for chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch in the manifest.

### ISSUE THREAD

**Issue by Imred-Gemu** [PF4Public/gentoo-overlay#248]
Emerge output:
```
>>> Downloading 'https://github.com/chromium/chromium/commit/54969766fd2029c506befc46e9ce14d67c7ed02a.patch'
--2023-09-03 20:44:56--  https://github.com/chromium/chromium/commit/54969766fd2029c506befc46e9ce14d67c7ed02a.patch
Resolving github.com... 140.82.113.4
Connecting to github.com|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2127 (2.1K) [text/plain]
Saving to: ‘/var/cache/distfiles/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch.__download__’

/var/cache/distfile 100%[===================>]   2.08K  --.-KB/s    in 0.002s  

2023-09-03 20:44:57 (1.10 MB/s) - ‘/var/cache/distfiles/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch.__download__’ saved [2127/2127]

!!! Fetched file: chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      2127
!!! Expected: 2129
Refetching... File renamed to '/var/cache/distfiles/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch._checksum_failure_.ecw16tcm'

!!! Couldn't download 'chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch'. Aborting.
```

Contents of /var/cache/distfiles/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch.\_checksum_failure\_.ecw16tcm:
```
From 54969766fd2029c506befc46e9ce14d67c7ed02a Mon Sep 17 00:00:00 2001
From: Arthur Eubanks <aeubanks@google.com>
Date: Tue, 25 Apr 2023 03:05:19 +0000
Subject: [PATCH] Reland [clang] Disable autoupgrading debug info in ThinLTO
 builds

ThinLTO reads bitcode many times and attempts to upgrade the debug info every time. This is expensive since it calls the verifier. We don't need this given all LLVM bitcode producers are from the same version of LLVM.

For just the build step that runs ThinLTO and links official Chrome, measured 34T -> 32T instructions via perf stat.

Reland disables adding flag for ChromeOS since that toolchain is too old to have this flag.

Bug: 972449
Change-Id: I44552dd6c9dc71683c002d0c885e78b2a4341659
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4470209
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Arthur Eubanks <aeubanks@google.com>
Cr-Commit-Position: refs/heads/main@{#1135007}
---
 build/config/compiler/BUILD.gn | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/build/config/compiler/BUILD.gn b/build/config/compiler/BUILD.gn
index 1c13bc80f0fa87..53db095c1b1efa 100644
--- a/build/config/compiler/BUILD.gn
+++ b/build/config/compiler/BUILD.gn
@@ -685,6 +685,7 @@ config("compiler") {
         "/lldltocache:" +
             rebase_path("$root_out_dir/thinlto-cache", root_build_dir),
         "/lldltocachepolicy:$cache_policy",
+        "-mllvm:-disable-auto-upgrade-debug-info",
       ]
     } else {
       ldflags += [ "-flto=thin" ]
@@ -725,6 +726,14 @@ config("compiler") {
       }
 
       ldflags += [ "-Wl,-mllvm,-import-instr-limit=$import_instr_limit" ]
+
+      if (!is_chromeos) {
+        # TODO(https://crbug.com/972449): turn on for ChromeOS when that
+        # toolchain has this flag.
+        # We only use one version of LLVM within a build so there's no need to
+        # upgrade debug info, which can be expensive since it runs the verifier.
+        ldflags += [ "-Wl,-mllvm,-disable-auto-upgrade-debug-info" ]
+      }
     }
 
     # TODO(https://crbug.com/1211155): investigate why this isn't effective on
```

SHA512:
`30c5dbe0aed5257ef22bd3bccfbcdcf17729fc1aa383dbfae746ba486efeb07f7c2d0e4a67dfe509836a931a3e316b84b8cfafd685f2380705ed2cd435d037b1  /var/cache/distfiles/chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch._checksum_failure_.ecw16tcm`

This is the same SHA512 from before this commit: https://github.com/PF4Public/gentoo-overlay/commit/6c571d8ff4ce049992dd7c52b88f8492d2e660c9, it appears whatever changes were made to this file were reverted. This is the only file used in the Electron ebuild that was changed back as far as I can tell.

**Comment by PF4Public** [comment]
See #240 #242

**Comment by Imred-Gemu** [comment]
I wrote a script which runs the fetch step repeatedly until it succeeds, it took a while but it did eventually work. All the failed files just have a couple characters added or missing on the index line. I wrote a script to delete and refetch the files 100 times, piping the output into a file:
```
grep "VERIFY FAILED" /tmp/emerge.log | sort | uniq -c
     77 !!! Fetched file: chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch VERIFY FAILED!
     65 !!! Fetched file: chromium-2af2d08972d14d5bdd91e0515eb5b15b4444aee9.patch VERIFY FAILED!
     40 !!! Fetched file: chromium-54969766fd2029c506befc46e9ce14d67c7ed02a.patch VERIFY FAILED!
     31 !!! Fetched file: chromium-a1fec6273f3ad7c73b35bb420a5540355df35b74.patch VERIFY FAILED!
```
The versions of chromium-2914039316d4ed3f53c3393dc2ba48f637807689.patch and chromium-2af2d08972d14d5bdd91e0515eb5b15b4444aee9.patch expected by the manifest are less likely than the altered versions, and so far in my testing are the files that take the longest to download and cache when running the fetch step repeatedly until succeeding as mentioned earlier. Not sure if this changes over time though.

**Comment by PF4Public** [comment]
Using commits like this is very convenient for me, it is a pity that it works like this :( 

Maybe I should include those commits as files instead…

**Comment by Imred-Gemu** [comment]
A simple regex could fix this if there was a way to do any processing on files before they are verified, I don't know of any way to do the latter in an ebuild though.

**Comment by PF4Public** [comment]
"if there was" :(

**Comment by Imred-Gemu** [comment]
Right, unfortunately. Please feel free to close this if you would like, or keep it if you would like to use it to track a long term solution. For now I will be relying on my method of brute forcing it until the fetch command succeeds, or I get IP banned from Github for spam. Here is the command I'm using in case anyone else runs into this:
`while ! emerge --fetchonly --ask=n dev-util/electron:25; do echo "Refetching"; done`
Then just emerge as normal

**Comment by PF4Public** [comment]
> For now I will be relying on my method of brute forcing it until the fetch command succeeds, or I get IP banned from Github for spam.

Your script needs to succeed just once, if you don't clear distfiles, you'll have the right ones for the next build.

I'll ~postpone~ keep this issue open for now.

**Comment by Imred-Gemu** [comment]
> Your script needs to succeed just once, if you don't clear distfiles, you'll have the right ones for the next build.

Right, that's what I'm doing in practice. Clearing the distfiles earlier was just to test how often each individual file fails to verify. Even that script did succeed once though it took several hours. When allowing it to cache the distfiles normally, it seems to take 5-10 minutes.

**Comment by PF4Public** [comment]
I've filed issue for GitHub 3 days ago, no reply jet.

**Comment by PF4Public** [comment]
They suggested appending `?full_index=true` to URL. Hope it works.
