### ISSUE TITLE
Allow for default Chromium optimizations in ungoogled-chromium

### ISSUE THREAD

**Issue by PF4Public** [PF4Public/gentoo-overlay#25]
**Is your feature request related to a problem? Please describe.**
In #24 @thubble demonstrated that with `chromium-compiler-r10.patch` applied user-defined flags and optimisations are preferred over the defaults, set by Chromium developers. 
Without this patch, the build makes the following changes to the compiler flags:

- Passes the clang version in a define.
- Adds the C[XX]FLAGS `-fno-ident -fdata-sections -ffunction-sections`
- Adds the LDFLAGS `-Wl,-O2 -Wl,--gc-sections`
- Adds `-O3` when building the V8 Javascript engine, and `-O2` everywhere else.
- Adds `march=` with whatever the gn flag `x64_arch` is set to. (`x86-64` if not defined).

It is clear, that preferring user flags could result in applying `-O2` everywhere. Since Chromium developers set `-O3` for v8, there might be a good reason to do so. 

**Describe the solution you'd like**
It could be advantageous to instead use defaults and strip user defined flags in ordinary builds and allow user optimizations with `custom-cflags`

**Comment by PF4Public** [comment]
I've played a bit with it.

Filtering "-O*" and "-Wl,-O*" I've removed those flags and now it looks promising.

Now compilation looks like this:

> [767/771] x86_64-pc-linux-gnu-clang++ -MMD -MF obj/third_party/protobuf/protobuf_lite/generated_message_util.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"373424-64a362e7-1\" -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -I../../third_party/protobuf/src -fprofile-sample-use=../../chrome/android/profiles/afdo.prof -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables **-m64 -march=x86-64 -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections** -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-reorder-init-list -Wno-final-dtor-non-final-class -Wno-sizeof-array-div -Wno-unused-function -Wno-shorten-64-to-32 -std=c++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -D__DATE__= -D__TIME__= -D__TIMESTAMP__= **-march=haswell -pipe -Wno-unknown-warning-option -Wno-builtin-macro-redefined** -c ../../third_party/protobuf/src/google/protobuf/generated_message_util.cc -o obj/third_party/protobuf/protobuf_lite/generated_message_util.o

Linking:

> [771/771] x86_64-pc-linux-gnu-clang++ -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=8 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=10g:cache_size_files=100000 -Wl,--lto-O2 -fwhole-program-vtables -m64 **-Wl,-O2 -Wl,--gc-sections** -rdynamic -pie -Wl,--disable-new-dtags -Wl,--as-needed -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=8 -o "./convert_dict" -Wl,--start-group @"./convert_dict.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -licui18n -licuuc -licudata -levent

And V8:

> [32/219] x86_64-pc-linux-gnu-clang++ -MMD -MF obj/v8/v8_libbase/logging.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"373424-64a362e7-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DENABLE_MINOR_MC -DV8_INTL_SUPPORT -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_CONCURRENT_MARKING -DV8_ENABLE_LAZY_SOURCE_POSITIONS -DV8_EMBEDDED_BUILTINS -DV8_SHARED_RO_HEAP -DV8_WIN64_UNWINDING_INFO -DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH -DV8_DEPRECATION_WARNINGS -DV8_TARGET_ARCH_X64 -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_LINUX -DDISABLE_UNTRUSTED_CODE_MITIGATIONS -DV8_DEPRECATION_WARNINGS -I../.. -Igen -I../../v8 -Igen/v8 -fprofile-sample-use=../../chrome/android/profiles/afdo.prof -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables **-m64 -march=x86-64** -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-reorder-init-list -Wno-final-dtor-non-final-class -Wno-sizeof-array-div -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wmissing-field-initializers -Wunreachable-code -Wshorten-64-to-32 **-O3 -fno-ident -fdata-sections -ffunction-sections** -std=c++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= **-march=haswell -pipe -Wno-unknown-warning-option -Wno-builtin-macro-redefined** -c ../../v8/src/base/logging.cc -o obj/v8/v8_libbase/logging.o

@thubble , is it what you were trying to achieve?

**Comment by thubble** [comment]
Yep, that looks fine. It's still adding `-march=x86-64`, but the custom CFLAGS are added later in the parameters list so should be overriding it. To fix, users can add `EXTRA_GN="x64_arch=\"native\""` (or whatever arch they want) in an `/etc/portage/package.env` customization. I think there are gn flags for other architectures like ARM, but I haven't looked into it.

**Comment by PF4Public** [comment]
> It's still adding `-march=x86-64`, but the custom CFLAGS are added later in the parameters list so should be overriding it. 

Exactly! But there's nothing to fix further. Like you may see in my quotes '-march=haswell' is taken from my make.conf. `-O2` was stripped by ebuild beforehand.
