### ISSUE TITLE
x11/caffeine-ng: Python Targets Over 3.10

### ISSUE THREAD

**Issue by tbsteinb** [PF4Public/gentoo-overlay#253]
According to the [readme](https://codeberg.org/WhyNotHugo/caffeine-ng/src/branch/main/README.md), caffeine-ng currently only supports Python versions up to 3.10. In my case I had 3.10 and 3.11 both active with 3.11 taking precedence, which caused an import error when trying to launch the program.

Until upstream updates to use 3.11+, the Python Targets should be changed to include only python3_10.

For reference, the error is `AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'` which occurs due to a change in Python's libraries.

**Comment by PF4Public** [comment]
Thanks for reporting.
