### ISSUE TITLE
www-client/ungoogled-chromium-117.0.5938.88_p1 error: conflicting types for 'gsk_render_node_get_node_type'

### ISSUE THREAD

**Issue by logrusx** [PF4Public/gentoo-overlay#259]
`[20118/51575] x86_64-pc-linux-gnu-clang++ -MMD -MF obj/ui/gtk/gtk_stubs/gtk_stubs.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DBASE_USE_PERFETTO_CLIENT_LIBRARY=1 -Igen/ui/gtk -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/jsoncpp_shim -Igen/shim_headers/libevent_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/lib64/libffi/include -mfpmath=sse -msse -msse2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/lib64/libffi/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/graphene-1.0 -I/usr/lib64/graphene-1.0/include -I/usr/include/gtk-4.0/unix-print -DPROTOBUF_ALLOW_DEPRECATED=1 -std=c++20 -Wno-trigraphs -gsimple-template-names -fno-exceptions -fno-rtti -fvisibility-inlines-hidden  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=znver3 -pipe -Wno-unknown-warning-option -Wno-builtin-macro-redefined -c gen/ui/gtk/gtk_stubs.cc -o obj/ui/gtk/gtk_stubs/gtk_stubs.o
FAILED: obj/ui/gtk/gtk_stubs/gtk_stubs.o 
x86_64-pc-linux-gnu-clang++ -MMD -MF obj/ui/gtk/gtk_stubs/gtk_stubs.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DBASE_USE_PERFETTO_CLIENT_LIBRARY=1 -Igen/ui/gtk -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/jsoncpp_shim -Igen/shim_headers/libevent_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/lib64/libffi/include -mfpmath=sse -msse -msse2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/lib64/libffi/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/graphene-1.0 -I/usr/lib64/graphene-1.0/include -I/usr/include/gtk-4.0/unix-print -DPROTOBUF_ALLOW_DEPRECATED=1 -std=c++20 -Wno-trigraphs -gsimple-template-names -fno-exceptions -fno-rtti -fvisibility-inlines-hidden  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=znver3 -pipe -Wno-unknown-warning-option -Wno-builtin-macro-redefined -c gen/ui/gtk/gtk_stubs.cc -o obj/ui/gtk/gtk_stubs/gtk_stubs.o
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:1:19: error: conflicting types for 'gsk_render_node_get_node_type'
GskRenderNodeType gsk_render_node_get_node_type(GskRenderNode* node);
                  ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:121:25: note: previous declaration is here
GskRenderNodeType       gsk_render_node_get_node_type           (const GskRenderNode *node);
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:3:16: error: conflicting types for 'gsk_transform_node_get_child'
GskRenderNode* gsk_transform_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:404:25: note: previous declaration is here
GskRenderNode *         gsk_transform_node_get_child            (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:4:16: error: conflicting types for 'gsk_opacity_node_get_child'
GskRenderNode* gsk_opacity_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:414:25: note: previous declaration is here
GskRenderNode *         gsk_opacity_node_get_child              (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:5:16: error: conflicting types for 'gsk_color_matrix_node_get_child'
GskRenderNode* gsk_color_matrix_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:425:25: note: previous declaration is here
GskRenderNode *         gsk_color_matrix_node_get_child         (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:6:16: error: conflicting types for 'gsk_repeat_node_get_child'
GskRenderNode* gsk_repeat_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:439:25: note: previous declaration is here
GskRenderNode *         gsk_repeat_node_get_child               (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:7:16: error: conflicting types for 'gsk_clip_node_get_child'
GskRenderNode* gsk_clip_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:449:25: note: previous declaration is here
GskRenderNode *         gsk_clip_node_get_child                 (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:8:16: error: conflicting types for 'gsk_rounded_clip_node_get_child'
GskRenderNode* gsk_rounded_clip_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:459:25: note: previous declaration is here
GskRenderNode *         gsk_rounded_clip_node_get_child         (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:9:16: error: conflicting types for 'gsk_shadow_node_get_child'
GskRenderNode* gsk_shadow_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:470:25: note: previous declaration is here
GskRenderNode *         gsk_shadow_node_get_child               (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:10:16: error: conflicting types for 'gsk_blur_node_get_child'
GskRenderNode* gsk_blur_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:530:25: note: previous declaration is here
GskRenderNode *         gsk_blur_node_get_child                 (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:11:16: error: conflicting types for 'gsk_debug_node_get_child'
GskRenderNode* gsk_debug_node_get_child(GskRenderNode* node);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:204:25: note: previous declaration is here
GskRenderNode *         gsk_debug_node_get_child                (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:12:16: error: conflicting types for 'gsk_container_node_get_child'
GskRenderNode* gsk_container_node_get_child(GskRenderNode* node, guint idx);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:395:25: note: previous declaration is here
GskRenderNode *         gsk_container_node_get_child            (const GskRenderNode      *node,
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:13:16: error: conflicting types for 'gsk_gl_shader_node_get_child'
GskRenderNode* gsk_gl_shader_node_get_child(GskRenderNode* node, guint idx);
               ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:558:25: note: previous declaration is here
GskRenderNode *         gsk_gl_shader_node_get_child            (const GskRenderNode      *node,
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:14:7: error: conflicting types for 'gsk_container_node_get_n_children'
guint gsk_container_node_get_n_children(GskRenderNode* node);
      ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:393:25: note: previous declaration is here
guint                   gsk_container_node_get_n_children       (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:15:7: error: conflicting types for 'gsk_gl_shader_node_get_n_children'
guint gsk_gl_shader_node_get_n_children(GskRenderNode* node);
      ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:556:25: note: previous declaration is here
guint                   gsk_gl_shader_node_get_n_children       (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
In file included from gen/ui/gtk/gtk_stubs.cc:12:
In file included from ../../ui/gtk/gtk_compat.h:25:
../../ui/gtk/gsk.sigs:16:13: error: conflicting types for 'gsk_texture_node_get_texture'
GdkTexture* gsk_texture_node_get_texture(GskRenderNode* node);
            ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:222:25: note: previous declaration is here
GdkTexture *            gsk_texture_node_get_texture            (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
gen/ui/gtk/gtk_stubs.cc:727:26: error: conflicting types for 'gsk_render_node_get_node_type'
extern GskRenderNodeType gsk_render_node_get_node_type(GskRenderNode* node) __attribute__((weak));
                         ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:121:25: note: previous declaration is here
GskRenderNodeType       gsk_render_node_get_node_type           (const GskRenderNode *node);
                        ^
gen/ui/gtk/gtk_stubs.cc:729:20: error: conflicting types for 'gsk_render_node_get_node_type'
GskRenderNodeType  gsk_render_node_get_node_type(GskRenderNode* node) {
                   ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:121:25: note: previous declaration is here
GskRenderNodeType       gsk_render_node_get_node_type           (const GskRenderNode *node);
                        ^
gen/ui/gtk/gtk_stubs.cc:737:23: error: conflicting types for 'gsk_transform_node_get_child'
extern GskRenderNode* gsk_transform_node_get_child(GskRenderNode* node) __attribute__((weak));
                      ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:404:25: note: previous declaration is here
GskRenderNode *         gsk_transform_node_get_child            (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
gen/ui/gtk/gtk_stubs.cc:739:17: error: conflicting types for 'gsk_transform_node_get_child'
GskRenderNode*  gsk_transform_node_get_child(GskRenderNode* node) {
                ^
/usr/include/gtk-4.0/gsk/gskrendernode.h:404:25: note: previous declaration is here
GskRenderNode *         gsk_transform_node_get_child            (const GskRenderNode      *node) G_GNUC_PURE;
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
`

`[ebuild     U  ] www-client/ungoogled-chromium-117.0.5938.88_p1::pf4public [116.0.5845.179_p1::pf4public] USE="X bluetooth clang convert-dict cups gtk4 hangouts nvidia official optimize-webui proprietary-codecs pulseaudio screencast system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libusb system-openh264 system-png system-snappy vaapi wayland widevine -cfi -custom-cflags -debug -enable-driver -headless -hevc -kerberos -optimize-thinlto -override-data-dir% -pax-kernel -pgo -pic -qt5 -qt6 (-selinux) -suid -system-abseil-cpp -system-av1 -system-brotli -system-crc32c -system-double-conversion -system-libvpx -system-openjpeg -system-re2 -system-woff2 -thinlto -uazo-bromite"`

[build.log](https://drive.google.com/file/d/1kEXtI3oRyd8we6AqprJ2DTADntP-cseg/view?usp=sharing)

**Comment by PF4Public** [comment]
Please try this patch: https://gitlab.com/Matt.Jolly/chromium-patches/-/blob/master/chromium-117-later-gtk4-version.patch?ref_type=heads

**Comment by logrusx** [comment]
I think it worked. I applied the patch directly in the work directory and resumed with keepwork. The same line which failed before now succeeded. It should be sufficient proof it works.

Thanks!

Best Regards,
Georgi
