### ISSUE TITLE
www-client/ungoogled-chromium-118: system-ffmpeg crash

### ISSUE THREAD

**Issue by gringus** [PF4Public/gentoo-overlay#267]
Even though `ungoogled-chromium-118` builds just fine with `ffmpeg-4/5/6` (`5` & `6` require [patch](https://aur.archlinux.org/cgit/aur.git/plain/040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch?h=ffmpeg-full)), it crashes with Zoom (eg. https://zoom.us/test) with Aw Snap error (SIGTRAP). I tried the following:
`ffmpeg-4.4`: crashes
`ffmpeg-5.1` (with [patch](https://aur.archlinux.org/cgit/aur.git/plain/040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch?h=ffmpeg-full)): crashes
`ffmpeg-6.0` (with [patch](https://aur.archlinux.org/cgit/aur.git/plain/040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch?h=ffmpeg-full)): crashes
`ffmpeg-9999` (with [patch](https://aur.archlinux.org/cgit/aur.git/plain/040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch?h=ffmpeg-full)): crashes
bundled `ffmpeg`: works just fine
As much as I love to use system `ffmpeg` with `ungoogled-chromium` it feels like it's currently not safe to use it.

**Comment by gringus** [comment]
I think they dropped building `chromium` with system `ffmpeg` recently. I tried briefly to debug it, but seems like `chromium` might be intercepting the signal. I will try later as I returned my new desktop and have to use the old one which is much slower.

**Comment by PF4Public** [comment]
I know that Gentoo Chromium dropped system-ffmpeg (such a pity), but you can `ebuild ungoogled-chromium.ebuild unpack`, remove `ungoogled-chrommium` folder, clean `environment` file from "ungoogling" procedures and build normally. You should also attempt building debug version and probably disable sandbox and forking behaviour in order to obtain meaningful backtrace.

Given that it does not crash on ordinary videos it might be related to webrtc or something like that. Perhaps _that_ code expects some hidden API available only in built-in ffmpeg. Alternatively it might be some leftovers not taken care of by "ungoogling" process, that's why I asked if you tried vanilla Chromium.

By the way, did it crash in 117?

**Comment by gringus** [comment]
@PF4Public I did not go far.. First I ran into problems building `chromium-119` with `debug` enabled.. In the end, the only error message showing up during failure is:
```
[335975:335978:1106/181237.585069:FATAL:ffmpeg_glue.cc(160)] Check failed: container_ != container_names::MediaContainerName::kContainerUnknown (0 vs. 0)
```

**Comment by PF4Public** [comment]
Perhaps dumping (somehow) `format_context_->iformat->name` could give a lead.

**Comment by gringus** [comment]
FYI: Along with the patch included in https://github.com/ungoogled-software/ungoogled-chromium/issues/2034#issuecomment-1795907332 you also need below patch to be able to build `chromium-119`:
```
--- chromium-119.0.6045.105/v8/src/compiler/turboshaft/utils.h.orig 2023-11-01 19:13:17.516947700 +0100
+++ chromium-119.0.6045.105/v8/src/compiler/turboshaft/utils.h  2023-11-06 13:23:44.259889845 +0100
@@ -6,6 +6,7 @@
 #define V8_COMPILER_TURBOSHAFT_UTILS_H_

 #include <iostream>
+#include <limits>
 #include <tuple>

 #include "src/base/logging.h"
```
This one feels like `gcc-13` and `chromium` related.

**Comment by PF4Public** [comment]
> This one feels like `gcc-13` and `chromium` related.

Agreed. I remember I had to do something similar when building debug variant.

By the way, have you enabled hevc? Could be it is searching for av1 and not finding it?

**Comment by gringus** [comment]
No, I used to have `system-av1` but there are some constraints regarding `system-av1` and `system-ffmpeg`, so I disabled it.

**Comment by PF4Public** [comment]
I meant the USE flag `hevc`

**Comment by gringus** [comment]
Patch:
```
   // For a successfully opened file, we will get a container we've compiled in.
+  LOG(ERROR) << "iformat->name: " << format_context_->iformat->name;
   CHECK_NE(container_, container_names::MediaContainerName::kContainerUnknown);
   LogContainer(is_local_file, container_);
```
and result:
```
[1708:3:1108/075224.121591:ERROR:ffmpeg_glue.cc(161)] iformat->name: mpegts
[1708:3:1108/075224.121679:FATAL:ffmpeg_glue.cc(162)] Check failed: container_ != container_names::MediaContainerName::kContainerUnknown (0 vs. 0)
```

**Comment by gringus** [comment]
`hevc` requires `system-ffmpeg` which I disabled (to make Zoom work)
`system-av1` cannot work with `vaapi` (which I enabled)
So neither `hevc` nor `system-av1` are enabled on my system ATM.

**Comment by gringus** [comment]
Interestingly with bundled `ffmpeg` I only see these:
```
[139491:4:1108/125615.191700:ERROR:ffmpeg_glue.cc(161)] iformat->name: mp3
[139491:3:1108/125615.191701:ERROR:ffmpeg_glue.cc(161)] iformat->name: mp3
```

**Comment by PF4Public** [comment]
It might not be going through that routine with built-in ffmpeg. Have you tried to find corresponding `container_names::MediaContainerName::` for mpegts and add it to if/else ladder?

**Comment by PF4Public** [comment]
@gringus Should I add `symbol_level=2`, `blink_symbol_level=2` and `v8_symbol_level=2` under debug condition as was suggested in linked issue?

**Comment by gringus** [comment]
Doesn't hurt.. especially if you enable `debug` it means you are looking for answers...

**Comment by gringus** [comment]
The latest `ungoogled-chromium` forbids to to build with `debug` and `official` flags at the same time.

**Comment by gringus** [comment]
Seems like the latest `clang`/`llvm` (`17.0.4`) is stricter about types as now I get many similar errors of format:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/debug/helper_functions.h:185:13: error: invalid operands to binary expression ('spvtools::opt::UptrVectorIterator<spvtools::opt::BasicBlock>' and 'spvtools::opt::UptrVectorIterator<spvtools::opt::BasicBlock>')
  185 |         && __first <= __last;
```
I just give up..

**Comment by PF4Public** [comment]
> The latest `ungoogled-chromium` forbids to to build with `debug` and `official` flags at the same time.

That's probably because I enabled is_debug. Should I keep it false instead?

>Seems like the latest clang/llvm (17.0.4) is stricter about types as now I get many similar errors of format:

Are you sure it is not because of enabling is_debug?

**Comment by gringus** [comment]
It's possible.. I assumed clang/llvm as that was the only recent change in the stack I made on my system.

**Comment by PF4Public** [comment]
I remember building non-debug versions with 17.0.4 for some time without issues.

**Comment by gringus** [comment]
Non-debug works fine (I use one), but potentially `debug` exposes some extra code which `clang` does not like.

**Comment by PF4Public** [comment]
Sooooo, is `is_debug` of any use while debugging or maybe just enabling symbols would suffice?

**Comment by gringus** [comment]
I presume `is_debug` prints lots of debug information whereas extra symbols don't ..

**Comment by PF4Public** [comment]
@gringus Have you tried 121? Video stream and audio do not seem to work (didn't debug further though), but at least it does not crash the tab.

**Comment by gringus** [comment]
@PF4Public I'm sorry, but in the meantime, I switched to Firefox and did not use `ungoogled-chromium` for quite some time now.

**Comment by PF4Public** [comment]
No problem. I'll close this issue then.
