### ISSUE TITLE
Build failure - vapigen

### ISSUE THREAD

**Issue by scottfurry** [PF4Public/gentoo-overlay#27]
**Description**
Using ebuild from repo, attempt to build locally would always result in a build failure at item 50/123.
Ebuild would fail out with the message:
```
ninja: build stopped: subcommand failed.
* ERROR: app-misc/font-manager-0.7.7::overlay failed (compile phase):
 *   ninja -v -j6 -l6 -C /var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7-build failed
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_compile
 *   environment, line 3722:  Called meson_src_compile
 *   environment, line 2586:  Called eninja '-C' '/var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7-build'
 *   environment, line 1022:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=app-misc/font-manager-0.7.7::overlay'`,
 * the complete build log and the output of `emerge -pqv '=app-misc/font-manager-0.7.7::overlay'`.
 * The complete build log is located at '/var/log/portage/build/app-misc/font-manager-0.7.7:20200213-104239.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/app-misc/font-manager-0.7.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-misc/font-manager-0.7.7/temp/environment'.
 * Working directory: '/var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7'
 * S: '/var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7'
```

Review of log indicated that meson could not locate `vapigen`. From log file:
```
FAILED: lib/common/FontManager-0.7.7.vapi 
/usr/bin/vapigen-0.46 --quiet --library=FontManager-0.7.7 --directory=/var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7-build/lib/common --vapidir=/var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7-build/lib/common --vapidir=/var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7-build/lib/unicode --metadatadir=/var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7-build/lib/common --pkg=glib-2.0 --pkg=gio-2.0 --pkg=gdk-3.0 --pkg=gtk+-3.0 --pkg=json-glib-1.0 --pkg=libxml-2.0 --pkg=sqlite3 --pkg=Unicode-0.7.7 --metadatadir=/var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7/lib/common /var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7-build/lib/common/FontManager-0.7.7.gir /var/tmp/portage/app-misc/font-manager-0.7.7/work/font-manager-0.7.7/lib/common/FontManager-custom.vala
```

I could "manually" build from source repositories completely and without error. It was only using the ebuild that I encountered a problem.

**How to Reproduce**
Issue presents always when executing emerge against ebuild.

**Expected behavior**
clean run

**Actual behavior**
Emerge aborted with error messages shown above.

**Additional context**
In vala.eclass, vala version 0.42 is explicitly masked out. Commentary indicates that this version has bugs. Would recommend changing `VALA_MIN_API_VERSION=0.42` to 0.44.

To work around problem, I reviewed other ebuilds that involve valac/vapigen. These ebuilds contain the line `VALA_USE_DEPEND="vapigen"`. Once I inserted this line into the ebuild file, emerge successfully completed.

**Comment by scottfurry** [comment]
Note...
I have two versions of vala libs installed on system (slotted packages): 0.44 and 0.46.
I suspect bug presents itself  if there is more than one version installed due to other package dependencies.

**Comment by PF4Public** [comment]
Thank you very much for searching for and providing a solution.
Feel free to close this issue if that commit solves it for you.

**Comment by scottfurry** [comment]
We have a winner \o/.
Thank you.
