### ISSUE TITLE
www-client/cromite-119.0.6045.105: ${FILESDIR}/00LIN-Build-fixes.patch interferes with cromite patch set

### ISSUE THREAD

**Issue by skunk73** [PF4Public/gentoo-overlay#273]
cromite-0db4890cec236dc44384f400f99b5c7efecaca3c/build/patches/ungoogled-chromium-no-special-hosts-domains.patch tries to remove lines commented out by ${FILESDIR}/00LIN-Build-fixes.patch, therefore it fails to apply
for me the easiest way to fix this was editing the latter leaving it like this:
```
--- a/chrome/browser/BUILD.gn
+++ b/chrome/browser/BUILD.gn
@@ -134,6 +134,7 @@
     "//build:chromeos_buildflags",
     "//chrome/common:buildflags",
     "//media:media_buildflags",
+    "//services/network/public/mojom",
   ]
 }
```

**Comment by PF4Public** [comment]
What do you mean? Is it not?

**Comment by skunk73** [comment]
ops, sorry for the noise...
i'm noticing right now that ${FILESDIR}/00LIN-Build-fixes.patch was already updated in your tree

**Comment by PF4Public** [comment]
@skunk73 are you still copying my ebuild into your local overlay, uncomment that line? That's awkward, I can uncomment it here for the greater good.

**Comment by skunk73** [comment]
no, i did it just while trying to fix the issue with the ffmpeg patch.
i emerge cromite from your tree without modifying the ebuild, chrome_crashpad_handler lives as an orphan from previous installation...
