### ISSUE TITLE
www-client/ungoogled-chromium-119.0.6045.123_p1 web.whatsapp.com broken with uazo-bromite USE flag

### ISSUE THREAD

**Issue by V10lator** [PF4Public/gentoo-overlay#275]
When you're logged in already it endlessly loads the messages in both diretions, so you can neither send nor receive any messages.
When you're not logged in it endlessly loads the QR code needed to login, so you can't login to begin with.

The same website works just fine without the uazo-bromite USE flag as well as from full blown Cromite.

https://web.whatsapp.com

**Comment by PF4Public** [comment]
Have you enabled JIT?

**Comment by V10lator** [comment]
@PF4Public Thanks for the fast response. Yes, JIT is enabled (I enabled all the site-specific restrictions from the popdown menu on the left side of the URL bar for testing).

**Comment by PF4Public** [comment]
Is there anything in developer tools/console? Have you changed fingerprinting flags? As far as I remember they work in opposite directions in ungoogled-chromium and cromite. I mean enabled in one case means disabled in another case.

> full blown Cromite

From my overlay or on Windows/Android from upstream?

**Comment by V10lator** [comment]
> Is there anything in developer tools/console?

Yes, `no native wasm support detected` and `Uncaught ReferenceError: WebAssembly is not defined`. Both I can't see in Cromite.
![image](https://github.com/PF4Public/gentoo-overlay/assets/1312422/ae07b205-8da8-457e-9a4c-2534d8253400)


> From my overlay or on Windows/Android from upstream?

Windows upstream.

> Also please try reproducing this with empty profile.

Done: Same issue.

**Comment by V10lator** [comment]
> There is also a weird logic behind it, which uazo refuses to fix :D

Do you have any more infos on that? Like how to toggle it correctly?

**Comment by V10lator** [comment]
Found the solution at https://github.com/macchrome/winchrome/issues/119#issuecomment-1777220290

Still weird that it worked on a clean Cromite installation on Windows after toggling JIT but anyway, closing this as it seems to work as expected?

**Comment by V10lator** [comment]
Sorry but I just double-checked and on Windows upstream Cromite that linked workaround is NOT needed, so maybe this is indeed a bug in your patchset?

See, on Cromite it's enough to toggle the switch, no need for a custom rule:
![image](https://github.com/PF4Public/gentoo-overlay/assets/1312422/7464fe4c-d39c-4336-af4b-5aa99b3727bd)

**Comment by V10lator** [comment]
> Although this might be the consequence of ungoogling

Doesn't the official Cromite build for Android/Windows build on top of ungoogled-chromium patches, too? I might be wrong but I think it's more of:
> Perhaps there is a piece of code missing since I do not include all patches. Need to find the missing one.

> It pleases me to know that it is of use to someone :)

Bet there are more people using this extensively. It's simple to find and use for gentoo users. Really thanks for the work you put into maintaining the ebuilds. :)
Also thanks a lot for investigating into the issue even after I closed it.

**Comment by PF4Public** [comment]
Turns out, for this to work, one needs `SitePerProcess` and `StrictOriginIsolation` enabled. Former is enabled by default on desktop, but not the latter. @V10lator You can try: `--enable-features=StrictOriginIsolation` and check if that fixes this issue for you. Alternatively you can build .159, which now should have this fixed.
