### ISSUE TITLE
www-client/ungoogled-chromium/ungoogled-chromium-119.0.6045.159_p1: build fails with dev-libs/libxml2-2.12.0

### ISSUE THREAD

**Issue by kcning** [PF4Public/gentoo-overlay#279]
Similar to https://bugs.gentoo.org/917526
This is a upstream issue. Reporting it just for others' info.

**Comment by thubble** [comment]
This MR fixes it: https://chromium-review.googlesource.com/c/chromium/src/+/4985186

Just need the first 2 files (in `third_party/blink/`) though - the rest are updating the local copy of libxml itself which isn't relevant since we're using system.

**Comment by PF4Public** [comment]
@thubble Would you be able to submit PR with the patch?
