### ISSUE TITLE
www-client/ungoogled-chromium: rebase disable-bluez.patch for 119

### ISSUE THREAD

**Issue by apprehensions** [PF4Public/gentoo-overlay#283]
thanks

**Comment by PF4Public** [comment]
Please do not ignore issue template and provide **all** of the requested information **immediately** when filling an issue. **Full build log** is of highest importance even if one may think otherwise.

Here is the issue template text once again for your reference in case you missed it:

> What were you trying to accomplish? What didn't function as expected?
> Please provide any relevant information including **the full build log**. Please **don't use external services** for that. If you have some unusual setup in your system please also mention this.
> And don't forget to edit the title.
