### ISSUE TITLE
Provide ffmpeg-6.x patched to work with Chromium

### ISSUE THREAD

**Issue by UnclePain** [PF4Public/gentoo-overlay#286]
As you mentioned in #260, current Chromium builds only work with ffmpeg versions that provide av_stream_get_first_dts. For users like me that prefer enabling system-ffmpeg, I’d like to have ffmpeg ebuilds that have this patched in.

**Comment by PF4Public** [comment]
I'd reeeeeeeeeeally appreciate it if you used [the search](https://github.com/PF4Public/gentoo-overlay/issues?q=is%3Aissue+av_stream_get_first_dts) first (second time already btw). You could come to https://github.com/PF4Public/gentoo-overlay/issues/260 without me needing to point you there.

PS: If you do this again and I happen to have no time to spare, I'll close your issue immediately without any explanations, so don't feel offended, I'm very limited in time right now, sorry.

**Comment by blackteahamburger** [comment]
See also https://bugs.gentoo.org/831487.
