### ISSUE TITLE
www-client/ungoogled-chromium: 120.0.6099.216_p1

### ISSUE THREAD

**Issue by ProtoGitCell** [PF4Public/gentoo-overlay#287]
I renamed ungoogled-chromium-120.0.6099.62_p1.ebuild to ungoogled-chromium-120.0.6099.129_p1.ebuild and added the ~amd64 keyword, but it didn't compile. But after doing change after change it finally did. Just in case someone finds it helpful, I upload the patch here. Perhaps it provides a useful starting point. I have only tested basic functionality of patched ungoogled-chromium, though.

In any case, thank you for all the work on ungoogled-chromium and the Gentoo overlay! It is very much appreciated!

[chromium-120-libstdc++.txt](https://github.com/PF4Public/gentoo-overlay/files/13747020/chromium-120-libstdc%2B%2B.txt)

**Comment by PF4Public** [comment]
Initially I thought you supplied a diff for ebuild, but now I realise that you actually patched Chromium to make it work with libstdc++. Is it really so? Does it work for you without issues?

**Comment by VPaulV** [comment]
Thank you for the patch, I confirm it seems to be working like a charm. I had no success with building 119.0.6045.199_p1, went to the github and was lucky enough finding your work.

 Is it possible somehow integrate the patch in a way that it will work for further versions as well?

**Comment by PF4Public** [comment]
> Is it possible somehow integrate the patch in a way that it will work for further versions as well?

One could use /etc/portage/patches as a temporary solution

**Comment by PF4Public** [comment]
I just noticed that [Debian seemingly had solved these issues](https://salsa.debian.org/chromium-team/chromium/-/blob/master/debian/patches/fixes/absl-optional.patch). I guess, I'll give that patch a try when I get back to updating ebuilds.

**Comment by PF4Public** [comment]
Feel free to submit a PR with your patch and your ebuild (masked for now), but don't delete existing ones.

**Comment by PF4Public** [comment]
`chromium-120-libstdc++.patch` was merged. Thanks @ProtoGitCell
