### ISSUE TITLE
www-client/ungoogled-chromium-121.0.6167.85_p1: fails with: hkdf.h:25:6: error: no template named 'vector' in namespace 'std'

### ISSUE THREAD

**Issue by crabbedhaloablution** [PF4Public/gentoo-overlay#294]
Emerging www-client/ungoogled-chromium-121.0.6167.85_p1 fails with the following error message:

> FAILED: obj/crypto/crypto/hkdf.o 
x86_64-pc-linux-gnu-clang++ -MMD -MF obj/crypto/crypto/hkdf.o.d -DCRYPTO_IMPLEMENTATION -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE
_OZONE=1 -DOFFICIAL_BUILD -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE6
4_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNO
TATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DBASE_USE_PERFETTO_C
LIENT_LIBRARY=1 -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfe
tto -Igen/shim_headers/zlib_shim -Igen/shim_headers/jsoncpp_shim -Igen/shim_headers/libevent_shim -Igen/shim_headers/icui18n_shim 
-Igen/shim_headers/icuuc_shim -I../../base/allocator/partition_allocator/src -Igen/base/allocator/partition_allocator/src -I../../
third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -Wimplicit-fall
through -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psab
i -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-built
ins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -Wno-invalid-offsetof -Wno-vla-extension -Wno-thread-safety-ref
erence-return -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -fno-unwind-tables -fno-a
synchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -flto=thin -fsplit-lto-unit -fwhole-program-vta
bles -no-canonical-prefixes -ftrivial-auto-var-init=pattern -fno-omit-frame-pointer -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/nss -I/usr/include/nspr -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/lib64/libffi/include -DPROTOBUF_ALLOW_DEPRECATED=1 -std=c++20 -Wno-trigraphs -gsimple-template-names -fno-exceptions -fno-rtti -fvisibility-inlines-hidden  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=native -mtune=native -ggdb -O2 -pipe -ggdb0 -Wno-unknown-warning-option -Wno-builtin-macro-redefined -c ../../crypto/hkdf.cc -o obj/crypto/crypto/hkdf.o
In file included from ../../crypto/hkdf.cc:5:
../../crypto/hkdf.h:25:6: error: no template named 'vector' in namespace 'std'
   25 | std::vector<uint8_t> HkdfSha256(base::span<const uint8_t> secret,
      | ~~~~~^
1 error generated.

Full logs:
[www-client:ungoogled-chromium-121.0.6167.85_p1:20240127-004918.log](https://github.com/PF4Public/gentoo-overlay/files/14072044/www-client.ungoogled-chromium-121.0.6167.85_p1.20240127-004918.log)

Emerge --info:
[emergeinfo.txt](https://github.com/PF4Public/gentoo-overlay/files/14072047/emergeinfo.txt)

**Comment by PF4Public** [comment]
Try this patch: https://chromium-review.googlesource.com/c/chromium/src/+/5138462
