### ISSUE TITLE
www-client/unoogle-chromium-bin crashes at sturtup because "missing libpulse"

### ISSUE THREAD

**Issue by pony-montana** [PF4Public/gentoo-overlay#304]
Hi, I have installed it on a system that uses alsa + apulse (no pulseaudio, no pipewire) and a wlroots based window manager (wayland + xwayland for compatibility available).

After the installation it doesn't start and claim that libpulse is missing (and that's true, libpulse is actually missing, but I would expect it isn't a problem; there is apulse exposed to ensure compatibility).

The ungoogle-chromium portable linux official binary works well on same machine with same confing

Thanks :)

**Comment by PF4Public** [comment]
Have you tried to solve this issue yourself? What have you attempted to do in order to fix it? I'm afraid I won't be able to help you with this as I have no system where I could try and reproduce this ussue. It should just work though: https://forums.gentoo.org/viewtopic-t-1165734.html

**Comment by pony-montana** [comment]
Hi, issue solved by linking /usr/lib64/apulse/libpulse.so.0 to /usr/lib64/libpulse.so.0

Doing ldd chrome it say it cant find libpulse.so.0.
I noted that it was searching libraries in /usr/lib64/ so I linked here and it worked :)

**Comment by PF4Public** [comment]
As you can see from the forum thread I linked, apulse should create `/usr/lib64/libpulse.so.0`. Maybe your version is outdated?

**Comment by pony-montana** [comment]
Its the last stable version, I think the problem could be that I have a no-multilib setup with no abi32 comptibility (?) 
I dont know.

**Comment by PF4Public** [comment]
Maybe. But good, that it works now.
