### ISSUE TITLE
www-client/ungoogled-chromium-121.0.6167.184_p1: no audio

### ISSUE THREAD

**Issue by baconsalad** [PF4Public/gentoo-overlay#305]
After updating from 119 to 121 I have lost audio on most things. Soundcloud just fails to play anything with no obvious reason why. Even went to steam to try their videos and no audio. Here's the one for tekken 8 which given what a popular game it is you would expect the trailer to work properly https://cdn.cloudflare.steamstatic.com/steam/apps/256997587/movie480_vp9.webm

`X clang cromite custom-cflags hevc nvidia official optimize-thinlto optimize-webui proprietary-codecs pulseaudio qt5 system-crc32c system-double-conversion system-ffmpeg system-harfbuzz system-icu system-libevent system-libusb system-openh264 system-openjpeg system-png system-zstd thinlto vaapi -bluetooth -cfi -convert-dict -cups -debug -enable-driver -gtk4 -hangouts -headless -kerberos -libcxx -override-data-dir -pax-kernel -pgo -qt6 -screencast (-selinux) -system-abseil-cpp -system-av1 -system-brotli -system-jsoncpp -system-libvpx -system-re2 -system-snappy -system-woff2 -wayland -widevine`

**Comment by PF4Public** [comment]
Try `-system-ffmpeg`

**Comment by baconsalad** [comment]
Yep that fixed it... Here's my ffmpeg flags should something stand out

`[ebuild   R    ] media-video/ffmpeg-6.1.1-r3:0/58.60.60::gentoo  USE="X alsa amr bluray bzip2 chromium cuda dav1d encode fdk gmp gnutls gpl iconv ieee1394 jpeg2k lcms libass libdrm librtmp mp3 network nvenc openal opengl openh264 openssl opus pic postproc pulseaudio sdl svg svt-av1 theora threads truetype v4l vdpau vidstab vmaf vorbis vpx vulkan webp x264 x265 xvid zimg zlib -amf -amrenc (-appkit) -bs2b -cdio -chromaprint -codec2 -cpudetection -debug -doc -flite -fontconfig -frei0r -fribidi -gcrypt -glslang -gme -gsm -hardcoded-tables -iec61883 -jack -jpegxl -kvazaar -ladspa -libaom -libaribb24 -libcaca -libilbc -libplacebo -libsoxr -libtesseract -libv4l -libxml2 -lv2 -lzma (-mipsdspr1) (-mipsdspr2) (-mipsfpu) -modplug -opencl -oss -qsv -rav1e -rubberband -samba -shaderc -snappy -sndio -soc -speex -srt -ssh -static-libs -test -twolame -vaapi -verify-sig -zeromq -zvbi" ABI_X86="32 (64) (-x32)" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext sse sse2 sse3 sse4_1 sse4_2 ssse3 -3dnow -3dnowext -fma4 -xop" FFTOOLS="aviocat cws2fws ffescape ffeval ffhash fourcc2pixfmt graph2dot ismindex pktdumper qt-faststart sidxindex trasher" 0 KiB`

and i was using 0000-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch as well.

**Comment by PF4Public** [comment]
To be honest I haven't yet debugged it, but Arch also has the same issue, they've commented out ffmpeg:
>#[ffmpeg]=ffmpeg # YouTube playback stopped working in Chromium 120

**Comment by PF4Public** [comment]
See also https://github.com/PF4Public/gentoo-overlay/issues/303#issuecomment-1949056533

**Comment by PF4Public** [comment]
See https://github.com/PF4Public/gentoo-overlay/issues/303#issuecomment-1949494058
