### ISSUE TITLE
wayland support in www-client/ungoogled-chromium-bin

### ISSUE THREAD

**Issue by pony-montana** [PF4Public/gentoo-overlay#306]
I cant set the flag "ozone-preferred-platform" to "wayland". 
Is ungoogled-chromium-bin built without wayland support or is this an issue that need to be investigated with my setup?
As today, a lot of linux distros ship with wayland-first setup with gnome and kde that seems finally ready for the switch.
The official portable-linux ungoogled-chromium binary start to X11 by default, but is possible to set ozone-preferred-platform to wayland.

Probably lot of user that uses ungoogled-chromium-bin in a wayland setup dont experiment any breakage, because the compatibility with "legacy" X11 is still available in pretty every desktop environment. 
I think that, as now, defaulting on X11 is still a good idea for compatibility reasons, but it's also important to build wayland compatibility.
There are a lot of benefit in security (render-process isolation) and performance using wayland.

**Comment by pony-montana** [comment]
Hi, searched in ths issues and seems that this feature is not planned. I'm closing this issue, if for any reason something is changed fell free to reopen it :)

**Comment by PF4Public** [comment]
If anyone could build ungoogled chromium that has support for both, but does not hard-depend on wayland, that could be doable. The thing is that I don't use Wayland and therefore cannot verify.
