### ISSUE TITLE
www-client/ungoogled-chromium-121.0.6167.184_p1 build fails with useflag system-ffmpeg enabled 

### ISSUE THREAD

**Issue by stallonen** [PF4Public/gentoo-overlay#309]
Here is the last 300 lines of the buildlog
[ucbuildlog.txt](https://github.com/PF4Public/gentoo-overlay/files/14393680/ucbuildlog.txt)

The `useflags` I have enabled are as follows 

`www-client/ungoogled-chromium-121.0.6167.184_p1  USE="clang hevc official optimize-thinlto pgo proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-libevent system-libusb system-openh264 system-png system-zstd thinlto vaapi wayland -X -bluetooth -cfi -convert-dict -cromite -cups -custom-cflags -debug -enable-driver -gtk4 -hangouts -headless -kerberos -libcxx -nvidia -optimize-webui -override-data-dir -pax-kernel -qt5 -qt6 -screencast (-selinux) -system-abseil-cpp -system-av1 -system-brotli -system-crc32c -system-double-conversion -system-jsoncpp -system-libvpx -system-openjpeg -system-re2 -system-snappy -system-woff2 -widevine" L10N="af am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW" `

I get this message at the beginning of the build, when applying patches 
`You need to expose "av_stream_get_first_dts" in ffmpeg via user patch`

**Comment by stallonen** [comment]
I think [this](https://github.com/bashonly/ffmpeg-bashonly/blob/master/01-add-av_stream_get_first_dts-for-chromium.patch) patch might fix the issue. I will test it and report here.

**Comment by stallonen** [comment]
I have applied the patch `patch` to `ffmpeg` by placing it on `/etc/portage/patches` and running `ebuild ffmpeg-6.0.1-r2.ebuild clean prepare` and then emerging ffmpeg. 

I emerged ungoogled-chromium, and it was successful. 

I am new to this, how do I submit a pull request to include this patch in future ffmpeg releases? Should I submit this pull-request to the ffmpeg ebuild repo or here?

**Comment by PF4Public** [comment]
> I am new to this, how do I submit a pull request to include this patch in future ffmpeg releases? Should I submit this pull-request to the ffmpeg ebuild repo or here?

Short answer: no. It is a known issue. In a nutshell Gentoo neither provides support for system-ffmpeg in Chromium nor patches ffmpeg to make it compatible. I decided to keep support of system-ffmpeg in ungoogled-chromium. 

PS: it would be great if you [searched existing issues first](https://github.com/PF4Public/gentoo-overlay/issues?q=is%3Aissue+av_stream_get_first_dts)
