### ISSUE TITLE
ungoogled-chromium 80.* does not compile

### ISSUE THREAD

**Issue by Sixardyh** [PF4Public/gentoo-overlay#31]
**Description**
I cannot compile ungoogled-chromium on my machine since versions 80.*

**How to Reproduce**
Emerge ungoogled-chromium from your overlay

**Expected behavior**
The package compiles and installs

**Actual behavior**
The package fails at compile phase:
```
ERROR: www-client/ungoogled-chromium-80.0.3987.149_p2::pf4public failed (compile phase):
   ninja -v -j8 -l0 -C out/Release chrome failed
 
 Call stack:
     ebuild.sh, line  125:  Called src_compile
   environment, line 4526:  Called eninja '-C' 'out/Release' 'chrome'
   environment, line 2062:  Called die 
 The specific snippet of code:
       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 
 If you need support, post the output of `emerge --info '=www-client/ungoogled-chromium-80.0.3987.149_p2::pf4public'`,
 the complete build log and the output of `emerge -pqv '=www-client/ungoogled-chromium-80.0.3987.149_p2::pf4public'`.
 
 MemTotal:       14286888 kB
 SwapTotal:       5242876 kB
 
 The complete build log is located at '/var/tmp/notmpfs/portage/www-client/ungoogled-chromium-80.0.3987.149_p2/temp/build.log'.
 The ebuild environment file is located at '/var/tmp/notmpfs/portage/www-client/ungoogled-chromium-80.0.3987.149_p2/temp/environment'.
 Working directory: '/var/tmp/notmpfs/portage/www-client/ungoogled-chromium-80.0.3987.149_p2/work/chromium-80.0.3987.149'
 S: '/var/tmp/notmpfs/portage/www-client/ungoogled-chromium-80.0.3987.149_p2/work/chromium-80.0.3987.149'
```

**Logs**
- [emerge --info output](https://covid19.framadrop.org/r/2LfQHvoa0R#eBp1ZuqPW503dcJmMkzTdjjDsEXmVf5bHIP4DFkjlIk=)
- [Build log](https://covid19.framadrop.org/r/4epap21tQB#BSHdhj/cmO7cfeWPPU/9s7wcWmhVojpkcYxcMMrHRpY=)

**Comment by PF4Public** [comment]
Something is overriding `AR`. Did you do it yourself?

It should be [llvm-ar](https://github.com/PF4Public/gentoo-overlay/blob/b7e192d6e4d20c205176a1197ad258c861e26e3e/www-client/ungoogled-chromium/ungoogled-chromium-80.0.3987.163_p1.ebuild#L542), but is gcc-ar instead.

Or… should it also have CHOST prefix?…

**Comment by Sixardyh** [comment]
> Something is overriding `AR`. Did you do it yourself?

Nope, I didn't do any manual override so I have no idea why it's using gcc-ar instead of llvm-ar... Maybe something is wrong with my use flags?

**Comment by PF4Public** [comment]
Given that your logs have no "Enforcing the use of clang due to USE=clang ...", `tc-is-clang` returns true. Have you enabled clang by default?

**Comment by Sixardyh** [comment]
I have enabled the clang use flag and it shows in the use flags in the build logs. Weird because in the logs we see
```
Building with following compiler settings:
CC = "clang"
CXX = "clang++"
AR = "x86_64-pc-linux-gnu-ar"
NM = "x86_64-pc-linux-gnu-nm"
RANLIB = ""
  CFLAGS = "-march=native -pipe -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
CXXFLAGS = "-march=native -pipe -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
CPPFLAGS = " -D__DATE__= -D__TIME__= -D__TIMESTAMP__="
LDFLAGS = "-Wl,--as-needed -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=8"
```

I guess a workaround would be to make a package.env entry with llvm binutils instead of the gcc ones

**Comment by Sixardyh** [comment]
After checking my package.env entries, I found out that for some reason I had a useclang.conf file for ungoogled-chromium which set clang as the compiler but didn't set llvm-binutils. As this might be the source of the issue I will try building properly once I fix this...

**Comment by PF4Public** [comment]
> useclang.conf file for ungoogled-chromium

That's exactly what is happening! Your useclang.conf changes CC and because of that `tc-is-clang` returns true and the conditional, that should fix AR, isn't followed, hence this build failure.
