### ISSUE TITLE
www-client/ungoogled-chromium-121.0.6167.184_p1 build fails throwing error [1mclang frontend command failed with exit code 134]

### ISSUE THREAD

**Issue by stallonen** [PF4Public/gentoo-overlay#310]
Here are my use flags for chromium 

`www-client/ungoogled-chromium-121.0.6167.184_p1  USE="clang hevc official optimize-thinlto pgo proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-libevent system-libusb system-openh264 system-png system-zstd thinlto vaapi wayland -X -bluetooth -cfi -convert-dict -cromite -cups -custom-cflags -debug -enable-driver -gtk4 -hangouts -headless -kerberos -libcxx -nvidia -optimize-webui -override-data-dir -pax-kernel -qt5 -qt6 -screencast (-selinux) -system-abseil-cpp -system-av1 -system-brotli -system-crc32c -system-double-conversion -system-jsoncpp -system-libvpx -system-openjpeg -system-re2 -system-snappy -system-woff2 -widevine" L10N="af am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW" `

Here are the first 100 lines of the build log [ucbuildlog121ffmpegpatched.txt](https://github.com/PF4Public/gentoo-overlay/files/14395585/ucbuildlog121ffmpegpatched.txt) 

The error asked to attached these files 
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
```
Preprocessed source(s) and associated run script(s) are located at:[0m
x86_64-pc-linux-gnu-clang++: [0;1;36mnote: [0mdiagnostic msg: /var/tmp/portage/www-client/ungoogled-chromium-121.0.6167.184_p1/temp/cfxjse_engine-a630e5.cpp[0m
x86_64-pc-linux-gnu-clang++: [0;1;36mnote: [0mdiagnostic msg: /var/tmp/portage/www-client/ungoogled-chromium-121.0.6167.184_p1/temp/cfxjse_engine-a630e5.sh[0m
x86_64-pc-linux-gnu-clang++: [0;1;36mnote: [0mdiagnostic msg: 
```
Here are the files 
[cfxjse_engine-a630e5.cpp.txt](https://github.com/PF4Public/gentoo-overlay/files/14395597/cfxjse_engine-a630e5.cpp.txt)
[cfxjse_engine-a630e5.sh.txt](https://github.com/PF4Public/gentoo-overlay/files/14395598/cfxjse_engine-a630e5.sh.txt)

**Comment by JohnFlowerful** [comment]
This is a clang issue. Try rebuild clang with USE="-debug" and resume the ungoogled-chromium build.

**Comment by stallonen** [comment]
Thank you. Disabling `debug` USE flag solved the issue. 

Can you tell me how did you figure out it was a clang issue, and removing the debug use flag will help?

**Comment by JohnFlowerful** [comment]
The crash report says to report it to the llvm issue tracker on github, hence it being a clang issue :)
There is already a report for this.

I ran into it when building electron: https://github.com/PF4Public/gentoo-overlay/issues/302#issuecomment-1944519170. 
The initial error is ```Assertion `!T->isDependentType() && "should not see dependent types here"' failed.```
Reading a bit led me to the fact that assertions are enabled by the debug useflag in the clang ebuilds. That and the fact that it's one of the differences between the clang-17 and clang-18 ebuilds.
