### ISSUE TITLE
ungoogled-chromium-122.0.6261.69_p1 fails while applying  fmpeg-nb_coded_side_data.patch

### ISSUE THREAD

**Issue by stallonen** [PF4Public/gentoo-overlay#311]
I am emerging ungoogled-chromium-122 and it currently fails to build throwing the error 

`patch -p1 -R failed with /var/tmp/portage/www-client/ungoogled-chromium-122.0.6261.69_p1/files/ffmpeg-nb_coded_side_data.patch`

Here are my use flags 

`www-client/ungoogled-chromium-122.0.6261.69_p1::pf4public [121.0.6167.184_p1::pf4public] USE="clang hevc official optimize-thinlto pgo proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-libevent system-libusb system-openh264 system-png system-zstd thinlto vaapi wayland -X -bluetooth -cfi -convert-dict -cromite -cups -custom-cflags -debug -enable-driver -gtk4 -hangouts -headless -kerberos -libcxx -nvidia -optimize-webui -override-data-dir -pax-kernel -qt5 -qt6 -screencast (-selinux) -system-abseil-cpp -system-av1 -system-brotli -system-crc32c -system-double-conversion -system-jsoncpp -system-libvpx -system-openjpeg -system-re2 -system-snappy -system-woff2 -widevine" L10N="af am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW"`

Here is the buildlog
[ungoogledch122.txt](https://github.com/PF4Public/gentoo-overlay/files/14396081/ungoogledch122.txt)

**Comment by PF4Public** [comment]
I've just added another patch, please give it a try
