### ISSUE TITLE
www-client/ungoogled-chromium-122.0.6261.111_p1: fails to build

### ISSUE THREAD

**Issue by salfter** [PF4Public/gentoo-overlay#319]
I've tried building this with the same settings as v121, and with all of the system-* USE flags disabled.  It still won't build.  I don't know if it's a packaging issue or an upstream issue.

USE flags used: X bluetooth clang cups official proprietary-codecs pulseaudio qt5 screencast wayland -cfi -convert-dict -cromite -custom-cflags -debug -enable-driver -gtk4 -hangouts -headless -hevc -kerberos -libcxx -nvidia -optimize-thinlto -optimize-webui -override-data-dir -pax-kernel -pgo -qt6 (-selinux) -system-abseil-cpp -system-av1 -system-brotli -system-crc32c -system-double-conversion -system-ffmpeg -system-harfbuzz -system-icu -system-jsoncpp -system-libevent -system-libusb -system-libvpx -system-openh264 -system-openjpeg -system-png -system-re2 -system-snappy -system-woff2 -system-zstd -thinlto -vaapi -widevine" L10N="-af -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -ur -vi -zh-CN -zh-TW

[emerge-info.txt](https://github.com/PF4Public/gentoo-overlay/files/14544516/emerge-info.txt)
[build.log.gz](https://github.com/PF4Public/gentoo-overlay/files/14544515/build.log.gz)

**Comment by PF4Public** [comment]
Are you building with clang-17?

**Comment by PF4Public** [comment]
~Are you building with clang-17? It must be a clang bug, but I cannot find a fix in chromium issue tracker.~

Oh wait, are you still with gcc-12? Try upgrading to gcc-13, gcc-12 might be to blame here.

**Comment by baconsalad** [comment]
Had gcc-12 fail with the same error. Upgraded to gcc-13 and it compiled fine.

**Comment by salfter** [comment]
...and the build succeeded with gcc 13.  Thanks for the hint.
