### ISSUE TITLE
www-client/ungoogled-chromium unable to build with thinlto

### ISSUE THREAD

**Issue by 0xC0ncord** [PF4Public/gentoo-overlay#32]
**Description**
On my system I'm not able to build `ungoogled-chromium-81.0.4044.113_p1` with the `thinlto` USE flag.

**How to Reproduce**
1. Enable the `thinlto` USE flag for `www-client/ungoogled-chromium`
2. Do `emerge ungoogled-chromium`

**Expected behavior**
The build succeeds with the `thinlto` USE flag.

**Actual behavior**
The build fails very early.

**Logs**
`emerge -pqv`
```
[ebuild  N    ] www-client/ungoogled-chromium-81.0.4044.113_p1  USE="cfi clang optimize-thinlto optimize-webui proprietary-codecs pulseaudio (selinux) system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libvpx system-openh264 tcmalloc thinlto vaapi -closure-compile -convert-dict -cups -custom-cflags -enable-driver -gnome -hangouts -kerberos -suid -system-openjpeg -widevine" L10N="-am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python2_7 python3_6 -python3_7 -python3_8"
```
[`emerge --info`](https://hastebin.com/nayayijomu.sql)

[Build log](https://hastebin.com/ilucelehop.php)

**Additional context**
N/A

**Comment by perfect7gentleman** [comment]
the problem in on your side
```
www-client/ungoogled-chromium-81.0.4044.113_p1::pf4public was built with the following:
USE="clang convert-dict cups custom-cflags optimize-thinlto optimize-webui proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libvpx system-openh264 system-openjpeg tcmalloc thinlto vaapi -cfi -closure-compile -enable-driver -gnome -hangouts -kerberos (-selinux) -suid -widevine" L10N="ru -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python2_7 python3_8 -python3_6 -python3_7"
CFLAGS="-march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
CXXFLAGS="-march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++ -flax-vector-conversions=all -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch parallel-install pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--strip-debug -Wl,--discard-all -Wl,--thinlto-jobs=9 -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -s -march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++ -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=9"
```

**Comment by 0xC0ncord** [comment]
> the problem in on your side
> 
> ```
> www-client/ungoogled-chromium-81.0.4044.113_p1::pf4public was built with the following:
> USE="clang convert-dict cups custom-cflags optimize-thinlto optimize-webui proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libvpx system-openh264 system-openjpeg tcmalloc thinlto vaapi -cfi -closure-compile -enable-driver -gnome -hangouts -kerberos (-selinux) -suid -widevine" L10N="ru -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python2_7 python3_8 -python3_6 -python3_7"
> CFLAGS="-march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
> CXXFLAGS="-march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++ -flax-vector-conversions=all -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
> FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch parallel-install pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
> LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--strip-debug -Wl,--discard-all -Wl,--thinlto-jobs=9 -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -s -march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++ -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=9"
> ```

Thank you! I'll play around with these flags and see if I can resolve it. I'll update with the solution if I can find it.

**Comment by 0xC0ncord** [comment]
Seems like the build fails if `thinlto` is enabled but `convert-dict` is not.

**Comment by PF4Public** [comment]
Your issue is very weird. 
* Did you get anything interesting in dmesg?
* Have you tried running failed python script by hand?
* Have you tried compiling without `cfi`?

It is also curios, how strip-flags removes `thinlto` — that's also weird.

**Comment by 0xC0ncord** [comment]
So far I've set up a different `env` for `ungoogled-chromium` with the following contents (using the information provided by @perfect7gentleman):
```
CC="clang"
CXX="clang++"
CFLAGS="-march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
CXXFLAGS="-march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++ -flax-vector-conversions=all -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--strip-debug -Wl,--discard-all -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -s -march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
```
I am now using the following USE flags:
```
www-client/ungoogled-chromium clang convert-dict cups custom-cflags optimize-thinlto optimize-webui proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libvpx system-openh264 system-openjpeg tcmalloc thinlto vaapi -cfi -closure-compile -enable-driver -gnome -hangouts -kerberos -suid -widevine
```

The build now fails at a point much further than before, although I still could not figure out the root cause of the original build failure. This one appears to be different:
`emerge -pqv`
```
[ebuild  N    ] www-client/ungoogled-chromium-81.0.4044.113_p1  USE="clang convert-dict cups custom-cflags optimize-thinlto optimize-webui proprietary-codecs pulseaudio (selinux) system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libvpx system-openh264 system-openjpeg tcmalloc thinlto vaapi -cfi -closure-compile -enable-driver -gnome -hangouts -kerberos -suid -widevine" L10N="-am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python2_7 python3_6 -python3_7 -python3_8"
```
[`emerge --info`](https://hastebin.com/buvonoyuku.sql)
[Build log](https://files.catbox.moe/tygejy.log)

> Your issue is very weird.
> 
>     * Did you get anything interesting in dmesg?
> 
>     * Have you tried running failed python script by hand?
> 
>     * Have you tried compiling without `cfi`?
> 
> 
> It is also curios, how strip-flags removes `thinlto` — that's also weird.

- Nothing in `dmesg`
- The build process makes it much further than before, but running the Python command that failed results in the same failure
- Yes. The last build I attempted was without `cfi`

**Comment by PF4Public** [comment]
Which versions of lld, llvm, clang (all installed versions if multiple) does your system have?

**Comment by 0xC0ncord** [comment]
> Which versions of lld, llvm, clang (all installed versions if multiple) does your system have?

`lld-10.0.0`
`llvm-10.0.0, llvm-9.0.1`
`clang-10.0.0, clang-9.0.1`

**Comment by perfect7gentleman** [comment]
> So far I've set up a different env for ungoogled-chromium with the following contents (using the information provided by @perfect7gentleman):

You shouldn't use those switches if you don't know what you're doing. But certainly you are not.
First, you should have LLVM/Clang toolchain built with these switches.
Second, some of UGC deps should be build in the same manner.
Thirdly, your environment seems to be badly configured.

**Comment by PF4Public** [comment]
> `lld-10.0.0`
> `llvm-10.0.0, llvm-9.0.1`
> `clang-10.0.0, clang-9.0.1`

You shouldn't be having differing versions at once, see #4

**Comment by 0xC0ncord** [comment]
> You shouldn't use those switches if you don't know what you're doing. But certainly you are not.
> First, you should have LLVM/Clang toolchain built with these switches.
> Second, some of UGC deps should be build in the same manner.
> Thirdly, your environment seems to be badly configured.

> You shouldn't be having differing versions all at once, see #4

Okay, let's backtrack. I've dropped the `custom-cflags` USE flag, unmerged both `llvm-9.0.1` and `clang-9.0.1`, and rebuilt the toolchain (twice, to ensure it was built with itself) for good measure. So far, I've been able to build `ungoogled-chromium` with `thinlto`, but only without the `cfi` USE flag. The error that results is the same as in the OP when this is the case. Strangely, running the python script by hand at this point prints no errors, but *does* exit with code 252.

Are there any known issues with enabling `cfi` at this time, or am I missing something else?

`emerge -pqv`
```
[ebuild   R   ] www-client/ungoogled-chromium-81.0.4044.113_p1  USE="cfi* clang convert-dict cups optimize-thinlto optimize-webui proprietary-codecs pulseaudio (selinux) system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libvpx system-openh264 system-openjpeg tcmalloc thinlto vaapi -closure-compile -custom-cflags -enable-driver -gnome -hangouts -kerberos -suid -widevine" L10N="-am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python2_7 python3_6 -python3_7 -python3_8"
```

[`emerge --info`](https://pastebin.com/spvY26kD)
[Build log](https://files.catbox.moe/72i70i.log)

**Comment by PF4Public** [comment]
>The error that results is the same as in the OP when this is the case.

I don't get it. Have you managed to compile it successfully without `cfi` or not?

I've just tried enabling `cfi` and it indeed fails. Like you say, running python script, gives exit code 252. I did dig further and it turns out that this python script just runs the compiled `./torque` binary. Running it I've got exit code `132` and `Illegal instruction` exception. With this in `dmesg`: `traps: torque[30860] trap invalid opcode`. You should be also getting the same! So, supposedly this binary wasn't properly compiled for some reason due to `cfi`. Unfortunately, have no time to investigate further.

>Are there any known issues with enabling cfi at this time, or am I missing something else?

It just occured to me, that I've already encountered something similar and indeed! See [here](https://gitlab.com/chaoslab/chaoslab-overlay/issues/73).

In the end, I'm afraid, there is not much I can do, except for adding a warning in ebuild.

**Comment by 0xC0ncord** [comment]
> I don't get it. Have you managed to compile it successfully without `cfi` or not?

Sorry for the terrible wording. I *can not* compile it with `cfi`. Without `cfi`, it is successful.

No idea why I'm not getting anything interesting in `dmesg` when the build fails. I will have to dig further as well here.

>It just occured to me, that I've already encountered something similar and indeed! See here.
>In the end, I'm afraid, there is not much I can do, except for adding a warning in ebuild.

So there must be something wrong upstream or so with CFI. Fair enough. If that's the case, I'll close this as my original issue has been resolved. Thank you both for your help.

**Comment by PF4Public** [comment]
>So there must be something wrong upstream or so with CFI.

Many things could interfere, it could take a lot of time and effort finding the culprit unfortunately.

**Comment by leandrolnh** [comment]
To build with cfi one should make sure that is using lld linker.
My suggestion:
Replace this `myconf_gn+=" use_lld=false"` with this 
`myconf_gn+=" use_lld=$(usex thinlto true false)"`

**Comment by PF4Public** [comment]
@leandrolnh There is already one:
https://github.com/PF4Public/gentoo-overlay/blob/b733732eeac93bfa1b35d0b8d9bfaa0d9514a347/www-client/ungoogled-chromium/ungoogled-chromium-83.0.4103.106_p1.ebuild#L802
