### ISSUE TITLE
dev-util/electron-29.1.1: chromium-118-ffmpeg.patch fails to apply

### ISSUE THREAD

**Issue by SpookySkeletons** [PF4Public/gentoo-overlay#320]
```
 * Applying chromium-118-ffmpeg.patch ...
patching file media/filters/ffmpeg_demuxer.cc
Hunk #1 FAILED at 398.
Hunk #2 succeeded at 464 (offset 3 lines).
1 out of 2 hunks FAILED -- saving rejects to file media/filters/ffmpeg_demuxer.cc.rej
```

USE="X bluetooth clang proprietary-codecs pulseaudio screencast system-crc32c system-ffmpeg system-openh264 system-openjpeg system-png system-woff2 system-zstd ungoogled vaapi wayland -cups -custom-cflags -debug -dev-dependencies -gtk4 -hangouts -hevc -kerberos -libcxx% -nvidia -optimize-thinlto -optimize-webui -pax-kernel -pgo (-selinux) -system-abseil-cpp -system-av1 -system-brotli -system-double-conversion -system-harfbuzz -system-icu -system-jsoncpp -system-libevent -system-libusb -system-libvpx -system-re2 -system-snappy -thinlto"

**Comment by PF4Public** [comment]
What is your ffmpeg version?

**Comment by SpookySkeletons** [comment]
4.4 it seems!
I may have to trim my USE in other places to get this to upgrade, thankyou, this might be a quick close :sweat_smile:

**Comment by PF4Public** [comment]
#285 #272 :D
