### ISSUE TITLE
remove dependency on libpulse in ungoogled-chromium-bin

### ISSUE THREAD

**Issue by ndk-** [PF4Public/gentoo-overlay#322]
Hi,

It seems the latest version of ungoogled-chromium-bin is now dependent on libpulse.
It causes all kinds of issues on my system as I do not use libpulse.
Using apulse causes videos to play with an uneven speed (i.e. sound is breaking up and video is tearing up).
I downloaded the latest portable version from here: https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/122.0.6261.128-1 and it does not require libpulse, neither it has any issues with playing videos.

For the reference:
Kernel: Linux 6.8.1-gentoo-x86_64
CPU/Platform: Ryzen 5900x/x570
Audio: FiiO K5 Pro

I would be more than happy to provide any additional details, if necessary.

I would love to continue using this overlay repo!

**Comment by PF4Public** [comment]
I wonder if it would make it unusable on systems with pulseaduio?

**Comment by ndk-** [comment]
why would it? Pulse still uses alsa under the hood. And there is pulse alsa sink if someone needs it.

**Comment by PF4Public** [comment]
I'll get back to it later :)

**Comment by PF4Public** [comment]
@ndk- I've built [i686 without linking it to libpulse specifically](https://github.com/PF4Public/ungoogled-chromium-bin/releases/tag/124.0.6367.155) and indeed it is absent from ldd output.
Would you be able to test whether it works for you? x86_64 hasn't finished yet unfortunately.

**Comment by ndk-** [comment]
just tried to test it. Unfortunately, it randomly crashes on my PC now. That being said, we can close this one as I just started using the native gentoo package. It takes forever, but it is what it is.
