### ISSUE TITLE
net-im/element-desktop-1.11.63: electron v28 removed

### ISSUE THREAD

**Issue by baconsalad** [PF4Public/gentoo-overlay#325]
I see electron v28 is removed from the ebuild, but the ebuild still defaults to `ELECTRON_SLOT_DEFAULT="28"`. So question is what is the preferred version now?

**Comment by PF4Public** [comment]
Normally I update default version in accordance with upstream `package.json`, except when I'm very limited in time :)

Indeed it should be 29 for `element-desktop-1.11.63`. I'll correct that soon.
