### ISSUE TITLE
dev-util/electron: fix_adapt_exclusive_access_for_electron_needs patch fails

### ISSUE THREAD

**Issue by joecool1029** [PF4Public/gentoo-overlay#327]
Currently this patch fails on 29.2.0 and 29.1.6.

**Comment by PF4Public** [comment]
@joecool1029 [Workflow succeeded](https://github.com/PF4Public/gentoo-overlay/actions/runs/8583088169), you can give it a try.

**Comment by joecool1029** [comment]
Patches all successfully apply now. Thanks!
