### ISSUE TITLE
www-client/ungoogled-chromium-122.0.6261.111_p1: would it be possible to add a system-XNNPACK use flag?

### ISSUE THREAD

**Issue by psychedup** [PF4Public/gentoo-overlay#329]
I'm trying to build ungoogled chromium on a Raspberry Pi 4B. This used to work just fine until a few months ago.

Now I keep running into a bug where the build system keeps failing while trying to build XNNPACK, because it's trying to compile with CPU extensions (dotprod) that don't exist on my CPU.

I had a similar issue previously with libaom but was able to get around it by enabling the system-av1 USE flag.

Today I discovered that sci-libs/XNNPACK exists in portage and I was able to build and install it, so I was wondering if it would be possible to add a "system-XNNPACK" USE flag that would allow ungoogled-chromium to use that instead of building it as part of chromium.

I tried copying the ebuild and making the changes myself but it is too complicated to figure out what I'd need to do.

**Comment by PF4Public** [comment]
> because it's trying to compile with CPU extensions (dotprod) that don't exist on my CPU

Have you attempted building without `-march=native`?

**Comment by psychedup** [comment]
yes I'm using:

```
COMMON_FLAGS="-march=armv8-a+crc+simd -mtune=cortex-A72 -ftree-vectorize -O2 -pipe -fomit-frame-pointer"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
```

I think I was able to get past this issue, by adding this in the src_configure section:

`myconf_gn+=" build_tflite_with_xnnpack=false build_webnn_with_xnnpack=false"`

I think this avoids trying to build or use XNNPACK at all, which is probably fine for me. Still testing though (takes a while on my slow machines).

**Comment by PF4Public** [comment]
Perhaps it might be possible to use the existing substitution infrastructure in Chromium, but I don't see significant benefits in doing so.
