### ISSUE TITLE
www-client/ungoogled-chromium: rename debian_buster to debian

### ISSUE THREAD

**Issue by leandrolnh** [PF4Public/gentoo-overlay#35]
**Is your feature request related to a problem? Please describe.**
Eloston renamed `debian_buster` to `debian`:
https://github.com/Eloston/ungoogled-chromium/commit/d8ce06aa6fe4a99a8372d30377076aa890705238

**Describe the solution you'd like**
Follow accordingly and replace
```
local ugc_unneeded=(
# GN bootstrap
extra/debian_buster/gn/parallel
)
```
with
```
local ugc_unneeded=(
# GN bootstrap
extra/debian/gn/parallel
)
```

**Comment by PF4Public** [comment]
Good catch!
