### ISSUE TITLE
www-client/ungoogled-chromium-128.0.6613.84_p1: compile fails due to WTF::String issues

### ISSUE THREAD

**Issue by UnclePain** [PF4Public/gentoo-overlay#368]
When trying to build said version, the following error appears for two files:

```
../../third_party/blink/renderer/platform/fonts/font_face_creation_params.h:113:32: error: no member named 'data' in 'WTF::String'
  113 |                     Filename().data(),
      |                     ~~~~~~~~~~ ^
../../third_party/blink/renderer/platform/fonts/font_face_creation_params.h:137:15: error: no viable overloaded '='
  137 |     filename_ = filename;
      |     ~~~~~~~~~ ^ ~~~~~~~~
```
The affected compile calls are for:
- obj/third_party/blink/renderer/bindings/core/v8/v8/v8_layout_callback.o
- obj/third_party/blink/renderer/bindings/core/v8/v8/v8_intrinsic_sizes_callback.o

See the attached [build.log.gz](https://github.com/user-attachments/files/16729997/build.log.gz) for detailed info.

Though I suspected it comes from one of my many enabled system-xxx USE flags, none of them seem to be related to v8 stuff (to me).

**Comment by PF4Public** [comment]
No, I used `WTF::String` as a temporary solution for the crash that is caused by garbage collection. I'll see if it is still needed.

**Comment by PF4Public** [comment]
No, I used WTF::String as a temporary solution for the crash that is caused by garbage collection.

Please try adding `Utf8().` before `.data()` and let me know whether it solves it.

**Comment by UnclePain** [comment]
Yes, this solves the first error. The second one (also in font_face_creation_params.h) about the = overload remains, but I figured it out by myself: SetFilename needs to be adjusted because the = operator doesn’t allow implicit conversion.
```
  void SetFilename(std::string& filename) {
#if defined(ADDRESS_SANITIZER)
    *filename_ = WTF::String(filename);
#else
    filename_ = WTF::String(filename);
#endif
  }
```
Since I have zero knowledge about C++, please take this with a grain of salt, but so far it compiles…

**Comment by PF4Public** [comment]
I'll bump the patch then

**Comment by UnclePain** [comment]
Ok, now I have another problem:
```
../../third_party/blink/renderer/platform/fonts/web_font_typeface_factory.cc:80:10: error: use of undeclared identifier 'SkTypeface_Make_Fontations'
   80 |   return SkTypeface_Make_Fontations(std::move(stream), SkFontArguments());
      |          ^
```

**Comment by PF4Public** [comment]
Yep, I just hit it too. I'll run it with -k0 to uncover other problems.

**Comment by PF4Public** [comment]
Builds and runs now
