### ISSUE TITLE
www-client/ungoogled-chromium-bin: no wayland ozone platform support?

### ISSUE THREAD

**Issue by repomansez** [PF4Public/gentoo-overlay#369]
I don't seem to have the option to enable the wayland ozone platform, I wonder if it's something on my end or if your builds deliberately disable it.

**Comment by PF4Public** [comment]
Please do search through [existing issues](https://github.com/PF4Public/gentoo-overlay/issues?q=is%3Aissue+wayland+ungoogled-chromium-bin+) before filing a new one.
