### ISSUE TITLE
www-client/ungoogled-chromium failed to apply vdpau patch

### ISSUE THREAD

**Issue by RefinedAnarchy** [PF4Public/gentoo-overlay#37]
**Description**
ungoogled-chromium version 84 can't apply vdpau

**How to Reproduce**
1. Enable vdpau USE flag
2. Emerge the package
3. Package fails to apply the patch

**Expected behavior**
Ebuild would apply the patch and emerge the package

**Actual behavior**
Patch doesn't apply and build fails

**Logs**
[build.log](https://github.com/PF4Public/gentoo-overlay/files/4945836/build.log)

**Comment by PF4Public** [comment]
I've updated vdpau patch, please test, if it works now

**Comment by r7l** [comment]
Was running into the same issue and can confirm your new patch to be working. Just finished rebuilding it successfully. Thanks allot for you work!

**Comment by PF4Public** [comment]
I have established [testing](https://github.com/PF4Public/gentoo-overlay/actions/runs/286799081). Although this won't outright prevent such issues from happening, I do hope being able to catch them early on.
