### ISSUE TITLE
app-misc/font-manager: google-fonts require webkit-gtk 6

### ISSUE THREAD

**Issue by Outtay** [PF4Public/gentoo-overlay#378]
Currently, the font-manager only checks to see if >=webkit-gtk-2.24 is installed, but that doesn't seem to be enough. When I tired to emerge 0.9.0, I got the error that webkit-gtk 6 was not found. 
I'd guess that the dependency should require >=webkit-gtk-2.24 specifically of webkit-gtk 6

**Comment by PF4Public** [comment]
Should ebuild be checking for slot 6 then?

**Comment by Outtay** [comment]
Yeah I think so

**Comment by PF4Public** [comment]
I hope this should do
