### ISSUE TITLE
www-client/cromite-129: build fails due libjxl

### ISSUE THREAD

**Issue by skunk73** [PF4Public/gentoo-overlay#385]
doesn't matter if USE flag system-libjxl is enabled or not compilation stops with the same error:
`FAILED: obj/third_party/blink/renderer/platform/image-decoders/image_decoders/jxl_image_decoder.o 
x86_64-pc-linux-gnu-clang++ -MD -MF obj/third_party/blink/renderer/platform/image-decoders/image_decoders/jxl_image_decoder.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -
DUSE_OZONE=1 -DOFFICIAL_BUILD -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_G
NU_SOURCE -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -D_GLIBCXX_ASSERTIONS=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_PLATFORM_IMPLEMENT
ATION=1 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG
_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_DISABLE_LEGACY_INIT_DECODERS -DSK_DISABLE_LEGACY_BACKEND_TEXTURE_FUNCS -DSK_DISABLE_
LEGACY_TEXTURE_INFO_FUNCS -DSK_DISABLE_LEGACY_BACKEND_SEMAPHORE_FUNCS -DSK_DISABLE_LEGACY_GRAPHITE_IMAGES -DSK_DISABLE_LEGACY_DAWN_TEXTURE_INFO_FUNCS -DSK_DISABLE_LEG
ACY_DAWN_BACKEND_TEXTURE_FUNCS -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_GANESH -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driv
er_bug_workaround_autogen.h\" -DSK_GL -DSK_VULKAN=1 -DSK_GRAPHITE -DSK_DAWN -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_WAYLAND_KHR -DCHROMIUM -DLIBYUV_DISABLE_NEON -
DLIBYUV_DISABLE_SVE -DLIBYUV_DISABLE_SME -DLIBYUV_DISABLE_LSX -DLIBYUV_DISABLE_LASX -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DU_IMPORT=U_EXPORT
 -DWTF_USE_WEBAUDIO_PFFFT=1 -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DUSE_SYSTEM_ZLIB=1 -DV8_ARRAY_BUFFER_INTERNAL_FIELD_COUNT=0 -DV8_ARRAY_BUFFER_VIEW_INTERNAL_FIELD_COUNT=0 -DV8_PROMISE_INTERNAL_FIELD_COUNT=0 -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_ENABLE_SANDBOX -DV8_DEPRECATION_WARNINGS -DV8_USE_PERFETTO -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_LINUX -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERATION -DCPPGC_POINTER_COMPRESSION -DCPPGC_ENABLE_LARGER_CAGE -DCPPGC_SLIM_WRITE_BARRIER -DUSE_SYSTEM_LIBJPEG -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -DWEBRTC_ENABLE_AVX2 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_X11 -DWEBRTC_USE_PIPEWIRE -DWEBRTC_USE_GIO -DLOGGING_INSIDE_WEBRTC -DLEVELDB_PLATFORM_CHROMIUM=1 -DAVIF_ENABLE_EXPERIMENTAL_GAIN_MAP -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/jsoncpp_shim -Igen/shim_headers/double_conversion_shim -Igen/shim_headers/libevent_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/skia -Igen/third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan/include -I../../third_party/vulkan-headers/src/include -I../../third_party/wayland/src/src -I../../third_party/wayland/include/src -Igen/third_party/dawn/include -I../../third_party/dawn/include -Igen/shim_headers/libpng_shim -Igen/shim_headers/libwebp_shim -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/quiche/common/platform/default -I../../net/third_party/quiche/src -Igen/shim_headers/zstd_headers -I../../third_party/libyuv/include -Igen/shim_headers/opus_shim -Igen/shim_headers/ffmpeg_shim -Igen/shim_headers/openh264_shim -Igen/shim_headers/crc32c_shim -I../../third_party/khronos -I../../gpu -Igen/shim_headers/flac_shim -Igen/shim_headers/snappy_shim -I../../base/allocator/partition_allocator/src -Igen/base/allocator/partition_allocator/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/ipcz/include -I../../third_party/ced/src -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/linux -I../../third_party/crashpad/crashpad/compat/non_win -I../../v8/include -Igen/net/third_party/quiche/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/libwebm/source -I../../third_party/mesa_headers -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/libaom/source/libaom -I../../third_party/libaom/source/config/linux/x64 -I../../third_party/libjxl/src/lib/include -I../../third_party/libjxl/gen_headers -Igen/third_party/libjxl -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-cast-function-type -Wno-deprecated-this-capture -Wno-invalid-offsetof -Wno-vla-extension -Wno-thread-safety-reference-return -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector-strong -fwrapv -ftrivial-auto-var-init=zero -Wno-unused-command-line-argument -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fno-sized-deallocation -flto=thin -fno-split-lto-unit -mllvm -inlinehint-threshold=360 -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-math-errno -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -isystem/usr/lib64/libffi/include -isystem/usr/include/glib-2.0 -isystem/usr/lib64/glib-2.0/include -Wno-redundant-parens -Wno-redundant-parens -DPROTOBUF_ALLOW_DEPRECATED=1 -isystem/usr/include/nss -isystem/usr/include/nspr -isystem/usr/include/libpng16 -Wenum-compare-conditional -Wno-c++11-narrowing-const-reference -Wno-missing-template-arg-list-after-template-kw -Wno-dangling-assignment-gsl -std=c++20 -Wno-trigraphs -gsimple-template-names -fno-exceptions -fno-rtti -fvisibility-inlines-hidden  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=znver2 -mtune=znver3 -pipe -U_GLIBCXX_ASSERTIONS -Wno-unknown-warning-option -Wno-builtin-macro-redefined -c ../../third_party/blink/renderer/platform/image-decoders/jxl/jxl_image_decoder.cc -o obj/third_party/blink/renderer/platform/image-decoders/image_decoders/jxl_image_decoder.o
In file included from <built-in>:496:
<command line>:16:9: warning: '_LIBCPP_HARDENING_MODE' macro redefined [-Wmacro-redefined]
   16 | #define _LIBCPP_HARDENING_MODE _LIBCPP_HARDENING_MODE_NONE
      |         ^
<command line>:3:9: note: previous definition is here
    3 | #define _LIBCPP_HARDENING_MODE _LIBCPP_HARDENING_MODE_EXTENSIVE
      |         ^
../../third_party/blink/renderer/platform/image-decoders/jxl/jxl_image_decoder.cc:66:7: error: no matching constructor for initialization of 'ImageDecoder'
   66 |     : ImageDecoder(alpha_option,
      |       ^            ~~~~~~~~~~~~~
   67 |                    high_bit_depth_decoding_option,
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |                    color_behavior,
      |                    ~~~~~~~~~~~~~~~
   69 |                    max_decoded_bytes) {
      |                    ~~~~~~~~~~~~~~~~~
../../third_party/blink/renderer/platform/image-decoders/image_decoder.h:455:3: note: candidate constructor not viable: requires 5 arguments, but 4 were provided
  455 |   ImageDecoder(AlphaOption alpha_option,
      |   ^            ~~~~~~~~~~~~~~~~~~~~~~~~~
  456 |                HighBitDepthDecodingOption high_bit_depth_decoding_option,
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  457 |                ColorBehavior color_behavior,
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  458 |                cc::AuxImage aux_image,
      |                ~~~~~~~~~~~~~~~~~~~~~~~
  459 |                wtf_size_t max_decoded_bytes);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/blink/renderer/platform/image-decoders/image_decoder.h:191:3: note: candidate constructor not viable: requires 1 argument, but 4 were provided
  191 |   ImageDecoder(const ImageDecoder&) = delete;
      |   ^            ~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.`

**Comment by Kawanaao** [comment]
This error is related to enabling this flag, you can disable it

https://github.com/PF4Public/gentoo-overlay/blob/ea185a29fd9050c936910efb182809c2fb303370/www-client/cromite/cromite-130.0.6723.58.ebuild#L1284

Also @PF4Public cromite recommends not to use jxl

https://github.com/uazo/cromite/issues/1552

**Comment by skunk73** [comment]
thank you, it builds fine now with enable_jxl_decoder disabled...
