### ISSUE TITLE
ungoogled-chromium-bin-129.0.6668.89 ebuild - unable to download tarball

### ISSUE THREAD

**Issue by ericghara** [PF4Public/gentoo-overlay#386]
When trying to emerge `ungoogled-chromium-bin-129.0.6668.89` the actual release tarball is not found

```
>>> Downloading 'https://github.com/PF4Public/ungoogled-chromium-bin/releases/download/129.0.6668.89/x86-64.tar.bz2'
--2024-10-23 14:50:04--  https://github.com/PF4Public/ungoogled-chromium-bin/releases/download/129.0.6668.89/x86-64.tar.bz2
Resolving github.com... 140.82.116.4
Connecting to github.com|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-23 14:50:04 ERROR 404: Not Found.
```

I took a look at the ungoogled-chromium-bin repo and it doesn't look like the release exists.  I think either there is a typo in the ebuild or perhaps there was an error uploading the release to github?

Thanks.

**Comment by PF4Public** [comment]
Sorry, I removed it accidentally. Soon comes 130, so I hope it is not a big problem.
