### ISSUE TITLE
net-im/element-web-1.11.84: Error: Can't resolve '@sentry/browser'

### ISSUE THREAD

**Issue by joecool1029** [PF4Public/gentoo-overlay#389]
previous release 1.11.83 works fine on same configuration. Build log attached:
[build.log.gz](https://github.com/user-attachments/files/17650881/build.log.gz)

**Comment by PF4Public** [comment]
Yep, it failed in [CI](https://github.com/PF4Public/gentoo-overlay/actions/runs/11686115641) too, I just wasn't around to look into it and bot was doing its thing unsupervised :-/

**Comment by PF4Public** [comment]
.85 fails the same way :(

**Comment by joecool1029** [comment]
worse yet .83 just whitescreens on electron-32. I was running it without problems on electron-28 but that's long reached EoL.

**Comment by baconsalad** [comment]
in 1.11.84 they added a new "sentry" to package.json
[https://github.com/element-hq/element-web/blob/v1.11.84/package.json](url)

so the fix is to change
`sed -i '/sentry/d' "${WORKDIR}/${P}/package.json" || die`
to
`sed -i '/sentry\/webpack-plugin/d' "${WORKDIR}/${P}/package.json" || die`

**Comment by PF4Public** [comment]
@baconsalad That is right! I should make that sed more specific at the first place. Thanks!
