### ISSUE TITLE
app-editors/vscode: line 3156: ulimit: open files: cannot modify limit: Operation not permitted

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [PF4Public/gentoo-overlay#390]
I was trying to emerge app-editors/vscode-1.93.1::pf4public but it stalled for a long time, when I took a look at the logs, I noticed there was an error related to ulimit. So I then tried to build by using the ebuild command and it seems to have failed because the ulimit wasn't set correctly, here's the full logs:

[ebuild_logs.txt](https://github.com/user-attachments/files/17651392/ebuild_logs.txt)

I'm using gentoo with openrc, I'm not using systemd.

p.s.:
I was also wondering if you planned to update the vscode ebuild to 1.94.2 and 1.95.1

**Comment by PF4Public** [comment]
> the ulimit wasn't set correctly

Correct, that is an issue I ~have no idea how to fix~ didn't fix. The simplest solutions is indeed to manually alter the ulimit.



>I was also wondering if you planned to update the vscode ebuild to 1.94.2 and 1.95.1

If you were monitoring this repo, you might've noticed me mentioning my limited internet access and computing power available, which makes some activities really difficult. No time estimates for now, sorry. You could've also noticed https://github.com/PF4Public/gentoo-overlay/issues/377. Fortunately @Kawanaao took the initiative and working on it here: https://github.com/PF4Public/gentoo-overlay/pull/384

> but it's stuck on that since two hours

Is your hardware OK? Any OOMs in dmesg? That step shouldn't take that long. Have you tried restarting the build?

**Comment by PF4Public** [comment]
Which version of electron are you using for the build?

**Comment by PF4Public** [comment]
You'll have to provide more information than that without me requesting it from you bit by bit. I won't be able to help you otherwise. If you really want to find the culprit, you'll have to provide _everything you have_ without me trying to guess it.

Good candidates were: your USE flags for `vscode` and `electron`, _full_ build.log as it is generated by portage in temp folder, `emerge --info` might be valuable, are you building electron from this overlay or are you using something else. Anything could help, I just cannot guess what exactly.

**Comment by PF4Public** [comment]
Hmm, I just don't see anything suspicious. Try building with `temp-fix`.

**Comment by PF4Public** [comment]
Does it work though? :D If it does, I'd be tending to mark this issue as resolved

**Comment by PF4Public** [comment]
I meant if vscode itself works

**Comment by PF4Public** [comment]
I'm still not in the mood of playing the guessing game :-/

https://github.com/PF4Public/gentoo-overlay/issues/372

**Comment by PF4Public** [comment]
> Do you think it would be doable to remove the telemetry code of Code-OSS completely through a patch instead of just disabling it by default?

https://github.com/PF4Public/gentoo-overlay/blob/02bb24fd3e415b642db3804d0aca21b12c704a90/app-editors/vscode/metadata.xml#L36
