### ISSUE TITLE
www-client/ungoogled-chromium-bin-130.0.6723.58 [x86]: doexe failed: chrome does not exist

### ISSUE THREAD

**Issue by arbitrary-dev** [PF4Public/gentoo-overlay#392]
```
!!! doexe: ./usr/lib/chromium-browser/chrome does not exist
```

**Comment by arbitrary-dev** [comment]
As I understood, noone is providing x86 binaries these days. So I'd suggest to remove `x86` keyword from the ebuild then, to not mislead people.

**Comment by arbitrary-dev** [comment]
So are you planing to build x86 in the future or just leave ebuild broken to trick people into false hopes? 😄

**Comment by PF4Public** [comment]
Are you planing to build x86 using the existing ebuilds instead of blaming me of not doing that for you?

**Comment by arbitrary-dev** [comment]
I'm too mentally retarded to build a binary. That's why I expected `*-bin` package to have one already available.

**Comment by PF4Public** [comment]
> That's why I expected `*-bin` package to have one already available.

I could build one without pgo, I think 🤔
