### ISSUE TITLE
What is the difference between thinlto and optimize-thinlto USE flags?

### ISSUE THREAD

**Issue by RefinedAnarchy** [PF4Public/gentoo-overlay#41]
The description of the flags aren't clear. Just in case if they're pretty much the same thing, why not intergrate both into one USE flag: thinlto?

**Comment by PF4Public** [comment]
They are not the same thing. 
`thinlto` improves linking time upon compiler LTO feature.
`optimize-thinlto` adds additional optimizations upon `thinlto` feature, but it further lengthens compile time. 
All of this is written in description, isn't it?

**Comment by RefinedAnarchy** [comment]
according to 'equery u ungoogled-chromium'
thinlto                  : Build with ThinLTO support. LTO (Link Time Optimization) achieves better
                              runtime performance through whole-program analysis and cross-module
                              optimization (highly recommended).
optimize-thinlto    : Whether to enable ThinLTO optimizations. Turning ThinLTO optimizations on
                              can substantially increase link time and binary size, but they generally
                              also make binaries a fair bit faster.

I understands what you're saying but the descriptions aren't very self-explainatory

**Comment by PF4Public** [comment]
I didn't change the descriptions from the time I have overtaken this ebuild from Ian, but now that you've mentioned it, they are indeed not very clear. 
Do you have any suggestions?

**Comment by logrusx** [comment]
One is in regards to LTO and the other to ThinLTO specifically. There's a difference, I suggest looking up what the Thin version is. I will not try to describe it here because I'm afraid I'd say something stupid :-)

**Comment by logrusx** [comment]
To my knowledge, ThinLTO is just the mechanism that allows faster and scalable optimization. The compiler emits additional LLVM bytecode, which is not like regular monolithic LTO which then can be used to enable faster and more scalable optimization.

According to clang documentation, don't mind it's for v13, this part of the doc hasn't changed:

> ThinLTO compilation is a new type of LTO that is both scalable and incremental. LTO (Link Time Optimization) achieves better runtime performance through whole-program analysis and cross-module optimization. However, monolithic LTO implements this by merging all input into a single module, which is not scalable in time or memory, and also prevents fast incremental compiles.

> In ThinLTO mode, as with regular LTO, clang emits LLVM bitcode after the compile phase. The ThinLTO bitcode is augmented with a compact summary of the module. During the link step, only the summaries are read and merged into a combined summary index, which includes an index of function locations for later cross-module function importing. Fast and efficient whole-program analysis is then performed on the combined summary index.

So thinlto enable that mode and optimize-thinlto enables the optimization based on it. That's why the later depends on the former.

Regards,
Georgi

**Comment by PF4Public** [comment]
I will close this issue for the time being as no better alternative wording was suggested. If at a later time someone has further suggestions, feel free to share them with us here.
