### ISSUE TITLE
Ungoogled-chromium emerged with the hangouts flag can't stream desktop (in hangouts or meet)

### ISSUE THREAD

**Issue by toniz4** [PF4Public/gentoo-overlay#42]
**Description**
Building ungoogled chromium with the "hangouts" use flag don't make possible to use features as screen sharing (as the use flag description says: "Enable support for Google Hangouts features such as screen sharing")

**How to Reproduce**
1. Try to screen share on hangouts or meet
2. see a message saying that this browser does not support screen sharing

**Expected behavior**
Screen sharing being possible

**Actual behavior**
When i try to screen share, i get a message that is not possible

**Comment by PF4Public** [comment]
Do you have anything in terminal/logs?

**Comment by toniz4** [comment]
> Do you have anything in terminal/logs?

on the terminal i'm getting no output, and where can i access the logs?

**Comment by PF4Public** [comment]
Could your issue be related to Eloston/ungoogled-chromium/#1137?

**Comment by PF4Public** [comment]
Could your issue be related to Eloston/ungoogled-chromium#1137?

**Comment by toniz4** [comment]
Probably no, i tried enabling chrome://flags#cast-media-route-provider and it made no difference.

**Comment by PF4Public** [comment]
According to Eloston/ungoogled-chromium#601 `enable_hangout_services_extension` should be enabled, but if you enable `hangouts` it should be. I have no other ideas as to what makes it non-functional. You could probably file a bug upstream in Eloston/ungoogled-chromium. That repository has a bigger audience, someone could help.

**Comment by toniz4** [comment]
In arch it didn't work, by what i understand, the aur build disables the enable_hangout_services_extension. But with the hangouts flag i expected it to work. there is any way to enable ` myconf_gn+=" enable_mdns=false" ` via a use flag? I'm new to gentoo.

And btw, thank you for the attention, and thanks for maintaining this package

**Comment by PF4Public** [comment]
You may use `EXTRA_GN` for that. See the example here: https://forums.gentoo.org/viewtopic-t-1074724-start-0.html

The last setting should override prior one, so, having `EXTRA_GN="enable_mdns=true"` should change it.

**Comment by toniz4** [comment]
Thanks for the help! Gonna try that Friday, it takes me a whole 24 hrs to compile it on my toaster.

**Comment by PF4Public** [comment]
Let me know if you find a flag/flags, which prevent this from functioning, so that I may fix this in the ebuild.

**Comment by Eloston** [comment]
Might be related: https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/176#issue-688676522

I think Service Discovery and mDNS might be the wrong components to look into because they're made for local network P2P connections, but I might be wrong.

**Comment by toniz4** [comment]
I'm compiling it with those flags today.

ps. the jumbo build does't work anymore?

**Comment by PF4Public** [comment]
> ps. the jumbo build does't work anymore?

Unfortunately, Google dropped jumbo support, see here: Eloston/ungoogled-chromium#928

**Comment by toniz4** [comment]
Unfortunately, due to compile times, i decided to not run ungoogled chromium anymore, so i can't test that. Sorry.

**Comment by PF4Public** [comment]
With ccache they could be lowered to a manageable value, but anyway, I'll keep this bug open in case anyone wishes to identify the cause.

**Comment by PF4Public** [comment]
It came recently to my attention, that hangouts does actually function, so I'll assume this issue as self-fixed, but if anyone still (or in the future) has issues with it, feel free to reopen it.
