### ISSUE TITLE
www-client/ungoogled-chromium-85.0.4183.83_p1: vaapi issues

### ISSUE THREAD

**Issue by PF4Public** [PF4Public/gentoo-overlay#43]
There are 2 issues with `vaapi` in newer 85 chromium:
1. ❌ `vaapi` requires libvpx-1.9, and it is hard-wired to builtin libvpx
    * vaapi code under `media/gpu/vaapi/` needs to be patched to use system libvpx instead
    * they might fix this in following revisions/versions *{insert bug reference if found}*
2. ✔️ Even if compiled with builtin libvpx, it says `WARNING:vaapi_wrapper.cc(416)] : VAAPI video acceleration not available for angle` and no hardware accelerated video in `chrome://gpu/` _Video Acceleration Information_ section
    * Arch user mentions, that *In version 86 chromium will be able to use vaapi with angle enabled.*
    * 💡 `CHROMIUM_FLAGS="--use-gl=desktop"` restores hardware acceleration
    * 💡 `CHROMIUM_FLAGS="--use-gl=egl"` also restores hardware acceleration
    * ✔️ 86 indeed does not need "--use-gl" for hardware acceleration

**Comment by dagraver** [comment]
Is this still an issue? Using --use-gl=desktop on 85.0.4183.102 re-enables vaapi for h264, I don't have VP9-capable hardware, so I can't test that. The key part is ' --use-gl=desktop' without it it doesn't work. ' 

' --use-gl=egl' does *not* work for me, I'm using XFCE4 on X11.

For what it is worth, I have the following set in /etc/chromium/default : 
`CHROMIUM_FLAGS="--ignore-gpu-blocklist --ignore-gpu-blacklist --enable-zero-copy --enable-native-gpu-memory-buffers --disable-gpu-driver-bug-workarounds --enable-accelerated-video-decode --use-gl=desktop"`

**Comment by PF4Public** [comment]
> Is this still an issue?

The first one, which is marked with a cross, is still not solved.

**Comment by dagraver** [comment]
What are the advantages of using system-libvpx? Chromium from portage has system-libvpx masked since v58 something.

Afaik, libvpx is only used if vaapi fails.

**Comment by PF4Public** [comment]
> What are the advantages of using system-libvpx?

More code reuse; less compile times.


> Afaik, libvpx is only used if vaapi fails.

Some people might not be using `vaapi`. `vaapi` is also absent from mainline portage tree ;)

**Comment by dagraver** [comment]
Since libvpx comes bundled with chromium, it should not be an issue.

**Comment by PF4Public** [comment]
> Compared to the rest of the gigantic codebase, libvpx doesn't take that long to compile, tbh.

True, but Gentoo is about options, if someone sees the benefit, I won't be against.

Apart from that, I've linked these bugs in ebuilds so that anyone could immediately obtain the needed information on these issues to ease making informed decision on further actions: either mask 85 until these issues are solved, or disable `system-libvpx`
