### ISSUE TITLE
www-client/ungoogled-chromium-85.0.4183.83_p1: libvpx-1.7 support

### ISSUE THREAD

**Issue by PF4Public** [PF4Public/gentoo-overlay#45]
Chromium 85 uses some features, that are unavailable in libvpx-1.7
* Either it must be patched away
* Or support of libvpx-1.7 should be dropped
* I'm also curious as to what will Debian do about it

**Comment by dagraver** [comment]
Debian/Ubuntu uses bundled libvpx

**Comment by PF4Public** [comment]
Debian [uses system libvpx](https://salsa.debian.org/chromium-team/chromium/-/blob/master/debian/patches/system/vpx.patch) and their [libvpx is 1.7](https://salsa.debian.org/chromium-team/chromium/-/blob/master/debian/patches/buster/vpx17.patch)

**Comment by dagraver** [comment]
Yes, and they are also stuck at 84 for now, which has a couple of security vulnerabilities which aren't patched by the looks of it.
[](https://www.securityweek.com/chrome-85-released-20-security-fixes)

**Comment by PF4Public** [comment]
> Yes, and they are also stuck at 84 for now

> I'm also curious as to what will Debian do about it

**Comment by PF4Public** [comment]
Now that libvpx 1.9 is stable, there is no need to support 1.7
