### ISSUE TITLE
ungoogled-chromium-bin use pulseaudio or apulse?

### ISSUE THREAD

**Issue by mahdi1234** [PF4Public/gentoo-overlay#47]
Hi,

I wanted to try ungoogled-chromium-bin to get rid of chrome, but it hard requires media-sound/pulseaudio, though my system is using instead media-sound/apulse which chrome works fine with.

Do you think it would be possible to use apulse when it's already present?

cheers

**Comment by PF4Public** [comment]
Have you seen #46? I would be nice, if you could test it.

**Comment by mahdi1234** [comment]
@PF4Public thanks I'll report my findings in that issue and close this one.
