### ISSUE TITLE
Python 2* deps for www-client/ungoogled-chromium

### ISSUE THREAD

**Issue by arbitrary-dev** [PF4Public/gentoo-overlay#50]
Why Python 2* is still required for the build?

https://github.com/PF4Public/gentoo-overlay/blob/078a6fd269139cac348118f3962fffcc0fb7d490/www-client/ungoogled-chromium/ungoogled-chromium-85.0.4183.121_p1.ebuild#L47

**Comment by PF4Public** [comment]
Because [it is still required for the build](https://bugs.chromium.org/p/chromium/issues/detail?id=942720)

**Comment by zz64** [comment]
Hi, 
version 87.0.4280.66_p1 require python 2.7 ?
```
The following REQUIRED_USE flag constraints are unsatisfied:
    python_targets_python2_7
```
i don't have any more python 2.7 on my gentoo  :-(
```
cat /etc/portage/package.mask/python 
dev-lang/python:2.7
dev-lang/python:3.6
dev-lang/python:3.7
dev-lang/python:3.9
```
any idea how can unmask python 2.7 for ungoogled-chromium **only** ?

Thanks.

**Comment by PF4Public** [comment]
@zz64 As far as I know, you can unmask things system-wide, not per-package. You could however try to unmask python2, but allow only ungoogled-chromium to use it via 
```
*/* PYTHON_TARGETS: -python2_7 
www-client/ungoogled-chromium PYTHON_TARGETS: python2_7 
```

**Comment by perfect7gentleman** [comment]
```
any idea how can unmask python 2.7 for ungoogled-chromium only ?
```
It's not the way Gentoo works. You have remove Python-2.7 from masked package otherwise don't use packages which still require it.
Then add it to USE flags.

**Comment by zz64** [comment]
Thanks PF4Public.
Your support is always appreciated :+1:
