### ISSUE TITLE
ungoogled-chromium-bin is xz compressed, not bzip2 compressed

### ISSUE THREAD

**Issue by agates** [PF4Public/gentoo-overlay#51]
Emerging `www-client/ungoogled-chromium-bin-85.0.4183.121_p1` produces the following error:
`bzip2: /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.121_p1/distdir/ungoogled-chromium-bin-85.0.4183.121_p1-haswell.tar.bz2 is not a bzip2 file.`

Indeed, it is not a bzip2 file:
```
$ file ungoogled-chromium-bin-85.0.4183.121_p1-haswell.tar.bz2
ungoogled-chromium-bin-85.0.4183.121_p1-haswell.tar.bz2: XZ compressed data
```

Renaming it to `.tar.xz` allows `xz` to decompress it successfully.

**Comment by PF4Public** [comment]
Thanks for mentioning this, I'm aware if this issue, it will be fixed with 86 release.
As you can see, I've already fixed the extension: https://github.com/PF4Public/ungoogled-chromium-bin/releases/tag/86.0.4240.80-1

**Comment by PF4Public** [comment]
Recently I have implemented testing in this overlay in the hope of improving the quality of it. It did immediately pay off: it [became apparent](https://github.com/PF4Public/gentoo-overlay/runs/1203346162?check_suite_focus=true), that tar cannot extract an archive with a wrong extension (what was I hoping for :) ).

Now that the tests are [passing](https://github.com/PF4Public/gentoo-overlay/actions/runs/314863291), this issue should be solved, feel free to close it.

**Comment by agates** [comment]
Yes, it is working for me.  Thank you!
