### ISSUE TITLE
Package 'dev-util/electron-9.2.1' NOT merged due to file collisions

### ISSUE THREAD

**Issue by sedimentation-fault** [PF4Public/gentoo-overlay#54]
**Description**
>>> Installing (1 of 2) dev-util/electron-9.2.1::pf4public
 * checking 5010 files for package collisions
 99% done,    10 files remaining ...
100% done
 * This package will overwrite one or more files that may belong to other
 * packages (see list below). You can use a command such as `portageq
 * owners / <filename>` to identify the installed package that owns a
 * file. If portageq reports that only one package owns a file then do
 * NOT file a bug report. A bug report is only useful if it identifies at
 * least two or more packages that are known to install the same file(s).
 * If a collision occurs and you can not explain where the file came from
 * then you should simply ignore the collision since there is not enough
 * information to determine if a real problem exists. Please do NOT file
 * a bug report at https://bugs.gentoo.org/ unless you report exactly
 * which two packages install the same file(s). See
 * https://wiki.gentoo.org/wiki/Knowledge_Base:Blockers for tips on how
 * to solve the problem. And once again, please do NOT file a bug report
 * unless you have completely understood the above message.
 * 
 * Detected file collision(s):
 * 
 *      /usr/lib/debug/.build-id/09/71e724994107fcbb071eac56830a67149eb96e.debug
 *      /usr/lib/debug/.build-id/09/71e724994107fcbb071eac56830a67149eb96e
 *      /usr/lib/debug/.build-id/79/ec1368a748c04c131c116835503de3474248bc.debug
 *      /usr/lib/debug/.build-id/79/ec1368a748c04c131c116835503de3474248bc
 *      /usr/lib/debug/.build-id/7c/778c65e85b48512ae4987b163f255afa6fde70.debug
 *      /usr/lib/debug/.build-id/7c/778c65e85b48512ae4987b163f255afa6fde70
 *      /usr/lib/debug/.build-id/b9/d4daa881eb4d18817df545f2a655e7a20efed6.debug
 *      /usr/lib/debug/.build-id/b9/d4daa881eb4d18817df545f2a655e7a20efed6
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * dev-util/electron-9.3.2:9.3.2::pf4public
 *      /usr/lib/debug/.build-id/09/71e724994107fcbb071eac56830a67149eb96e
 *      /usr/lib/debug/.build-id/09/71e724994107fcbb071eac56830a67149eb96e.debug
 *      /usr/lib/debug/.build-id/79/ec1368a748c04c131c116835503de3474248bc
 *      /usr/lib/debug/.build-id/79/ec1368a748c04c131c116835503de3474248bc.debug
 *      /usr/lib/debug/.build-id/7c/778c65e85b48512ae4987b163f255afa6fde70
 *      /usr/lib/debug/.build-id/7c/778c65e85b48512ae4987b163f255afa6fde70.debug
 *      /usr/lib/debug/.build-id/b9/d4daa881eb4d18817df545f2a655e7a20efed6
 *      /usr/lib/debug/.build-id/b9/d4daa881eb4d18817df545f2a655e7a20efed6.debug
 * 
 * Package 'dev-util/electron-9.2.1' NOT merged due to file collisions.
 * If necessary, refer to your elog messages for the whole content of the
 * above message.

>>> Failed to install dev-util/electron-9.2.1,

**How to Reproduce**
1. Merge a later version first, e.g. merge dev-util/electron-9.3.2
2. Try to merge an earlier version, e.g. merge dev-util/electron-9.2.1.
3. See above error after 1 day of 100% CPU usage and a sluggish system unable to do real work. :-(((

**Expected behavior**
Merge/unmerge whichever version you like without such problems.

**Actual behavior**
You get a silly error like the above.

**Additional context**
I had merged dev-util/electron-9.3.2 first, when I realized that vscode needed a lower version, 9.2.1. I let it do - and here we are...

**Comment by PF4Public** [comment]
Please provide build log and your system configuration.
I have both installed on my system:
```
qlist -Iv| grep electron
app-eselect/eselect-electron-0.1
dev-util/electron-9.3.2
dev-util/electron-9.2.1
```
And none of them is installing `.build-id`:
```
equery f electron| grep debug
/usr/lib64/electron-9.2.1/npm/node_modules/bluebird/js/release/debuggability.js
/usr/lib64/electron-9.2.1/npm/node_modules/debug
/usr/lib64/electron-9.2.1/npm/node_modules/debug/.coveralls.yml
/usr/lib64/electron-9.2.1/npm/node_modules/debug/.npmignore
/usr/lib64/electron-9.2.1/npm/node_modules/debug/.travis.yml
/usr/lib64/electron-9.2.1/npm/node_modules/debug/CHANGELOG.md
/usr/lib64/electron-9.2.1/npm/node_modules/debug/LICENSE
/usr/lib64/electron-9.2.1/npm/node_modules/debug/Makefile
/usr/lib64/electron-9.2.1/npm/node_modules/debug/README.md
/usr/lib64/electron-9.2.1/npm/node_modules/debug/karma.conf.js
/usr/lib64/electron-9.2.1/npm/node_modules/debug/node.js
/usr/lib64/electron-9.2.1/npm/node_modules/debug/node_modules
/usr/lib64/electron-9.2.1/npm/node_modules/debug/node_modules/ms
/usr/lib64/electron-9.2.1/npm/node_modules/debug/node_modules/ms/index.js
/usr/lib64/electron-9.2.1/npm/node_modules/debug/node_modules/ms/license.md
/usr/lib64/electron-9.2.1/npm/node_modules/debug/node_modules/ms/package.json
/usr/lib64/electron-9.2.1/npm/node_modules/debug/node_modules/ms/readme.md
/usr/lib64/electron-9.2.1/npm/node_modules/debug/package.json
/usr/lib64/electron-9.2.1/npm/node_modules/debug/src
/usr/lib64/electron-9.2.1/npm/node_modules/debug/src/browser.js
/usr/lib64/electron-9.2.1/npm/node_modules/debug/src/debug.js
/usr/lib64/electron-9.2.1/npm/node_modules/debug/src/index.js
/usr/lib64/electron-9.2.1/npm/node_modules/debug/src/node.js
/usr/lib64/electron-9.2.1/npm/node_modules/debuglog
/usr/lib64/electron-9.2.1/npm/node_modules/debuglog/LICENSE
/usr/lib64/electron-9.2.1/npm/node_modules/debuglog/README.md
/usr/lib64/electron-9.2.1/npm/node_modules/debuglog/debuglog.js
/usr/lib64/electron-9.2.1/npm/node_modules/debuglog/package.json
/usr/lib64/electron-9.2.1/npm/node_modules/worker-farm/tests/debug.js
/usr/lib64/electron-9.2.1/npm/test/tap/debug-logs.js
/usr/lib64/electron-9.2.1/resources/inspector/browser_debugger
/usr/lib64/electron-9.2.1/resources/inspector/browser_debugger/browser_debugger-legacy.js
/usr/lib64/electron-9.2.1/resources/inspector/browser_debugger/browser_debugger.js
/usr/lib64/electron-9.2.1/resources/inspector/browser_debugger/browser_debugger_module.js
/usr/lib64/electron-9.2.1/resources/inspector/node_debugger
/usr/lib64/electron-9.2.1/resources/inspector/node_debugger/node_debugger_module.js
/usr/lib64/electron-9.3.2/npm/node_modules/bluebird/js/release/debuggability.js
/usr/lib64/electron-9.3.2/npm/node_modules/debug
/usr/lib64/electron-9.3.2/npm/node_modules/debug/.coveralls.yml
/usr/lib64/electron-9.3.2/npm/node_modules/debug/.npmignore
/usr/lib64/electron-9.3.2/npm/node_modules/debug/.travis.yml
/usr/lib64/electron-9.3.2/npm/node_modules/debug/CHANGELOG.md
/usr/lib64/electron-9.3.2/npm/node_modules/debug/LICENSE
/usr/lib64/electron-9.3.2/npm/node_modules/debug/Makefile
/usr/lib64/electron-9.3.2/npm/node_modules/debug/README.md
/usr/lib64/electron-9.3.2/npm/node_modules/debug/karma.conf.js
/usr/lib64/electron-9.3.2/npm/node_modules/debug/node.js
/usr/lib64/electron-9.3.2/npm/node_modules/debug/node_modules
/usr/lib64/electron-9.3.2/npm/node_modules/debug/node_modules/ms
/usr/lib64/electron-9.3.2/npm/node_modules/debug/node_modules/ms/index.js
/usr/lib64/electron-9.3.2/npm/node_modules/debug/node_modules/ms/license.md
/usr/lib64/electron-9.3.2/npm/node_modules/debug/node_modules/ms/package.json
/usr/lib64/electron-9.3.2/npm/node_modules/debug/node_modules/ms/readme.md
/usr/lib64/electron-9.3.2/npm/node_modules/debug/package.json
/usr/lib64/electron-9.3.2/npm/node_modules/debug/src
/usr/lib64/electron-9.3.2/npm/node_modules/debug/src/browser.js
/usr/lib64/electron-9.3.2/npm/node_modules/debug/src/debug.js
/usr/lib64/electron-9.3.2/npm/node_modules/debug/src/index.js
/usr/lib64/electron-9.3.2/npm/node_modules/debug/src/node.js
/usr/lib64/electron-9.3.2/npm/node_modules/debuglog
/usr/lib64/electron-9.3.2/npm/node_modules/debuglog/LICENSE
/usr/lib64/electron-9.3.2/npm/node_modules/debuglog/README.md
/usr/lib64/electron-9.3.2/npm/node_modules/debuglog/debuglog.js
/usr/lib64/electron-9.3.2/npm/node_modules/debuglog/package.json
/usr/lib64/electron-9.3.2/npm/node_modules/worker-farm/tests/debug.js
/usr/lib64/electron-9.3.2/npm/test/tap/debug-logs.js
/usr/lib64/electron-9.3.2/resources/inspector/browser_debugger
/usr/lib64/electron-9.3.2/resources/inspector/browser_debugger/browser_debugger-legacy.js
/usr/lib64/electron-9.3.2/resources/inspector/browser_debugger/browser_debugger.js
/usr/lib64/electron-9.3.2/resources/inspector/browser_debugger/browser_debugger_module.js
/usr/lib64/electron-9.3.2/resources/inspector/node_debugger
/usr/lib64/electron-9.3.2/resources/inspector/node_debugger/node_debugger_module.js
```

**Comment by sedimentation-fault** [comment]
I am writing here to you to tell you that I will not follow any discussions, bugs, issues, whatever in this repository anymore, as it is a waste of my time. You @PF4Public, you must indeed learn to read first - to read what other people tell you - and try hard to understand and respond to the questions raised. You cannot just dismiss issues as "irrelevant", or even "too heated" just because *you* have trouble understanding them, as you did with https://github.com/PF4Public/gentoo-overlay/issues/55 , https://github.com/PF4Public/gentoo-overlay/issues/56 and https://github.com/PF4Public/gentoo-overlay/issues/57 ...

Goodbye.

**Comment by sedimentation-fault** [comment]
Just saw your message above. I don't want you to think that I didn't want to help you, so here is my last hint: as I told you elsewhere (https://github.com/PF4Public/gentoo-overlay/issues/56), I had to disable the *clang* USE flag, so I installed both versions in the indicated sequence with *-clang*. Maybe you should try that.

So, now, it's time to say goodbye for good. I'm out.

**Comment by sedimentation-fault** [comment]
...and also have

FEATURES="${FEATURES} splitdebug"

in your make.conf. Then you should be able to reproduce it. To avoid the issues with splitdebug, consider adding

RESTRICT="splitdebug"

to your ebuild, as you can read here:

splitdebug
    Disables splitdebug for specific packages. This is for packages with binaries that trigger problems with splitdebug, such as file-collisions between symlinks in /usr/lib/debug/.build-id (triggered by bundled libraries). 

(from: https://devmanual.gentoo.org/eclass-reference/ebuild/)

I have splitdebug enabled in my make.conf because of this:

# Valgrind will not work if glibc does not have debug symbols.
# To fix this you can add splitdebug to FEATURES
# and remerge both glibc and valgrind.  See:
# 
# https://bugs.gentoo.org/show_bug.cgi?id=214065
# https://bugs.gentoo.org/show_bug.cgi?id=274771
# https://bugs.gentoo.org/show_bug.cgi?id=388703
# https://bugs.gentoo.org/show_bug.cgi?id=390323

but maybe I should make it a per-package decision, following the advice in

https://blog.ramses-pyramidenbau.de/?p=252

Oh well...

**Comment by sedimentation-fault** [comment]
...sorry for the awful formatting, I cannot change it...Bye.
