### ISSUE TITLE
Is icu 67 really the minimum version necessary for vscode 1.50.1?

### ISSUE THREAD

**Issue by sedimentation-fault** [PF4Public/gentoo-overlay#55]
Please double-check what the minimum version of icu should be for vscode. I had icu-65.1-r1 and all was good. Due to you hard requirement for icu 67 in order to merge vscode, I had to upgrade it. The result was that I had to re-merge ~60 packages that depended on it - a process that took almost a *week*, brought the system to its knees, made other work hard to impossible - and forced me to download a dozen packages to my local overlay, because the versions I had would not re-merge with icu 67. What a PITA!

I still have not managed to merge vscode. I still struggle with its requirements. The reverberations of upgrading icu are not yet clear. Was all that *really* necessary*? Would vscode and/or electron *fail* with, say, icu 65?

I could just as well lay down my work for a month and start upgrading all 4000 packages! :-(((
I will certainly do it some day - but I prefer to be able to decide myself on the timing, rather than be forced into it by...a code editor! Am I still in charge of my system? Was Gentoo not "about choice"? What are my choices here if I am forced to see 4 out of 8 virtual CPUs at 100% for one week at a moment in time that could not be less favorable?

**Comment by PF4Public** [comment]
There is no such thing as icu-65.1-r1 in Gentoo presently: https://packages.gentoo.org/packages/dev-libs/icu

>Please double-check what the minimum version of icu should be for vscode.

Please tell me how could I accomplish that. What do I do if someone later asks me to verify whether this works with icu-64?

>Due to you hard requirement for icu 67 in order to merge vscode, I had to upgrade it.
> … rather than be forced into …
> … I am forced …

[Not seing any _hard_ dependencies](https://github.com/PF4Public/gentoo-overlay/blob/a81cd0fe86ea5f6a11768dfe4d6cbd5af763cab7/dev-util/electron/electron-9.3.2.ebuild#L1160), not seing any reasons, that you _had_ to upgrade it. Not seing any _enforcing_ either.

>Was all that *really* necessary*?

You could've merged electron with `-system-icu`.

>Would vscode and/or electron fail with, say, icu 65?

I have no idea, none of my systems has it, so I cannot test. You could give it a spin though.

>code editor

Please, do not misrepresent. You should've known, that this "code editor" is using electron, which is using a complete browser underneath. There is noone to blame here.

>Am I still in charge of my system? 

Absolutely! I didn't magically run portage on your system and agree to rebuild everything. Was that you yourself? So who's in charge then?

>Was Gentoo not "about choice"?

I'm not Gentoo developer, so you shouldn't be asking me this kind of questions.

>What are my choices … ?

What advice are you asking from me?

**Comment by PF4Public** [comment]
Given that there is not much to do w.r.t. this issue, I will close it.

When you have any additional information, feel free to reopen it.

**Comment by sedimentation-fault** [comment]
This is NOT an invalid issue. It is very, very valid!

You said:
> There is no such thing as icu-65.1-r1 in Gentoo presently: https://packages.gentoo.org/packages/dev-libs/icu

...and that's exactly the problem: PRESENTLY! What does this have to do with what I am trying to tell you? NOTHING!

So for you, if somebody (like me) synced his portage a few months ago (that was in May of this year) and got icu-65.1-r1 (which was the latest and greatest back then) now has to upgrade to version 67, just because it's the only one "presently" there? What does this have to do with an ebuild? An ebuild must require the *minimum* requirements, NOT the *maximum* ones!

You say:
> Please tell me how could I accomplish that. What do I do if someone later asks me to verify whether this works with icu-64?

Well, actually, that's pretty simple: as an author of an ebuild, it is your responsibility to find out the minimum requirements for the software that is installed through your ebuild. You do this by simply asking the developers: "Hello, I am the author of the Gentoo ebuild of your software. Please tell me the minimum versions of the libraries needed by your software". A possible answer would look like this: "Our software works with icu >= 60, but we recommend to use the latest version of it (67 at the time of this writing), as previous versions might contain security vulnerabilities".

With an answer like this, you would then go and add 

system-icu? ( >=dev-libs/icu-60:= )

and NOT, as you did

system-icu? ( >=dev-libs/icu-67.1:= )

Why? The developers (in this hypothetical example) told you that they recommend v. 67 due to possible vulnerabilities of previous versions, right?

Yes, but: here comes what I said about "choice" (which you dismissed as irrelevant): 

Because "Gentoo is about choice", you should not impose your own ideas on the users, you should leave them with a choice: they can use icu >= 60 (in this example), but are free to upgrade whenever they choose to the latest version. 

The important message to "take home" here is: the version you specify is NOT the one according to your own ideas of what is available/secure/whatever - but what WORKS! If version 60 works, according to the developers, you take that one and make a note: "Please consider upgrading your icu, as earlier versions might have XXX problems".

Very simple.

What you chose to do, instead is to impose the *maximum* version available as the *minimum* requirement:

system-icu? ( >=dev-libs/icu-67.1:= )

means: this software *requires* icu at least v. 67 - and v. 67 is the currently highest version!

"But, it is also the only one available at the Gentoo repository!", you might say. This may be true, but what I am trying to tell you here is that it is irrelevant: people may have various versions of icu installed on their systems, regardless of which version is available right now ("presently", as you said). What is important is: will the software work with those versions, or is the latest and greatest version really necessary? That was the essence of my writing. You cannot dismiss that as invalid! It has huge consequences:

> not seing any reasons, that you had to upgrade it. Not seing any enforcing either.

Well, a line like the one you have (and the one you linked to)

system-icu? ( >=dev-libs/icu-67.1:= )

says practically: So you want to use your system icu, instead of bloating your installation with the bundled (and possibly the 100th of such bundled crap) icu? Well, if you do, then you MUST use icu-67 or higher!

Why? Who are you to enforce a version of 67 to me, just because I want to use my system icu? Do you have valid reasons for this? Will the software cease to work if I use my system icu which is version 65? If not, then why are you trying to enforce it on me?

That's the essence of this bug report - you should not enforce anything. Saying "you must use version X if you want to continue to use your system library Y" *is* enforcing. You can certainly do it, but only if the software will not work with a lower version.

You said:
> I have no idea, none of my systems has it, so I cannot test. You could give it a spin though.

No. Definitely not. This is *your* job, not mine. I might indeed help you - if you had asked me. But you didn't. You set the above line, practically saying "the software will NOT work with a system icu lower than 67". When I see a line like that, I say to myself "oh, this software really needs icu 67", because I assume the ebuild developer checked this claim. Alas, you didn't. 

And you set off an avalanche of recompilations! Not only that I had to recompile ~60 packages, quite a few of them refused to compile, because they brought errors like

class XXXX of icu does not have member YYYY

so it was clear that I had to 

- either sync my portage to the latest version and re-merge ~3000+ packages, practically stopping to work for the next month, or
- get the newest versions of those packages that refused to compile, put them into my local overlay and merge them - what a PITA!

For all these reasons, just putting the *latest* version of a library like icu as the *minimum* requirement is not only mindless - but catastrophic as well. Please think about all this the next time you inflict a requirement as severe as this one that might not be really necessary on your users. Thank you.

**Comment by sedimentation-fault** [comment]
> When you have any additional information, feel free to reopen it.
For all the above reasons, I would reopen it. It is important to find the *really minimum* requirements of electron and maybe someone else can help here too. But I cannot find a way to do it (some JS menus still don't work here), so it's now up to you.

**Comment by PF4Public** [comment]
>Who are you to enforce

I'm not _enforcing_ (if you like this word most) you to using my overlay.
