### ISSUE TITLE
eslint-config-standard@12.0.0" has unmet peer dependency "eslint-plugin-promise@>=4.0.0"

### ISSUE THREAD

**Issue by sedimentation-fault** [PF4Public/gentoo-overlay#57]
During merge of electron 9.3.2, I get:

[3/4] Linking dependencies...
warning " > eslint-config-standard@12.0.0" has unmet peer dependency "eslint-plugin-promise@>=4.0.0".
[4/4] Building fresh packages...

What is going on?

**Description**

**How to Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Logs**
If applicable, please provide the build log.

**Additional context**

**Comment by PF4Public** [comment]
What is the issue exactly? Please fill in the issue template.

**Comment by PF4Public** [comment]
> During merge of electron 9.3.2

Is it not compiling? Please provide the build log.

**Comment by sedimentation-fault** [comment]
It compiles just fine. I am just curious why it spits this warning. It looks like this is some node(?) plugin that is trying to add, but cannot due to this "unmet requirement". 

I tried to attach the build log (at least the first 500 lines of it), but, as I said, I cannot fully use JavaScript on github right now, so it did not work, sorry.

**Comment by PF4Public** [comment]
>I am just curious why it spits this warning.

To answer your question: I'm not electron developer, I don't know what this warning means. You could file this issue upstream in electron repository.

>Looks like the ebuild is missing some dependency for some "extension"/whatever.

Unlikely.

As this turned to be a no-issue, I'll close it.
