### ISSUE TITLE
www-client/ungoogled-chromium with +clang conflicts with qtwebengine applications w/o clang (in dev-libs/re2 package)

### ISSUE THREAD

**Issue by Bogdan107** [PF4Public/gentoo-overlay#59]
**Is your feature request related to a problem? Please describe.** 
OS: Gentoo
dev-qt/qtwebengine require dev-libs/re2 for normal run.
www-client/ungoogled-chromium require dev-libs/re2 for normal run.

qtwebengine don't have flags to compiling it with clang, fails compiling with clang, and compiled only with gcc.
re2 may be compiled with gcc and clang, but do not have clang flag.
ungoogled-chromium may be compiled with gcc and clang and have clang flag.

If re2 compiled with gcc, then compiling ungoogled-chromium fails with error for RE2.
If re2 compiled with clang, then compiling qtwebengine fails with error for RE2.

Conclusions:
1) qtwebengine, compiled with gcc, require re2, which were compiled with gcc too.
2) ungoogled-chromium, compiled with clang, require re2, which were compiled with clang too.

If I need to use ungoogled-chromium, I need to recompile re2 with clang.
But at system update, qtwebengine compiling fails with error and all qtwebengined applications are crashes at start...
Error example:
> falkon: symbol lookup error: /usr/lib64/libQt5WebEngineCore.so.5: undefined symbol: _ZN3re212re2_internal5ParseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEbPKcmPT_

If I need to use qtwebengined applications, then I need to recompile re2 with gcc. But, ungoogled-chromium, which compiled with clang, crashes at start...
Error example:
> chromium-browser: symbol lookup error: chromium-browser: undefined symbol: _ZN3re23RE2C1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE

For using ungoogled-chromium, I recompile re2 with clang, and ungoogled-chromium runs well.
For using qtwebengine applications, I recompile re2 with gcc, and all qtwebengine applications are runs well.
### But not runs well <ungoogled-chromium/clang> and <qtwebengine/gcc applications> simultenious.

 **Describe the solution you'd like** 
I need compiling re2 library inside ungoogled-chromium, if clang flag activated for ungoogled-chromium.
Solution is like:
1) adding system-re2 flag to ebuild, which choise which re2 library to use - system or bundled with ungogoled-chromium,
1.1) modify REQUIRED_USE variable of ebuild, like this: REQUIRED_USE="clang? (system-re2? (dev-libs/re2 +clang))";
1.2) maybe add dev-libs/re2 to BDEPEND variable of ebuild and activate clang compiler for this package (I don't know how to force activate clang compiler for re2 in ebuild, while re2 don't have clang flag).
2) automatic build/link re2 library (whith force compiled with clang) with ungoogled-chromium, if clang flag activated for ungoogled-chromium.

Variant 1 is more pretty for me.

**Comment by PF4Public** [comment]
Have you tried compiling ungoogled-chromium with gcc?

**Comment by Bogdan107** [comment]
flaggie dev-libs/re2 %compiler-clang
flaggie ungoogled-chromium -clang -thinlto -optimize-thinlto -cfi; # -clang
require: -thinlto, -optimize-thinlto, -cfi
flaggie ungoogled-chromium +max-6pcu
emerge -1 dev-libs/re2 ungoogled-chromium


uname -a

> Linux fregat 5.9.11-gentoo-x86_64 #6 SMP PREEMPT Mon Nov 30 01:41:32 EET
> 2020 x86_64 AMD Ryzen 5 4600H with Radeon Graphics AuthenticAMD GNU/Linux


cat /etc/portage/env/compiler-clang

> CC="clang"
> CXX="clang++"


cat /etc/portage/env/max-6cpu

> MAKEOPTS="-j6 --load-average=11"


cat /etc/portage/make.conf | grep MAKEOPTS

> MAKEOPTS="-j10 --load-average=11"


equery u ungoogled-chromium | grep +

> +convert-dict
> +cups
> +kerberos
> +l10n_ru
> +l10n_uk
> +official
> +optimize-webui
> +proprietary-codecs
> +pulseaudio
> +python_targets_python2_7
> +python_targets_python3_7
> +system-ffmpeg
> +system-harfbuzz
> +system-icu
> +system-libevent
> +system-openh264
> +system-openjpeg
> +tcmalloc
> +vaapi
> +vdpau
> +wayland


qlop -v ungoogled-chromium

> 2020-04-08T08:43:43 >>> www-client/ungoogled-chromium-80.0.3987.163_p1:
> 21:55:19    <- GCC
> 2020-11-15T12:10:26 >>> www-client/ungoogled-chromium-86.0.4240.198_p1:
> 3:30:25    < Clang
> 2020-11-22T18:48:51 >>> www-client/ungoogled-chromium-87.0.4280.66_p1:
> 6:21:01    < Clang
> 2020-11-23T04:25:51 <<< www-client/ungoogled-chromium-87.0.4280.66_p1:
> 1:38:54    < Clang
> 2020-11-23T05:24:04 >>> www-client/ungoogled-chromium-87.0.4280.66_p1:
> 41′06″    < Clang
> 2020-11-28T11:48:10 >>> www-client/ungoogled-chromium-87.0.4280.67_p1:
> 43′55″    < Clang
> 2020-12-01T04:59:11 >>> www-client/ungoogled-chromium-87.0.4280.67_p1:
> 6:29:09    < Clang




>




вт, 1 дек. 2020 г. в 10:10, PF4Public <notifications@github.com>:

**Comment by PF4Public** [comment]
>compiling … on modern processor
> …
>ineffective usage of time and energy

First of all, please avoid blame game, okay? Gentoo _inherently_ involves compiling one way or another.

So, may I sum up the issue as I've undestood it.

Re2 compiled with cland is incompatible with qtwebengine, which (as you say) could not be compiled with clang.
Given that qtwebengine does not compile with clang, one solution is to compile ungoogled-chromium with gcc. Another solution would be to compile re2 within chromium codebase without depending on an external library. Did I get it right?

I've checked my system and looks like I don't have qtwebengine, and unfortunately I'll probbably have no time to test all this, so I'll take your words for granted, besides you do show your efforts in overcoming the issue, which is of the most value and really helpful.

Like you said, first solution, even being readily available, has a huge compilation cost, which makes it less appealing. With respect to second solution, I think implementing it would be relatively harmless, if any at all. I'll look into it later, but cannot promise anything in that regard.

**Comment by Bogdan107** [comment]
> Another solution would be to compile re2 within chromium codebase without depending on an external library. Did I get it right?

Yes, you right! I like this solution! I want this feature!

**Comment by PF4Public** [comment]
Please test if `-system-re2` does compile in re2 from the tree.

**Comment by Bogdan107** [comment]
> Please test if `-system-re2` does compile in re2 from the source tree.

> FAILED: chrome
> ld.lld: error: undefined symbol: re2::RE2::RE2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
> ld.lld: error: undefined symbol: re2::RE2::CheckRewriteString(re2::StringPiece const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const
> ld.lld: error: undefined symbol: re2::FilteredRE2::AllPotentials(std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> >*) const

**Comment by PF4Public** [comment]
I forgot to actually keep the re2 sources. Try again, should work now.

**Comment by PF4Public** [comment]
I assume this issue is now fixed, feel free to reopen it if that's not the case.

**Comment by Bogdan107** [comment]
> I assume this issue is now fixed, feel free to reopen it if that's not the case.

dev-libs/re2 compiled by gcc.
dev-qt/qtwebengine compiled by gcc.
dev-qt/qtwebengine[+clang,-system-re2] compiled by clang.

All works fine at the same time!

Issue fixed!
