### ISSUE TITLE
www-client/ungoogled-chromium: system-libvpx is enabled by default, which causes an instant failure

### ISSUE THREAD

**Issue by invakid404** [PF4Public/gentoo-overlay#60]
**Description**
www-client/ungoogled-chromium has the system-libvpx USE flag enabled by default, which results in an instant failure, stating that building with system libvpx is not supported.

**How to Reproduce**
Emerging www-client/ungoogled-chromium without touching the default USE flags.

**Comment by PF4Public** [comment]
Default USE flags are: `+system-libvpx vaapi`.
