### ISSUE TITLE
Chromium on electron-9.3.5 doesn't build

### ISSUE THREAD

**Issue by XutaxKamay** [PF4Public/gentoo-overlay#61]
**Description**
Chromium when emerging electron-9.3.5 doesn't compile because it misses a lot of patches:

chromium-fix-char_traits.patch
chromium-82-gcc-iterator.patch
... And many others

A fix would be just to remove or add the patches into the files directory, if possible.

**Comment by PF4Public** [comment]
I think, I could've removed some of the needed ones at 621ceedec2ec6ec1cecd022f1c796f2e4835bc42 :(

**Comment by PF4Public** [comment]
I hope, I've restored them all, test again and feel free to close this issue, if it is fixed.

**Comment by XutaxKamay** [comment]
It is fixed, thank you very much.

Closing.

**Comment by PF4Public** [comment]
Is it still open? :D

**Comment by XutaxKamay** [comment]
Right lol, dont know why.

Closing again. :)
