### ISSUE TITLE
app-editors/vscode-1.52.1 (stable) depends on testing version of electron.

### ISSUE THREAD

**Issue by muhlemmer** [PF4Public/gentoo-overlay#62]
Can't upgrade VSCode unless I keyword electron.

https://github.com/PF4Public/gentoo-overlay/blob/31e3659bd843c636aa28e0b4bdce3c8e3caea090/app-editors/vscode/vscode-1.52.1.ebuild#L31

https://github.com/PF4Public/gentoo-overlay/blob/31e3659bd843c636aa28e0b4bdce3c8e3caea090/dev-util/electron/electron-9.3.5.ebuild#L1167

Keep up the nice work!

**Comment by PF4Public** [comment]
Sorry, seems that I've forgotten to mark it stable.
