### ISSUE TITLE
The dependency of media-libs/openjpeg is hardcoded to 2.3

### ISSUE THREAD

**Issue by imrebuild** [PF4Public/gentoo-overlay#63]
https://github.com/PF4Public/gentoo-overlay/blob/800ae6dc82aff7513ef9064e18dc76fca71dc1d9/www-client/ungoogled-chromium/files/chromium-system-openjpeg-r2.patch#L23

Now the latest version is 2.4, which should be set to `#include <openjpeg-2.4/openjpeg.h>`.

**Comment by PF4Public** [comment]
Yesterday I started compiling all binaries and today got them suddenly failed. Was wandering, why so…

Thank you very much for pointing me strait to the solution!

**Comment by PF4Public** [comment]
Please test, if that solves the issue.

**Comment by imrebuild** [comment]
This change should fix the problem. I can emerge the package without issue.
