### ISSUE TITLE
CLOSED: My Error

### ISSUE THREAD

**Issue by mrturcot** [PF4Public/gentoo-overlay#64]
**Description**
Error during compilation

**How to Reproduce**
1. emerge www-client/ungoogled-chromium
2. Build Fails

**Expected behavior**
Compilation to complete without errors

**Actual behavior**
Compilation Fails

**Comment by mrturcot** [comment]
My error closing issue

**Comment by PF4Public** [comment]
Just FYI: I'm not involved in menelkir overlay.

**Comment by mrturcot** [comment]
> Just FYI: I'm not involved in menelkir overlay.
> 
> BTW, current version is 87, do you need 86 specifically?

No thank you, I'm fairly new to Gentoo and was under the impression I was using your ebuild. I've emerged with your overlay and now on 87.

Only issue is widevine. I enabled the use flag but it's not working. don't see any system links anywhere. I've commented to the widevine issue open on Eloston.
