### ISSUE TITLE
www-client/ungoogled-chromium-bin-87.0.4280.141_p1: dependency mismatch

### ISSUE THREAD

**Issue by nagalun** [PF4Public/gentoo-overlay#65]
The new pre-compiled version of ungoogled-chromium (only tested core2) was built with `=dev-libs/icu-68*`, however the ebuild still depends on `=dev-libs/icu-67*`:

https://github.com/PF4Public/gentoo-overlay/blob/master/www-client/ungoogled-chromium-bin/ungoogled-chromium-bin-87.0.4280.141_p1.ebuild#L99
```
$ ldd /opt/chromium-browser/chrome | grep icu
        libicui18n.so.68 => /usr/lib64/libicui18n.so.68 (0x00007f91f8e6e000)
        libicuuc.so.68 => /usr/lib64/libicuuc.so.68 (0x00007f91f8c87000)
        libicudata.so.68 => /usr/lib64/libicudata.so.68 (0x00007f91f37a2000)
```

**Comment by PF4Public** [comment]
Sorry, my bad. It is difficult to keep the list of dependencies in sync with binaries as there is no (at least I'm not aware of anything like that) easy way of doing so.
