### ISSUE TITLE
www-plugins/chrome-binary-plugins / dependency conflict

### ISSUE THREAD

**Issue by mrturcot** [PF4Public/gentoo-overlay#67]
Welp... well I just received this warning from emerge about a dependency conflict.... 

```
WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

www-plugins/chrome-binary-plugins:stable

  (www-plugins/chrome-binary-plugins-88.0.4324.96:stable/stable::gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)" conflicts with
    ~www-plugins/chrome-binary-plugins-87.0.4280.141 required by (www-client/ungoogled-chromium-87.0.4280.141_p1:0/0::pf4public, installed)
```

Widevine rearing its ugly head again. Let me know if I can test anything.
Thanks

Edit - I did notice in my root dir, a Widevine dir containing `libwidevinecdm.so`. Im not sure where it came from as chrome-binary-plugins installs in /usr/lib64/chromium-browser. So I removed the Widevine dir in root but then I thought maybe thats where the USE="widevine" installs it while emerging? Not too sure. Also `libwidevinecdm.so` in root dir was symlinked to a non existent location.

**Comment by PF4Public** [comment]
Are you trying to install it again, or is it a warning? It seems, that they've bumped chrome-binary-plugins with the arrival of new chromium version. I suggest waiting, till ungoogled-chromium bumps to 88 version and see if the warning persists. By the look of it, this seems to be harmless.

**Comment by mrturcot** [comment]
> Are you trying to install it again, or is it a warning? It seems, that they've bumped chrome-binary-plugins with the arrival of new chromium version. I suggest waiting, till ungoogled-chromium bumps to 88 version and see if the warning persists. By the look of it, this seems to be harmless.

No, just just came up with during my emerge world update, thanks for the response :)
