### ISSUE TITLE
Problem Trying to Emerge, Related to Python 2.7

### ISSUE THREAD

**Issue by robert17171** [PF4Public/gentoo-overlay#72]
When I try to emerge ungoogled-chromium, it tells me that I have unmet use flag requirements, but the list of unmet use flag requirements is empty. I believe it has something to do with $(python_gen_useflags 'python2*') in the ebuild file

```
!!! Problem resolving dependencies for www-client/ungoogled-chromium from @selected

!!! The ebuild selected to satisfy "www-client/ungoogled-chromium" has unmet requirements.
- www-client/ungoogled-chromium-88.0.4324.96-r1::pf4public USE="clang official pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libvpx system-openh264 system-re2 tcmalloc -cfi -closure-compile -convert-dict -cups -custom-cflags -enable-driver -hangouts -headless -kerberos -optimize-thinlto -optimize-webui -pgo -proprietary-codecs (-selinux) -suid -system-openjpeg -thinlto -vaapi -vdpau -wayland -widevine" ABI_X86="(64)" L10N="-am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python3_8 -python3_7 -python3_9"

  The following REQUIRED_USE flag constraints are unsatisfied:
    

  The above constraints are a subset of the following complete expression:
    any-of ( python_targets_python3_7 python_targets_python3_8 python_targets_python3_9 ) any-of ( ) thinlto? ( clang ) optimize-thinlto? ( thinlto ) cfi? ( thinlto ) pgo? ( clang ) x86? ( !thinlto !widevine )
```

**Comment by 0xC0ncord** [comment]
Looks like #71 is meant to address this

**Comment by perfect7gentleman** [comment]
Nope, those modifications did not help.

**Comment by dimgel** [comment]
Same here. No python-related stuff in make.conf.

**Comment by dimgel** [comment]
BTW, for a while same error arrived for already installed 87.0.4280.141_p1. If that ebuild was not edited (now it's deleted) then it's something gentoo guys changed. BTW recently there was a news item (eselect news) about python-exec.conf -- which does not look related to this issue, but they certainly do something.

**Comment by dimgel** [comment]
Funny thing is that problematic part "any-of ( )" is about python2 (if I understand correctly), but I have python 2.7 installed:

    $ emerge -pv --depclean python:2.7
    Calculating dependencies... done!
      dev-lang/python-2.7.18-r6 pulled in by:
        www-client/ungoogled-chromium-87.0.4280.141_p1 requires >=dev-lang/python-2.7.5-r2:2.7[xml]

**Comment by perfect7gentleman** [comment]
https://github.com/PF4Public/gentoo-overlay/pull/73 works.

**Comment by PF4Public** [comment]
> it's something gentoo guys changed

Yes, they are violently deprecating pytho2.7 and planning to remove it on Feb 15 completely. That's unfortunate :( No idea yet, what to do then.

In the meanwhile fixing ebuild like @perfect7gentleman suggest is the only option. I have some suggestions though.

**Comment by dimgel** [comment]
> Yes, they are violently deprecating python2.7 and planning on removing it on Feb 15 completely.

Maybe you can clone python2.7 ebuild into your repo? That is, if gentoo would still allow installing it alongside with python3. Or maybe it won't: news item "2020-09-28  Python 2.7 cleanup is progressing" says "However, if you really need to run them, we suggest using a virtualenv", whatever that means.

**Comment by PF4Public** [comment]
I've merged PRs, please test if its OK now.

**Comment by 0xC0ncord** [comment]
Seems to be working now, at least to get past the original error about `REQUIRED_USE`. Should be done compiling in 3-4 hours assuming nothing else goes wrong.

**Comment by smashcroft** [comment]
Seems to be working for me aswell now

**Comment by PF4Public** [comment]
~The Winter~ [Python3 support is coming](https://bugs.chromium.org/p/chromium/issues/detail?id=942720):
![image](https://user-images.githubusercontent.com/10319700/106467989-6c5c2f80-64ae-11eb-8701-12588d79bc94.png)
It is slow, but seems to be moving.

**Comment by dimgel** [comment]
> It is slow, but seems to be moving.

Same open bugs (6 in row, 3 in row, 1 last) for half a year at least.

**Comment by PF4Public** [comment]
> Same open bugs (6 in row, 3 in row, 1 last) for half a year at least.

Well, you know better 🤷

**Comment by 0xC0ncord** [comment]
I believe www-client/chromium is the only package in-tree that still requires python2.7. IIRC, Gentoo wanted to keep python2.7 but only as a BDEP and mask it completely otherwise, then last-rite it when Chromium finally updates its build system.

**Comment by 0xC0ncord** [comment]
Happy to report that I haven't run into any other issues.
```
www-client/ungoogled-chromium-88.0.4324.104-r1::pf4public was built with the following:
USE="cfi clang closure-compile convert-dict cups hangouts official optimize-thinlto optimize-webui pgo proprietary-codecs pulseaudio (selinux) suid system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-openh264 system-openjpeg system-re2 tcmalloc thinlto vaapi vdpau wayland -custom-cflags -enable-driver -headless -kerberos -system-libvpx -widevine" ABI_X86="(64)" L10N="-am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW"
CFLAGS="-march=znver2 -mtune=znver2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
CXXFLAGS="-march=znver2 -mtune=znver2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -flax-vector-conversions=all -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
LDFLAGS="-Wl,--as-needed -Wl,-S -Wl,-z,now -Wl,-z,relro -fuse-ld=lld -Wl,-unwindlib=libunwind -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=13"
```

**Comment by robert17171** [comment]
I now do not have the original errors about "any-of ( )", but the compile failed for me.

Here is the output of emerge `--info '=www-client/ungoogled-chromium-88.0.4324.96-r1::pf4public'`
https://pastebin.com/hUUJVfeS

Here is the output of `emerge -pqv '=www-client/ungoogled-chromium-88.0.4324.96-r1::pf4public'`
https://pastebin.com/Fcy9vg0e

**Comment by PF4Public** [comment]
@robert17171 Please provide the full build log.

**Comment by robert17171** [comment]
[build.log](https://github.com/PF4Public/gentoo-overlay/files/5907379/build.log)
I now see that you can upload files directly. Here is the build.log.

**Comment by PF4Public** [comment]
@robert17171 Now that this issue with Python 2.7 is fixed, would you mind if I close this bug and direct you to #75 to continue with this new issue as it seems to be exactly your new issue?

**Comment by robert17171** [comment]
Yeah. I am about to try with -system-libvpx. Thanks.
