### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by mcctuxic** [PF4Public/gentoo-overlay#75]
After the Python-2.7 issue was fixed (thanks! :) ) after an update I recompiled ungoogled chromium this morning (04:41 am UTC). The compilation ended with this error:
```
 * ERROR: www-client/ungoogled-chromium-88.0.4324.96-r1::pf4public failed (compile phase):
 *   ninja -v -j10 -l11 -C out/Release v8_context_snapshot_generator failed
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_compile
 *   environment, line 4512:  Called eninja '-C' 'out/Release' 'v8_context_snapshot_generator'
 *   environment, line 2138:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
```

Trying to attach the build.log (renamed to build-log.txt) fails with
"Something went really wrong, and we can't process that fiel. Try again."

I tried again and got the same error.

Three hours later it finally had worked....
[build-log.txt](https://github.com/PF4Public/gentoo-overlay/files/5909470/build-log.txt)

**Comment by gamozolabs** [comment]
Same issue here.

**Comment by PF4Public** [comment]
@gamozolabs @mcctuxic @robert17171 which version of libvpx do you have?

**Comment by gamozolabs** [comment]
Yep. Running `media-libs/libvpx-1.9.0::gentoo` on my stable Gentoo system.

I'm 20000/23000 through building with `www-client/ungoogled-chromium vdpau vaapi -system-libvpx optimize-thinlto optimize-webui thinlto` which is far beyond where I broke before. Seems the `-system-libvpx` does the trick here.

**Comment by mcctuxic** [comment]
Running the compilation since about 2 hours and 2.5 hours still to be done with the USE-flags given bei gamozolabs.
Previously it would had break already...
I think, this fix did it!

**Comment by smashcroft** [comment]
Samo issue for me, I'll try -system-libvpx and get back.

**Comment by mcctuxic** [comment]
It's done...everything is fine. "-system-libvpx" does it.
