### ISSUE TITLE
dev-util/electron: fails to build obj/v8/cppgc_base/heap-base.o

### ISSUE THREAD

**Issue by f1nniboy** [PF4Public/gentoo-overlay#82]
I'm on Gentoo and on the `default/linux/amd64/17.1/no-multilib/hardened` profile.
Build Log: https://paste.rs/ZZY
`emerge --info`: https://paste.rs/W79

It fails to build `obj/v8/cppgc_base/heap-base.o`.

LMK if I forgot any information.

**Comment by PF4Public** [comment]
Did it compile before?

**Comment by f1nniboy** [comment]
I have not compiled Electron before and I tried 11 and 12, I only compiled Chromium before which succeeded.

**Comment by PF4Public** [comment]
That might be a gcc-incompatibility. Have you tried clang?

**Comment by f1nniboy** [comment]
Yes, it was a different error though.
![image](https://user-images.githubusercontent.com/55994155/115241368-05e7c480-a121-11eb-93b6-16473db86c9b.png)

**Comment by PF4Public** [comment]
> clang-11: error: invalid linker name in argument '-fuse-ld=lld'

My bad, that must be due to this change:
https://github.com/PF4Public/gentoo-overlay/blob/f17294748274ecf35fb2e78449aa93db087a9b7f/dev-util/electron/electron-12.0.4.ebuild#L1842-L1843

I'll fix that later, in the meanwhile you may manually install `sys-devel/lld` to fix this particular error.

**Comment by f1nniboy** [comment]
Emerging that package fixed it, we can close this as soon as you fix the ebuild.

**Comment by PF4Public** [comment]
That is not exactly the fix for the original issue, which has something to do with your hardened profile and gcc, but I'm afraid I cannot help you more on the original issue.
