### ISSUE TITLE
www-client/ungoogled-chromium-90.0.4430.85-r1: build error: 'nomerge' attribute cannot be applied to a declaration

### ISSUE THREAD

**Issue by dimgel** [PF4Public/gentoo-overlay#83]
Build fails. Could not attach files to ticket (probably because of my NoScript), so here are links:

- http://dimgel.me/drop/gentoo/ungoogled-chromium-90.0.4430.85-r1--build.log.txt
- http://dimgel.me/drop/gentoo/ungoogled-chromium-90.0.4430.85-r1--emerge-info.txt

**Comment by dimgel** [comment]
Tried to turn off ccache, it made no difference.

**Comment by 115100** [comment]
This is because nomerge was only allowed on a declaration following llvm/llvm-project@fb0f7288051eb2745bb9211306f53ff9aa6f73e2, which is only available in clang-12 or over.

I noticed there's a check in the ebuild for >=clang-12 but the ebuild doesn't fail for me. Maybe the MERGE_TYPE check needs amending?

**Comment by PF4Public** [comment]
@115100 is absolutely right and I intended that check to fail fast and to avoid exactly this situation. Sorry for it didn't work.

@dimgel @115100 I've added a commit that should fix this fail-fast logic. May I ask you to verify that it fails the compilation early with clang-11?

**Comment by 115100** [comment]
It fails quickly for me now.

**Comment by dimgel** [comment]
For me too. So clang 12 it is then, didn't think of it. Now will try. :) Thanks!

**Comment by dimgel** [comment]
Everything is alright now, thank you again. :) Closing ticket.
// Phew, it builds so long... are you sure it's really ungoogled? :) Well, I know this question is not to you. :)

**Comment by PF4Public** [comment]
> it builds so long...

Earlier there was `jumbo` that helped immensely, but Google "fixed" it. They also generate a lot of code (interfaces and the like) on the fly and gradually this code became very ccache-unfriendly… 🤷
