### ISSUE TITLE
ungoogled-chromium-90.0.4430.85-r1 and 90.0.4430.93-r1: Clang 12 needed but not depended on

### ISSUE THREAD

**Issue by UnclePain** [PF4Public/gentoo-overlay#84]
When the USE flag clang is active (which is the default), the two mentioned versions of the ungoogled-chromium ebuilds depend (via BDEPEND) on sys-devel/clang with no version given. But the pre_build_checks function states (and fails if not met) that Clang >= 12 must be used.
Since Clang 12 is available in official Portage (currently 12.0.0-r1), I suggest that the ungoogled-chromium ebuilds include the necessary slot or version of sys-devel/clang in BDEPEND to avoid build failure.

**Comment by PF4Public** [comment]
I've considered that, but repoman QA check doesn't like it. I would like to avoid using `--force` to preserve the ability to catch real issues even before committing.

Sorry, but `wontfix`.
