### ISSUE TITLE
www-client/ungoogled-chromium: mksnapshot fails

### ISSUE THREAD

**Issue by cabinetto** [PF4Public/gentoo-overlay#85]
Before, that would only happen when I had the CFI use flag enabled, now I can't compile it at all. I'm compiling with clang 11.1.0 on a brand new gentoo chroot, here's the full build log:
[build.log](https://github.com/PF4Public/gentoo-overlay/files/6401829/build.log)
 build log

**Comment by PF4Public** [comment]
>Producer: 'LLVM13.0.0git' Reader: 'LLVM 11.1.0'

Your lld and llvm versions do not correspond to each other.

Please inspect your build log carefully yourself beforehand. I would like not to occupy myself with interpreting everyone's build logs.
