### ISSUE TITLE
www-client/ungoogled-chromium prebuild fails due to clang 12 despite it being scheduled for merge.

### ISSUE THREAD

**Issue by logrusx** [PF4Public/gentoo-overlay#86]
clang 12 is scheduled for merge, but:

 * ERROR: www-client/ungoogled-chromium-90.0.4430.93-r1::pf4public failed (pretend phase):
 *   At least clang 12 is required

**Comment by logrusx** [comment]
I'm sorry for being too fast to report a bug, this seems to come from the original chromium ebuild for a reason.

**Comment by PF4Public** [comment]
Thank you for understanding.

The reason is that it would be otherwise impossible to mark the ebuild as stable given that llvm-12 is still unstable.

**Comment by logrusx** [comment]
Hello, this is not necessary anymore and it still causes the same problem - ungoogled-chromium fails at pre-merge check because although clang is scheduled for merge, it's for the first time and still there isn't a clang version emerged to run that check on.

**Comment by PF4Public** [comment]
Do you have any proposition on how to fix this?

**Comment by logrusx** [comment]
I now see the stable chromium ebuild still does that too, but llvm-12 is stable since long ago, why is that still necessary? Can't it be at least done somewhere else than the pre-merge checks, to avoid breaking the very first install that pulls in clang?

**Comment by PF4Public** [comment]
> I now see the stable chromium ebuild still does that too, but llvm-12 is stable since long ago, why is that still necessary?

https://bugs.gentoo.org/757747

> Can't it be at least done somewhere else than the pre-merge checks, to avoid breaking the very first emerge that pulls in clang?

If this does not help:
https://github.com/PF4Public/gentoo-overlay/blob/e73b05fe3f6f2227edfdfcc59e45cfa549831168/www-client/ungoogled-chromium/ungoogled-chromium-107.0.5304.87_p1.ebuild#L209

I don't know what would.

Please refrain from reopening this issue unless you have a working solution.

**Comment by logrusx** [comment]
> Please refrain from reopening this issue unless you have a working solution.
Ok, no problem.

> > I now see the stable chromium ebuild still does that too, but llvm-12 is stable since long ago, why is that still necessary?
> 
> https://bugs.gentoo.org/757747
> 
> > Can't it be at least done somewhere else than the pre-merge checks, to avoid breaking the very first emerge that pulls in clang?
> 

I don't see how that's related. Original stable chromium ebuild suffers from the same issue, whether or not there is clang flag.

> If this does not help:
> 
> https://github.com/PF4Public/gentoo-overlay/blob/e73b05fe3f6f2227edfdfcc59e45cfa549831168/www-client/ungoogled-chromium/ungoogled-chromium-107.0.5304.87_p1.ebuild#L209
> 
> I don't know what would.
> 

I saw that line too. That's why I wondered why an check for an obsolete version of clang that's not even in the tree anymore still persists in the ebuild.

I hoped I can get an explanation as the previous one is no longer relevant. Could you elaborate on that?

**Comment by PF4Public** [comment]
> I saw that line too. That's why I wondered why an check for an obsolete version of clang that's not even in the tree anymore still persists in the ebuild.
> 
> I hoped I can get an explanation as the previous one is no longer relevant. Could you elaborate on that?

Looks like I misinterpreted your message, sorry. As for the question itself, well, it is simpler than it may seem. I would guess that the check you mention was once introduced and no one bothered removing it since. Likewise I do no review the whole ebuild with each bump, because, you know: <s>reasons</s> time. Since this check does not do any harm in 99.99% cases, it is easily neglected to be addressed (also by me).

Your reasoning looks valid and if this actually bothers you, I can comment that check.

**Comment by logrusx** [comment]
> Your reasoning looks valid and if this actually bothers you, I can comment that check.

It seems like the original ebuild does not have that problem because it does not have the clang use flag. If clang is not available it seems to resort to gcc.
So I think this should be commented or removed from ungoogled-chromium's ebuild as it creates unnecessary confusion for first timers, however rare might that case be.

**Comment by PF4Public** [comment]
Sure, no problem.
