### ISSUE TITLE
ungoogled-chromium-91.0.4472.77-r1 (and others): build fails with lld error "Unknown attribute kind"

### ISSUE THREAD

**Issue by UnclePain** [PF4Public/gentoo-overlay#88]
When trying to build either 91.0.4472.77-r1 or 90.0.4430.212-r1, I get the same error during compilation:

`ld.lld: error: obj/v8/gen-regexp-special-case/gen-regexp-special-case.o: Unknown attribute kind (70) (Producer: 'LLVM12.0.0' Reader: 'LLVM 11.1.0')`

I do have LLVM and Clang 12 installed:

```
$ equery l \*clang\* \*llvm\*
 * Searching for *clang* ...
[IP-] [  ] sys-devel/clang-10.0.1:10
[IP-] [  ] sys-devel/clang-11.1.0:11/11.1
[IP-] [  ] sys-devel/clang-12.0.0-r1:12
[IP-] [  ] sys-devel/clang-common-11.1.0:0
[IP-] [  ] sys-devel/clang-runtime-10.0.1:10.0.1
[IP-] [  ] sys-devel/clang-runtime-11.1.0:11.1.0
[IP-] [  ] sys-devel/clang-runtime-12.0.0:12.0.0

 * Searching for *llvm* ...
[IP-] [  ] sys-devel/llvm-10.0.1:10
[IP-] [  ] sys-devel/llvm-11.1.0:11
[IP-] [  ] sys-devel/llvm-12.0.0:12
[IP-] [  ] sys-devel/llvm-common-12.0.0:0
[IP-] [  ] sys-devel/llvmgold-12:0

```
I tried rebuilding all LLVM-related packages, to no avail.

[emerge-info.txt](https://github.com/PF4Public/gentoo-overlay/files/6591544/emerge-info.txt)
[build.log.gz](https://github.com/PF4Public/gentoo-overlay/files/6591545/build.log.gz)

**Comment by PF4Public** [comment]
Duplicate of #85

What is your use-case to have three versions simultaneously?

**Comment by UnclePain** [comment]
Thanks for the pointer, I would never have found #85 by its title. Updating lld to (yet unstable) 12.0.0 seems to fix the problem, ungoogled-chromium is currently compiling and it’s way past the gen-regexp-special-case point. So I’m closing this issue.

I didn’t have lld 12 installed because I manually installed Clang 12 in order to build ungoogled-chromium at all, and I had no idea it needs the same version of lld. I’m not experienced with the LLVM ecosystem and I basically do what Portage wants me to do…

I wish I could reduce my installed LLVMs and Clangs to one version but currently this is my use case:
- v12: sys-devel/llvm:12 is needed by sys-devel/clang:12 which is needed by ungoogled-chromium.
- v11: <sys-devel/llvm-12 is needed by dev-lang/rust-1.51.0-r2. Portage resolves this by installing LLVM 11, the latest stable version. Though I could get rid of this by updating to unstable rust-1.52.1 because it supports LLVM 12.
- v10: sys-devel/llvm-10.0.1 is needed by dev-util/lldb-10.0.1 which is needed by dev-util/idea-community-2021.1.1.211.7142.45. Here I have no upgrade path yet.

**Comment by PF4Public** [comment]
I truly understand your troubles, but cannot offer anything to ease the burden, sorry.
