### ISSUE TITLE
www-client/ungoogled-chromium-bin unlock version dependency on dev-libs/icu

### ISSUE THREAD

**Issue by Kusoneko** [PF4Public/gentoo-overlay#89]
Hello,

I'm unsure if there's a specific reason why `www-client/ungoogled-chromium-bin` forces the use of `=dev-libs/icu-68`. If there isn't a specific reason, could I suggest that it be changed to `>=dev-libs/icu-68`, as `dev-libs/icu-69.x` has been stabilized in the gentoo repository, and updating throws a bunch of warnings about `dev-libs/icu-68` not being able to be upgraded due to a dependecy conflict, and after looking at all the packages listed, only ungoogled-chromium-bin from this overlay is conflicting with every other package, which all allow version 69.

Essentially, this is asking if there's a specific reason why `dev-libs/icu` is locked to version 68 in the dependencies of `www-client/ungoogle-chromium-bin`, and if there isn't one, to change the line from `=dev-libs/icu-68` to `>=dev-libs/icu-68` so that icu can be upgraded.

Thanks,
Kusoneko.

**Comment by PF4Public** [comment]
>Essentially, this is asking if there's a specific reason why dev-libs/icu is locked to version 68 in the dependencies of `www-client/ungoogle-chromium-bin`

This is because `ungoogle-chromium-bin` is a binary version of `ungoogled-chromium`. At the time I was building it actual ICU version was 68 and it is linked to it therefore. To update this ICU dependency I would be needing to rebuild `ungoogle-chromium-bin`. I'm not up to rebuilding `ungoogle-chromium-bin` every now and then as building 4 variants already takes a considerable amount of computational power.

On the other hand you may consider building `ungoogle-chromium` yourself, which does accept any available ICU you throw at it.

**Comment by Kusoneko** [comment]
> > Essentially, this is asking if there's a specific reason why dev-libs/icu is locked to version 68 in the dependencies of `www-client/ungoogle-chromium-bin`
> 
> This is because `ungoogle-chromium-bin` is a binary version of `ungoogled-chromium`. At the time I was building it actual ICU version was 68 and it is linked to it therefore. To update this ICU dependency I would be needing to rebuild `ungoogle-chromium-bin`. I'm not up to rebuilding `ungoogle-chromium-bin` every now and then as building 4 variants already takes a considerable amount of computational power.
> 
> On the other hand you may consider building `ungoogle-chromium` yourself, which does accept any available ICU you throw at it.

Thank you for your reply, I indeed went and built it myself, and I understand why you weren't keen on doing it. It literally took over 2 days to do. If I needed any proof that web browsers are bloated, this is it. It spent most of the time compiling 2 chunks of roughly 20-25k code files into various things.

**Comment by PF4Public** [comment]
> It literally took over 2 days to do. If I needed any proof that web browsers are bloated

That depends heavily on your hardware, you might have encountered disk thrashing, which significantly slowed the compilation.

**Comment by PF4Public** [comment]
`www-client/ungoogled-chromium-bin-91.0.4472.101` will depend on ICU-69. In case anyone interested.
