### ISSUE TITLE
www-client:ungoogled-chromium-91.0.4472.77-r1: cursor.h:65:5: error: static_assert failed due to requirement 'std::is_standard_layout<sql::recover::VirtualCursor>::value' "needed for the reinterpret_cast below"

### ISSUE THREAD

**Issue by crabbedhaloablution** [PF4Public/gentoo-overlay#91]
Kind of vanilla setup. I suspect it's the use-flags, so if you have a set of working use-flags I could hopefully get an idea of where to start looking.

**Comment by crabbedhaloablution** [comment]
[Build log](http://dpaste.com/BPMG79DW6)

**Comment by PF4Public** [comment]
> get an idea of where to start looking

How about starting [here](https://github.com/PF4Public/gentoo-overlay/issues?q=is%3Aissue+cursor.h)?

**Comment by PF4Public** [comment]
Please see #94 and let me know in _that_ issue, if suggested patch works for you and is a reasonable fix.
