### ISSUE TITLE
www-client/ungoogled-chromium-91.0.4472.114-r1: failed to compile

### ISSUE THREAD

**Issue by groundflyer** [PF4Public/gentoo-overlay#92]
Merging www-client/ungoogled-chromium-91.0.4472.114-r1 with clang fails with an error:
```
x86_64-pc-linux-gnu-clang++: warning: .: 'linker' input unused [-Wunused-command-line-argument]
x86_64-pc-linux-gnu-clang++: warning: argument unused during compilation: '-Xcláng' [-Wunused-command-line-argument]
error: unknown argument: '-instcombine-lower-dbg-declare=0'
```
Flags enabled: clang official optimize-thinlto optimize-webui partition proprietary-codecs system-re2 thinlto

**Comment by PF4Public** [comment]
What is your clang version?

**Comment by groundflyer** [comment]
Latest stable 12.0.0-r1

**Comment by PF4Public** [comment]
Please provide the full build log.

**Comment by groundflyer** [comment]
Sure, https://www.mediafire.com/file/5xmx5xtwwgzdgbx/build.tar.xz/file

**Comment by PF4Public** [comment]
Have you tried [this patch](https://github.com/saiarcot895/chromium-ubuntu-build/blob/master/debian/patches/revert-Xclang-instcombine-lower-dbg-declare.patch)?

**Comment by groundflyer** [comment]
Just merged the package. That patch helps.
Will you incorporate it?

**Comment by PF4Public** [comment]
I've added a commit d004a547e97d7d2701d0c9432e8e93a4c46b2163. It would be awesome, if you could try compiling chromium once again without any additional patches to verify that this fix is sufficient.

**Comment by PF4Public** [comment]
I'll just assume it is OK now.
