### ISSUE TITLE
ungoogled-chromium-91.0.4472.114-r1: build fails with system-re2

### ISSUE THREAD

**Issue by N-R-K** [PF4Public/gentoo-overlay#93]
I'm using gcc-10.3 for this build due to https://github.com/PF4Public/gentoo-overlay/issues/87 but gcc-11.1.0 for everything else.
I tried rebuilding lld, clang, llvm and re2 but they didn't help. After setting `-system-re2` useflag, I was able to build successfully. I thought about rebuilding re2 with gcc10.3 but I'm not curious enough to recompile for 3 more hours to find out if that works or not.

Opening this issue in case someone else runs into the same problem, feel free to close it as you see fit.

```
[22562/22563] touch obj/third_party/blink/public/blink.stamp
[22563/22563] python "../../build/toolchain/gcc_link_wrapper.py" --output="./v8_context_snapshot_generator" -- x86_64-pc-linux-gnu-clang++ -fuse-ld=lld -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=5 -fwhole-program-vtables -rdynamic -Wl,--lto-O0 -pie -Wl,--disable-new-dtags -Wl,--icf=none -Wl,-O1 -Wl,--as-needed -Wl,--thinlto-jobs=12 -o "./v8_context_snapshot_generator" -Wl,--start-group @"./v8_context_snapshot_generator.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -ljsoncpp -licui18n -licuuc -licudata -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lz -levent -ljpeg -lpng16 -lxml2 -lxslt -lresolv -lgio-2.0 -lwebpdemux -lwebpmux -lwebp -lfreetype -lexpat -lfontconfig -lharfbuzz-subset -lharfbuzz -lm -lopus -lavcodec -lavformat -lavutil -lopenh264 -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender -lXrandr -lXtst -lxcb -ldrm -lre2 -lxkbcommon -lgbm -lXi -lpci -lasound -lsnappy -ldbus-1 -latk-1.0 -latk-bridge-2.0 -latspi -lpangocairo-1.0 -lpango-1.0 -lcairo
[31mFAILED: [0mv8_context_snapshot_generator 
python "../../build/toolchain/gcc_link_wrapper.py" --output="./v8_context_snapshot_generator" -- x86_64-pc-linux-gnu-clang++ -fuse-ld=lld -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=5 -fwhole-program-vtables -rdynamic -Wl,--lto-O0 -pie -Wl,--disable-new-dtags -Wl,--icf=none -Wl,-O1 -Wl,--as-needed -Wl,--thinlto-jobs=12 -o "./v8_context_snapshot_generator" -Wl,--start-group @"./v8_context_snapshot_generator.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -ljsoncpp -licui18n -licuuc -licudata -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lz -levent -ljpeg -lpng16 -lxml2 -lxslt -lresolv -lgio-2.0 -lwebpdemux -lwebpmux -lwebp -lfreetype -lexpat -lfontconfig -lharfbuzz-subset -lharfbuzz -lm -lopus -lavcodec -lavformat -lavutil -lopenh264 -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender -lXrandr -lXtst -lxcb -ldrm -lre2 -lxkbcommon -lgbm -lXi -lpci -lasound -lsnappy -ldbus-1 -latk-1.0 -latk-bridge-2.0 -latspi -lpangocairo-1.0 -lpango-1.0 -lcairo
ld.lld: [0;31merror: [0m/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../lib64/libre2.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve()@GLIBCXX_3.4.29 [--no-allow-shlib-undefined]
ld.lld: [0;31merror: [0m/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../lib64/libre2.so: undefined reference to std::__throw_bad_array_new_length()@GLIBCXX_3.4.29 [--no-allow-shlib-undefined]
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Full build log: https://we.tl/t-fhtvaCV1vg

**Comment by PF4Public** [comment]
You are telling that you are using gcc, but your excerpt says it is going to be compiling it with `x86_64-pc-linux-gnu-clang++`. How come?

Please, attach your build log here without using any external filehostings.

**Comment by N-R-K** [comment]
> How come?

Oh sorry for being misleading. I tried to build ugc with ``-clang`` long ago but it didn't build even with ``-custom-cflags`` so I have been using ``clang`` useflag ever since.
When I said I'm using gcc:10.3 for this build I meant setting gcc:10.3 through ``gcc-config`` (due to https://github.com/PF4Public/gentoo-overlay/issues/87) . This is once again with ``clang`` useflag just to be clear.



> Please, attach your build log here without using any external filehostings.

Not sure how to do that, dragging and dropping the log here doesn't seem to do anything.

**Comment by PF4Public** [comment]
OK, got it.

Given that it complains like this: `/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../lib64/libre2.so` it is obvious that it references (kind of) gcc10 for this compilation and this: `std::__cxx11::basic_string<char, std::char_traits<char>` is obviously a C++ symbol in a library. Most likely it should belong to `libstdc++`. Now I suppose that if you've built `libre2` and `libstdc++` with gcc-11 both, but use gcc-10 for UGC, it might somehow affect symbol resolution while linking UGC to `libre2`. If that's the case, then this probably could be avoided if re-building `libre2` with gcc-10.

Which compiler did you use for `libre2` and `libstdc++` in the end? Did I guess it right?

**Comment by N-R-K** [comment]
> Which compiler did you use for `libre2` and `libstdc++` in the end? Did I guess it right?

Correct. Everything is build with gcc:11 including ``dev-libs/libre2``,  however I don't have ``sys-libs/libstdc++-v3`` installed on my system (I'm assuming that's what you're reffering to with ``libstdc++``)
Only time I switch to gcc:10 is right before emerging ugc.

**Comment by PF4Public** [comment]
Well, if you've used gcc-11 for everything else, I suppose that everything else works fine, including the dependants of `libre2`. That means that only due to the need for gcc-10 UGC cannot resolve all symbols.

So to sum things up:
* ✔️ Using gcc-10 by default succeeds the compilation of UGC even with `clang`
* ❌ Using gcc-11 by default fails the compilation of UGC with `clang`
* ❌ Using gcc-10 by default only when compiling UGC fails with `system-re2`
* ✔️ Using gcc-10 by default only when compiling UGC succeeds with `-system-re2`
* ❔ Using gcc-10 by default only when compiling UGC with `system-re2` could potentially succeed if also building `libre2` with gcc-10, but noone tried. It could very well also fail or have other side-effects on other packages.
* ❔ Compiling UGC with `system-re2` `clang` and gcc-11 by default with `ld` instead of `ldd` could potentially succeed, but noone tried. It could very well also fail. But in turn this requires disabling `thinlto` and so on.

Thus I think now it is thoroughly examined and there is nothing left to do.

Thank you for reporting, I hope this would be helpful for anyone encountering the same.

> I don't have `sys-libs/libstdc++-v3` installed on my system (I'm assuming that's what you're reffering to with `libstdc++`)

~Still you cannot _not_ have it (sorry for double negation).~
It doesn't mean you don't have it:
```
 # ldd /usr/lib64/libre2.so
        linux-vdso.so.1 (0x00007ffd955b4000)
        libicuuc.so.69 => /usr/lib64/libicuuc.so.69 (0x00007f8685788000)
        libicudata.so.69 => /usr/lib64/libicudata.so.69 (0x00007f8683c2e000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so.6 (0x00007f8683a60000)
        libgomp.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libgomp.so.1 (0x00007f8683a24000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libgcc_s.so.1 (0x00007f8683a0a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f86839ec000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f868381f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8685a76000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f8683819000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f86836e2000)
# equery b /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so.6
 * Searching for /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so.6 ... 
sys-devel/gcc-10.3.0 (/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so.6 -> libstdc++.so.6.0.28)
sys-devel/gcc-10.3.0 (/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so.6.0.28)
```

**Comment by PF4Public** [comment]
Please see #94 you might be interested in a solution for a "cursor.h" issue and let me know in _that_ issue, if suggested patch works for you and is a reasonable fix.
